// Generated by abi-to-zod v0.0.0 from Bridge.json
// Do not edit manually -- regenerate from source.

import { z } from 'zod';

// === Primitive schemas (edit once to customise all uses) ===

const ADDRESS = z.string().regex(/^0x[0-9a-fA-F]{40}$/).transform((v) => v as `0x${string}`);
const BOOL = z.boolean();
const BYTES = z.string().regex(/^0x([0-9a-fA-F]{2})*$/).transform((v) => v as `0x${string}`);
const BYTES32 = z.string().regex(/^0x[0-9a-fA-F]{64}$/).transform((v) => v as `0x${string}`);
const UINT256 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 256n) - 1n);
const UINT8 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 8n) - 1n);

// === Function schemas ===

// acceptFundsFromOldBridge()
export const acceptFundsFromOldBridgeSchema = z.tuple([]);

// activeOutbox()
export const activeOutboxSchema = z.tuple([]);

// allowedDelayedInboxList(uint256)
export const allowedDelayedInboxListSchema = z.tuple([
  /* uint256 */ UINT256,
]);

// allowedDelayedInboxes(address)
export const allowedDelayedInboxesSchema = z.tuple([
  /* inbox: address */ ADDRESS,
]);

// allowedOutboxList(uint256)
export const allowedOutboxListSchema = z.tuple([
  /* uint256 */ UINT256,
]);

// allowedOutboxes(address)
export const allowedOutboxesSchema = z.tuple([
  /* outbox: address */ ADDRESS,
]);

// delayedInboxAccs(uint256)
export const delayedInboxAccsSchema = z.tuple([
  /* uint256 */ UINT256,
]);

// delayedMessageCount()
export const delayedMessageCountSchema = z.tuple([]);

// enqueueDelayedMessage(uint8,address,bytes32)
export const enqueueDelayedMessageSchema = z.tuple([
  /* kind: uint8 */ UINT8,
  /* sender: address */ ADDRESS,
  /* messageDataHash: bytes32 */ BYTES32,
]);

// enqueueSequencerMessage(bytes32,uint256,uint256,uint256)
export const enqueueSequencerMessageSchema = z.tuple([
  /* dataHash: bytes32 */ BYTES32,
  /* afterDelayedMessagesRead: uint256 */ UINT256,
  /* prevMessageCount: uint256 */ UINT256,
  /* newMessageCount: uint256 */ UINT256,
]);

// executeCall(address,uint256,bytes)
export const executeCallSchema = z.tuple([
  /* to: address */ ADDRESS,
  /* value: uint256 */ UINT256,
  /* data: bytes */ BYTES,
]);

// initialize(address)
export const initializeSchema = z.tuple([
  /* rollup_: address */ ADDRESS,
]);

// rollup()
export const rollupSchema = z.tuple([]);

// sequencerInbox()
export const sequencerInboxSchema = z.tuple([]);

// sequencerInboxAccs(uint256)
export const sequencerInboxAccsSchema = z.tuple([
  /* uint256 */ UINT256,
]);

// sequencerMessageCount()
export const sequencerMessageCountSchema = z.tuple([]);

// sequencerReportedSubMessageCount()
export const sequencerReportedSubMessageCountSchema = z.tuple([]);

// setDelayedInbox(address,bool)
export const setDelayedInboxSchema = z.tuple([
  /* inbox: address */ ADDRESS,
  /* enabled: bool */ BOOL,
]);

// setOutbox(address,bool)
export const setOutboxSchema = z.tuple([
  /* outbox: address */ ADDRESS,
  /* enabled: bool */ BOOL,
]);

// setSequencerInbox(address)
export const setSequencerInboxSchema = z.tuple([
  /* _sequencerInbox: address */ ADDRESS,
]);

// setSequencerReportedSubMessageCount(uint256)
export const setSequencerReportedSubMessageCountSchema = z.tuple([
  /* newMsgCount: uint256 */ UINT256,
]);

// submitBatchSpendingReport(address,bytes32)
export const submitBatchSpendingReportSchema = z.tuple([
  /* sender: address */ ADDRESS,
  /* messageDataHash: bytes32 */ BYTES32,
]);

// updateRollupAddress(address)
export const updateRollupAddressSchema = z.tuple([
  /* _rollup: address */ ADDRESS,
]);

// === Lookup barrel (mirrors abiToZod) ===

export const schemas = {
  acceptFundsFromOldBridge: acceptFundsFromOldBridgeSchema,
  activeOutbox: activeOutboxSchema,
  allowedDelayedInboxList: allowedDelayedInboxListSchema,
  allowedDelayedInboxes: allowedDelayedInboxesSchema,
  allowedOutboxList: allowedOutboxListSchema,
  allowedOutboxes: allowedOutboxesSchema,
  delayedInboxAccs: delayedInboxAccsSchema,
  delayedMessageCount: delayedMessageCountSchema,
  enqueueDelayedMessage: enqueueDelayedMessageSchema,
  enqueueSequencerMessage: enqueueSequencerMessageSchema,
  executeCall: executeCallSchema,
  initialize: initializeSchema,
  rollup: rollupSchema,
  sequencerInbox: sequencerInboxSchema,
  sequencerInboxAccs: sequencerInboxAccsSchema,
  sequencerMessageCount: sequencerMessageCountSchema,
  sequencerReportedSubMessageCount: sequencerReportedSubMessageCountSchema,
  setDelayedInbox: setDelayedInboxSchema,
  setOutbox: setOutboxSchema,
  setSequencerInbox: setSequencerInboxSchema,
  setSequencerReportedSubMessageCount: setSequencerReportedSubMessageCountSchema,
  submitBatchSpendingReport: submitBatchSpendingReportSchema,
  updateRollupAddress: updateRollupAddressSchema,
  'acceptFundsFromOldBridge()': acceptFundsFromOldBridgeSchema,
  'activeOutbox()': activeOutboxSchema,
  'allowedDelayedInboxList(uint256)': allowedDelayedInboxListSchema,
  'allowedDelayedInboxes(address)': allowedDelayedInboxesSchema,
  'allowedOutboxList(uint256)': allowedOutboxListSchema,
  'allowedOutboxes(address)': allowedOutboxesSchema,
  'delayedInboxAccs(uint256)': delayedInboxAccsSchema,
  'delayedMessageCount()': delayedMessageCountSchema,
  'enqueueDelayedMessage(uint8,address,bytes32)': enqueueDelayedMessageSchema,
  'enqueueSequencerMessage(bytes32,uint256,uint256,uint256)': enqueueSequencerMessageSchema,
  'executeCall(address,uint256,bytes)': executeCallSchema,
  'initialize(address)': initializeSchema,
  'rollup()': rollupSchema,
  'sequencerInbox()': sequencerInboxSchema,
  'sequencerInboxAccs(uint256)': sequencerInboxAccsSchema,
  'sequencerMessageCount()': sequencerMessageCountSchema,
  'sequencerReportedSubMessageCount()': sequencerReportedSubMessageCountSchema,
  'setDelayedInbox(address,bool)': setDelayedInboxSchema,
  'setOutbox(address,bool)': setOutboxSchema,
  'setSequencerInbox(address)': setSequencerInboxSchema,
  'setSequencerReportedSubMessageCount(uint256)': setSequencerReportedSubMessageCountSchema,
  'submitBatchSpendingReport(address,bytes32)': submitBatchSpendingReportSchema,
  'updateRollupAddress(address)': updateRollupAddressSchema,
} as const;
