// Generated by abi-to-zod v0.0.0 from EdgeChallengeManager.json
// Do not edit manually -- regenerate from source.

import { z } from 'zod';

// === Primitive schemas (edit once to customise all uses) ===

const ADDRESS = z.string().regex(/^0x[0-9a-fA-F]{40}$/).transform((v) => v as `0x${string}`);
const BYTES = z.string().regex(/^0x([0-9a-fA-F]{2})*$/).transform((v) => v as `0x${string}`);
const BYTES32 = z.string().regex(/^0x[0-9a-fA-F]{64}$/).transform((v) => v as `0x${string}`);
const UINT256 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 256n) - 1n);
const UINT64 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 64n) - 1n);
const UINT8 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 8n) - 1n);

// === Function schemas ===

// LAYERZERO_BIGSTEPEDGE_HEIGHT()
export const LAYERZERO_BIGSTEPEDGE_HEIGHTSchema = z.tuple([]);

// LAYERZERO_BLOCKEDGE_HEIGHT()
export const LAYERZERO_BLOCKEDGE_HEIGHTSchema = z.tuple([]);

// LAYERZERO_SMALLSTEPEDGE_HEIGHT()
export const LAYERZERO_SMALLSTEPEDGE_HEIGHTSchema = z.tuple([]);

// NUM_BIGSTEP_LEVEL()
export const NUM_BIGSTEP_LEVELSchema = z.tuple([]);

// assertionChain()
export const assertionChainSchema = z.tuple([]);

// bisectEdge(bytes32,bytes32,bytes)
export const bisectEdgeSchema = z.tuple([
  /* edgeId: bytes32 */ BYTES32,
  /* bisectionHistoryRoot: bytes32 */ BYTES32,
  /* prefixProof: bytes */ BYTES,
]);

// calculateEdgeId(uint8,bytes32,uint256,bytes32,uint256,bytes32)
export const calculateEdgeIdSchema = z.tuple([
  /* level: uint8 */ UINT8,
  /* originId: bytes32 */ BYTES32,
  /* startHeight: uint256 */ UINT256,
  /* startHistoryRoot: bytes32 */ BYTES32,
  /* endHeight: uint256 */ UINT256,
  /* endHistoryRoot: bytes32 */ BYTES32,
]);

// calculateMutualId(uint8,bytes32,uint256,bytes32,uint256)
export const calculateMutualIdSchema = z.tuple([
  /* level: uint8 */ UINT8,
  /* originId: bytes32 */ BYTES32,
  /* startHeight: uint256 */ UINT256,
  /* startHistoryRoot: bytes32 */ BYTES32,
  /* endHeight: uint256 */ UINT256,
]);

// challengePeriodBlocks()
export const challengePeriodBlocksSchema = z.tuple([]);

// confirmEdgeByOneStepProof(bytes32,(bytes32,bytes),(bytes32,uint256,address,uint64,uint64),bytes32[],bytes32[])
export const confirmEdgeByOneStepProofSchema = z.tuple([
  /* edgeId: bytes32 */ BYTES32,
  /* oneStepData: (bytes32,bytes) */ z.tuple([
    /* beforeHash: bytes32 */ BYTES32,
    /* proof: bytes */ BYTES,
  ]),
  /* prevConfig: (bytes32,uint256,address,uint64,uint64) */ z.tuple([
    /* wasmModuleRoot: bytes32 */ BYTES32,
    /* requiredStake: uint256 */ UINT256,
    /* challengeManager: address */ ADDRESS,
    /* confirmPeriodBlocks: uint64 */ UINT64,
    /* nextInboxPosition: uint64 */ UINT64,
  ]),
  /* beforeHistoryInclusionProof: bytes32[] */ z.array(BYTES32),
  /* afterHistoryInclusionProof: bytes32[] */ z.array(BYTES32),
]);

// confirmEdgeByTime(bytes32,(((bytes32[2],uint64[2]),uint8,bytes32),bytes32,bytes32))
export const confirmEdgeByTimeSchema = z.tuple([
  /* edgeId: bytes32 */ BYTES32,
  /* claimStateData: (((bytes32[2],uint64[2]),uint8,bytes32),bytes32,bytes32) */ z.tuple([
    /* assertionState: ((bytes32[2],uint64[2]),uint8,bytes32) */ z.tuple([
      /* globalState: (bytes32[2],uint64[2]) */ z.tuple([
        /* bytes32Vals: bytes32[2] */ z.array(BYTES32).length(2),
        /* u64Vals: uint64[2] */ z.array(UINT64).length(2),
      ]),
      /* machineStatus: uint8 */ UINT8,
      /* endHistoryRoot: bytes32 */ BYTES32,
    ]),
    /* prevAssertionHash: bytes32 */ BYTES32,
    /* inboxAcc: bytes32 */ BYTES32,
  ]),
]);

// confirmedRival(bytes32)
export const confirmedRivalSchema = z.tuple([
  /* mutualId: bytes32 */ BYTES32,
]);

// createLayerZeroEdge((uint8,bytes32,uint256,bytes32,bytes,bytes))
export const createLayerZeroEdgeSchema = z.tuple([
  /* args: (uint8,bytes32,uint256,bytes32,bytes,bytes) */ z.tuple([
    /* level: uint8 */ UINT8,
    /* endHistoryRoot: bytes32 */ BYTES32,
    /* endHeight: uint256 */ UINT256,
    /* claimId: bytes32 */ BYTES32,
    /* prefixProof: bytes */ BYTES,
    /* proof: bytes */ BYTES,
  ]),
]);

// edgeExists(bytes32)
export const edgeExistsSchema = z.tuple([
  /* edgeId: bytes32 */ BYTES32,
]);

// edgeLength(bytes32)
export const edgeLengthSchema = z.tuple([
  /* edgeId: bytes32 */ BYTES32,
]);

// excessStakeReceiver()
export const excessStakeReceiverSchema = z.tuple([]);

// firstRival(bytes32)
export const firstRivalSchema = z.tuple([
  /* mutualId: bytes32 */ BYTES32,
]);

// getEdge(bytes32)
export const getEdgeSchema = z.tuple([
  /* edgeId: bytes32 */ BYTES32,
]);

// getLayerZeroEndHeight(uint8)
export const getLayerZeroEndHeightSchema = z.tuple([
  /* eType: uint8 */ UINT8,
]);

// getPrevAssertionHash(bytes32)
export const getPrevAssertionHashSchema = z.tuple([
  /* edgeId: bytes32 */ BYTES32,
]);

// hasLengthOneRival(bytes32)
export const hasLengthOneRivalSchema = z.tuple([
  /* edgeId: bytes32 */ BYTES32,
]);

// hasMadeLayerZeroRival(address,bytes32)
export const hasMadeLayerZeroRivalSchema = z.tuple([
  /* account: address */ ADDRESS,
  /* mutualId: bytes32 */ BYTES32,
]);

// hasRival(bytes32)
export const hasRivalSchema = z.tuple([
  /* edgeId: bytes32 */ BYTES32,
]);

// initialize(address,uint64,address,uint256,uint256,uint256,address,address,uint8,uint256[])
export const initializeSchema = z.tuple([
  /* _assertionChain: address */ ADDRESS,
  /* _challengePeriodBlocks: uint64 */ UINT64,
  /* _oneStepProofEntry: address */ ADDRESS,
  /* layerZeroBlockEdgeHeight: uint256 */ UINT256,
  /* layerZeroBigStepEdgeHeight: uint256 */ UINT256,
  /* layerZeroSmallStepEdgeHeight: uint256 */ UINT256,
  /* _stakeToken: address */ ADDRESS,
  /* _excessStakeReceiver: address */ ADDRESS,
  /* _numBigStepLevel: uint8 */ UINT8,
  /* _stakeAmounts: uint256[] */ z.array(UINT256),
]);

// multiUpdateTimeCacheByChildren(bytes32[],uint256)
export const multiUpdateTimeCacheByChildrenSchema = z.tuple([
  /* edgeIds: bytes32[] */ z.array(BYTES32),
  /* maximumCachedTime: uint256 */ UINT256,
]);

// oneStepProofEntry()
export const oneStepProofEntrySchema = z.tuple([]);

// refundStake(bytes32)
export const refundStakeSchema = z.tuple([
  /* edgeId: bytes32 */ BYTES32,
]);

// stakeAmounts(uint256)
export const stakeAmountsSchema = z.tuple([
  /* uint256 */ UINT256,
]);

// stakeToken()
export const stakeTokenSchema = z.tuple([]);

// timeUnrivaled(bytes32)
export const timeUnrivaledSchema = z.tuple([
  /* edgeId: bytes32 */ BYTES32,
]);

// updateTimerCacheByChildren(bytes32,uint256)
export const updateTimerCacheByChildrenSchema = z.tuple([
  /* edgeId: bytes32 */ BYTES32,
  /* maximumCachedTime: uint256 */ UINT256,
]);

// updateTimerCacheByClaim(bytes32,bytes32,uint256)
export const updateTimerCacheByClaimSchema = z.tuple([
  /* edgeId: bytes32 */ BYTES32,
  /* claimingEdgeId: bytes32 */ BYTES32,
  /* maximumCachedTime: uint256 */ UINT256,
]);

// === Lookup barrel (mirrors abiToZod) ===

export const schemas = {
  LAYERZERO_BIGSTEPEDGE_HEIGHT: LAYERZERO_BIGSTEPEDGE_HEIGHTSchema,
  LAYERZERO_BLOCKEDGE_HEIGHT: LAYERZERO_BLOCKEDGE_HEIGHTSchema,
  LAYERZERO_SMALLSTEPEDGE_HEIGHT: LAYERZERO_SMALLSTEPEDGE_HEIGHTSchema,
  NUM_BIGSTEP_LEVEL: NUM_BIGSTEP_LEVELSchema,
  assertionChain: assertionChainSchema,
  bisectEdge: bisectEdgeSchema,
  calculateEdgeId: calculateEdgeIdSchema,
  calculateMutualId: calculateMutualIdSchema,
  challengePeriodBlocks: challengePeriodBlocksSchema,
  confirmEdgeByOneStepProof: confirmEdgeByOneStepProofSchema,
  confirmEdgeByTime: confirmEdgeByTimeSchema,
  confirmedRival: confirmedRivalSchema,
  createLayerZeroEdge: createLayerZeroEdgeSchema,
  edgeExists: edgeExistsSchema,
  edgeLength: edgeLengthSchema,
  excessStakeReceiver: excessStakeReceiverSchema,
  firstRival: firstRivalSchema,
  getEdge: getEdgeSchema,
  getLayerZeroEndHeight: getLayerZeroEndHeightSchema,
  getPrevAssertionHash: getPrevAssertionHashSchema,
  hasLengthOneRival: hasLengthOneRivalSchema,
  hasMadeLayerZeroRival: hasMadeLayerZeroRivalSchema,
  hasRival: hasRivalSchema,
  initialize: initializeSchema,
  multiUpdateTimeCacheByChildren: multiUpdateTimeCacheByChildrenSchema,
  oneStepProofEntry: oneStepProofEntrySchema,
  refundStake: refundStakeSchema,
  stakeAmounts: stakeAmountsSchema,
  stakeToken: stakeTokenSchema,
  timeUnrivaled: timeUnrivaledSchema,
  updateTimerCacheByChildren: updateTimerCacheByChildrenSchema,
  updateTimerCacheByClaim: updateTimerCacheByClaimSchema,
  'LAYERZERO_BIGSTEPEDGE_HEIGHT()': LAYERZERO_BIGSTEPEDGE_HEIGHTSchema,
  'LAYERZERO_BLOCKEDGE_HEIGHT()': LAYERZERO_BLOCKEDGE_HEIGHTSchema,
  'LAYERZERO_SMALLSTEPEDGE_HEIGHT()': LAYERZERO_SMALLSTEPEDGE_HEIGHTSchema,
  'NUM_BIGSTEP_LEVEL()': NUM_BIGSTEP_LEVELSchema,
  'assertionChain()': assertionChainSchema,
  'bisectEdge(bytes32,bytes32,bytes)': bisectEdgeSchema,
  'calculateEdgeId(uint8,bytes32,uint256,bytes32,uint256,bytes32)': calculateEdgeIdSchema,
  'calculateMutualId(uint8,bytes32,uint256,bytes32,uint256)': calculateMutualIdSchema,
  'challengePeriodBlocks()': challengePeriodBlocksSchema,
  'confirmEdgeByOneStepProof(bytes32,(bytes32,bytes),(bytes32,uint256,address,uint64,uint64),bytes32[],bytes32[])': confirmEdgeByOneStepProofSchema,
  'confirmEdgeByTime(bytes32,(((bytes32[2],uint64[2]),uint8,bytes32),bytes32,bytes32))': confirmEdgeByTimeSchema,
  'confirmedRival(bytes32)': confirmedRivalSchema,
  'createLayerZeroEdge((uint8,bytes32,uint256,bytes32,bytes,bytes))': createLayerZeroEdgeSchema,
  'edgeExists(bytes32)': edgeExistsSchema,
  'edgeLength(bytes32)': edgeLengthSchema,
  'excessStakeReceiver()': excessStakeReceiverSchema,
  'firstRival(bytes32)': firstRivalSchema,
  'getEdge(bytes32)': getEdgeSchema,
  'getLayerZeroEndHeight(uint8)': getLayerZeroEndHeightSchema,
  'getPrevAssertionHash(bytes32)': getPrevAssertionHashSchema,
  'hasLengthOneRival(bytes32)': hasLengthOneRivalSchema,
  'hasMadeLayerZeroRival(address,bytes32)': hasMadeLayerZeroRivalSchema,
  'hasRival(bytes32)': hasRivalSchema,
  'initialize(address,uint64,address,uint256,uint256,uint256,address,address,uint8,uint256[])': initializeSchema,
  'multiUpdateTimeCacheByChildren(bytes32[],uint256)': multiUpdateTimeCacheByChildrenSchema,
  'oneStepProofEntry()': oneStepProofEntrySchema,
  'refundStake(bytes32)': refundStakeSchema,
  'stakeAmounts(uint256)': stakeAmountsSchema,
  'stakeToken()': stakeTokenSchema,
  'timeUnrivaled(bytes32)': timeUnrivaledSchema,
  'updateTimerCacheByChildren(bytes32,uint256)': updateTimerCacheByChildrenSchema,
  'updateTimerCacheByClaim(bytes32,bytes32,uint256)': updateTimerCacheByClaimSchema,
} as const;
