// Generated by abi-to-zod v0.0.0 from Inbox.json
// Do not edit manually -- regenerate from source.

import { z } from 'zod';

// === Primitive schemas (edit once to customise all uses) ===

const ADDRESS = z.string().regex(/^0x[0-9a-fA-F]{40}$/).transform((v) => v as `0x${string}`);
const BOOL = z.boolean();
const BYTES = z.string().regex(/^0x([0-9a-fA-F]{2})*$/).transform((v) => v as `0x${string}`);
const UINT256 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 256n) - 1n);

// === Function schemas ===

// allowListEnabled()
export const allowListEnabledSchema = z.tuple([]);

// bridge()
export const bridgeSchema = z.tuple([]);

// calculateRetryableSubmissionFee(uint256,uint256)
export const calculateRetryableSubmissionFeeSchema = z.tuple([
  /* dataLength: uint256 */ UINT256,
  /* baseFee: uint256 */ UINT256,
]);

// createRetryableTicket(address,uint256,uint256,address,address,uint256,uint256,bytes)
export const createRetryableTicketSchema = z.tuple([
  /* to: address */ ADDRESS,
  /* l2CallValue: uint256 */ UINT256,
  /* maxSubmissionCost: uint256 */ UINT256,
  /* excessFeeRefundAddress: address */ ADDRESS,
  /* callValueRefundAddress: address */ ADDRESS,
  /* gasLimit: uint256 */ UINT256,
  /* maxFeePerGas: uint256 */ UINT256,
  /* data: bytes */ BYTES,
]);

// createRetryableTicketNoRefundAliasRewrite(address,uint256,uint256,address,address,uint256,uint256,bytes)
export const createRetryableTicketNoRefundAliasRewriteSchema = z.tuple([
  /* to: address */ ADDRESS,
  /* l2CallValue: uint256 */ UINT256,
  /* maxSubmissionCost: uint256 */ UINT256,
  /* excessFeeRefundAddress: address */ ADDRESS,
  /* callValueRefundAddress: address */ ADDRESS,
  /* gasLimit: uint256 */ UINT256,
  /* maxFeePerGas: uint256 */ UINT256,
  /* data: bytes */ BYTES,
]);

// getProxyAdmin()
export const getProxyAdminSchema = z.tuple([]);

// initialize(address,address)
export const initializeSchema = z.tuple([
  /* _bridge: address */ ADDRESS,
  /* _sequencerInbox: address */ ADDRESS,
]);

// isAllowed(address)
export const isAllowedSchema = z.tuple([
  /* address */ ADDRESS,
]);

// maxDataSize()
export const maxDataSizeSchema = z.tuple([]);

// pause()
export const pauseSchema = z.tuple([]);

// paused()
export const pausedSchema = z.tuple([]);

// postUpgradeInit(address)
export const postUpgradeInitSchema = z.tuple([
  /* address */ ADDRESS,
]);

// sendContractTransaction(uint256,uint256,address,uint256,bytes)
export const sendContractTransactionSchema = z.tuple([
  /* gasLimit: uint256 */ UINT256,
  /* maxFeePerGas: uint256 */ UINT256,
  /* to: address */ ADDRESS,
  /* value: uint256 */ UINT256,
  /* data: bytes */ BYTES,
]);

// sendL1FundedContractTransaction(uint256,uint256,address,bytes)
export const sendL1FundedContractTransactionSchema = z.tuple([
  /* gasLimit: uint256 */ UINT256,
  /* maxFeePerGas: uint256 */ UINT256,
  /* to: address */ ADDRESS,
  /* data: bytes */ BYTES,
]);

// sendL1FundedUnsignedTransaction(uint256,uint256,uint256,address,bytes)
export const sendL1FundedUnsignedTransactionSchema = z.tuple([
  /* gasLimit: uint256 */ UINT256,
  /* maxFeePerGas: uint256 */ UINT256,
  /* nonce: uint256 */ UINT256,
  /* to: address */ ADDRESS,
  /* data: bytes */ BYTES,
]);

// sendL1FundedUnsignedTransactionToFork(uint256,uint256,uint256,address,bytes)
export const sendL1FundedUnsignedTransactionToForkSchema = z.tuple([
  /* gasLimit: uint256 */ UINT256,
  /* maxFeePerGas: uint256 */ UINT256,
  /* nonce: uint256 */ UINT256,
  /* to: address */ ADDRESS,
  /* data: bytes */ BYTES,
]);

// sendL2Message(bytes)
export const sendL2MessageSchema = z.tuple([
  /* messageData: bytes */ BYTES,
]);

// sendL2MessageFromOrigin(bytes)
export const sendL2MessageFromOriginSchema = z.tuple([
  /* messageData: bytes */ BYTES,
]);

// sendUnsignedTransaction(uint256,uint256,uint256,address,uint256,bytes)
export const sendUnsignedTransactionSchema = z.tuple([
  /* gasLimit: uint256 */ UINT256,
  /* maxFeePerGas: uint256 */ UINT256,
  /* nonce: uint256 */ UINT256,
  /* to: address */ ADDRESS,
  /* value: uint256 */ UINT256,
  /* data: bytes */ BYTES,
]);

// sendUnsignedTransactionToFork(uint256,uint256,uint256,address,uint256,bytes)
export const sendUnsignedTransactionToForkSchema = z.tuple([
  /* gasLimit: uint256 */ UINT256,
  /* maxFeePerGas: uint256 */ UINT256,
  /* nonce: uint256 */ UINT256,
  /* to: address */ ADDRESS,
  /* value: uint256 */ UINT256,
  /* data: bytes */ BYTES,
]);

// sendWithdrawEthToFork(uint256,uint256,uint256,uint256,address)
export const sendWithdrawEthToForkSchema = z.tuple([
  /* gasLimit: uint256 */ UINT256,
  /* maxFeePerGas: uint256 */ UINT256,
  /* nonce: uint256 */ UINT256,
  /* value: uint256 */ UINT256,
  /* withdrawTo: address */ ADDRESS,
]);

// sequencerInbox()
export const sequencerInboxSchema = z.tuple([]);

// setAllowList(address[],bool[])
export const setAllowListSchema = z.tuple([
  /* user: address[] */ z.array(ADDRESS),
  /* val: bool[] */ z.array(BOOL),
]);

// setAllowListEnabled(bool)
export const setAllowListEnabledSchema = z.tuple([
  /* _allowListEnabled: bool */ BOOL,
]);

// unpause()
export const unpauseSchema = z.tuple([]);

// unsafeCreateRetryableTicket(address,uint256,uint256,address,address,uint256,uint256,bytes)
export const unsafeCreateRetryableTicketSchema = z.tuple([
  /* to: address */ ADDRESS,
  /* l2CallValue: uint256 */ UINT256,
  /* maxSubmissionCost: uint256 */ UINT256,
  /* excessFeeRefundAddress: address */ ADDRESS,
  /* callValueRefundAddress: address */ ADDRESS,
  /* gasLimit: uint256 */ UINT256,
  /* maxFeePerGas: uint256 */ UINT256,
  /* data: bytes */ BYTES,
]);

// === Lookup barrel (mirrors abiToZod) ===

export const schemas = {
  allowListEnabled: allowListEnabledSchema,
  bridge: bridgeSchema,
  calculateRetryableSubmissionFee: calculateRetryableSubmissionFeeSchema,
  createRetryableTicket: createRetryableTicketSchema,
  createRetryableTicketNoRefundAliasRewrite: createRetryableTicketNoRefundAliasRewriteSchema,
  getProxyAdmin: getProxyAdminSchema,
  initialize: initializeSchema,
  isAllowed: isAllowedSchema,
  maxDataSize: maxDataSizeSchema,
  pause: pauseSchema,
  paused: pausedSchema,
  postUpgradeInit: postUpgradeInitSchema,
  sendContractTransaction: sendContractTransactionSchema,
  sendL1FundedContractTransaction: sendL1FundedContractTransactionSchema,
  sendL1FundedUnsignedTransaction: sendL1FundedUnsignedTransactionSchema,
  sendL1FundedUnsignedTransactionToFork: sendL1FundedUnsignedTransactionToForkSchema,
  sendL2Message: sendL2MessageSchema,
  sendL2MessageFromOrigin: sendL2MessageFromOriginSchema,
  sendUnsignedTransaction: sendUnsignedTransactionSchema,
  sendUnsignedTransactionToFork: sendUnsignedTransactionToForkSchema,
  sendWithdrawEthToFork: sendWithdrawEthToForkSchema,
  sequencerInbox: sequencerInboxSchema,
  setAllowList: setAllowListSchema,
  setAllowListEnabled: setAllowListEnabledSchema,
  unpause: unpauseSchema,
  unsafeCreateRetryableTicket: unsafeCreateRetryableTicketSchema,
  'allowListEnabled()': allowListEnabledSchema,
  'bridge()': bridgeSchema,
  'calculateRetryableSubmissionFee(uint256,uint256)': calculateRetryableSubmissionFeeSchema,
  'createRetryableTicket(address,uint256,uint256,address,address,uint256,uint256,bytes)': createRetryableTicketSchema,
  'createRetryableTicketNoRefundAliasRewrite(address,uint256,uint256,address,address,uint256,uint256,bytes)': createRetryableTicketNoRefundAliasRewriteSchema,
  'depositEth()': z.tuple([]),
  'depositEth(uint256)': z.tuple([
    /* uint256 */ UINT256,
  ]),
  'getProxyAdmin()': getProxyAdminSchema,
  'initialize(address,address)': initializeSchema,
  'isAllowed(address)': isAllowedSchema,
  'maxDataSize()': maxDataSizeSchema,
  'pause()': pauseSchema,
  'paused()': pausedSchema,
  'postUpgradeInit(address)': postUpgradeInitSchema,
  'sendContractTransaction(uint256,uint256,address,uint256,bytes)': sendContractTransactionSchema,
  'sendL1FundedContractTransaction(uint256,uint256,address,bytes)': sendL1FundedContractTransactionSchema,
  'sendL1FundedUnsignedTransaction(uint256,uint256,uint256,address,bytes)': sendL1FundedUnsignedTransactionSchema,
  'sendL1FundedUnsignedTransactionToFork(uint256,uint256,uint256,address,bytes)': sendL1FundedUnsignedTransactionToForkSchema,
  'sendL2Message(bytes)': sendL2MessageSchema,
  'sendL2MessageFromOrigin(bytes)': sendL2MessageFromOriginSchema,
  'sendUnsignedTransaction(uint256,uint256,uint256,address,uint256,bytes)': sendUnsignedTransactionSchema,
  'sendUnsignedTransactionToFork(uint256,uint256,uint256,address,uint256,bytes)': sendUnsignedTransactionToForkSchema,
  'sendWithdrawEthToFork(uint256,uint256,uint256,uint256,address)': sendWithdrawEthToForkSchema,
  'sequencerInbox()': sequencerInboxSchema,
  'setAllowList(address[],bool[])': setAllowListSchema,
  'setAllowListEnabled(bool)': setAllowListEnabledSchema,
  'unpause()': unpauseSchema,
  'unsafeCreateRetryableTicket(address,uint256,uint256,address,address,uint256,uint256,bytes)': unsafeCreateRetryableTicketSchema,
} as const;
