// Generated by abi-to-zod v0.0.0 from NodeInterface.json
// Do not edit manually -- regenerate from source.

import { z } from 'zod';

// === Primitive schemas (edit once to customise all uses) ===

const ADDRESS = z.string().regex(/^0x[0-9a-fA-F]{40}$/).transform((v) => v as `0x${string}`);
const BOOL = z.boolean();
const BYTES = z.string().regex(/^0x([0-9a-fA-F]{2})*$/).transform((v) => v as `0x${string}`);
const BYTES32 = z.string().regex(/^0x[0-9a-fA-F]{64}$/).transform((v) => v as `0x${string}`);
const UINT256 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 256n) - 1n);
const UINT64 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 64n) - 1n);

// === Function schemas ===

// blockL1Num(uint64)
export const blockL1NumSchema = z.tuple([
  /* l2BlockNum: uint64 */ UINT64,
]);

// constructOutboxProof(uint64,uint64)
export const constructOutboxProofSchema = z.tuple([
  /* size: uint64 */ UINT64,
  /* leaf: uint64 */ UINT64,
]);

// estimateRetryableTicket(address,uint256,address,uint256,address,address,bytes)
export const estimateRetryableTicketSchema = z.tuple([
  /* sender: address */ ADDRESS,
  /* deposit: uint256 */ UINT256,
  /* to: address */ ADDRESS,
  /* l2CallValue: uint256 */ UINT256,
  /* excessFeeRefundAddress: address */ ADDRESS,
  /* callValueRefundAddress: address */ ADDRESS,
  /* data: bytes */ BYTES,
]);

// findBatchContainingBlock(uint64)
export const findBatchContainingBlockSchema = z.tuple([
  /* blockNum: uint64 */ UINT64,
]);

// gasEstimateComponents(address,bool,bytes)
export const gasEstimateComponentsSchema = z.tuple([
  /* to: address */ ADDRESS,
  /* contractCreation: bool */ BOOL,
  /* data: bytes */ BYTES,
]);

// gasEstimateL1Component(address,bool,bytes)
export const gasEstimateL1ComponentSchema = z.tuple([
  /* to: address */ ADDRESS,
  /* contractCreation: bool */ BOOL,
  /* data: bytes */ BYTES,
]);

// getL1Confirmations(bytes32)
export const getL1ConfirmationsSchema = z.tuple([
  /* blockHash: bytes32 */ BYTES32,
]);

// l2BlockRangeForL1(uint64)
export const l2BlockRangeForL1Schema = z.tuple([
  /* blockNum: uint64 */ UINT64,
]);

// legacyLookupMessageBatchProof(uint256,uint64)
export const legacyLookupMessageBatchProofSchema = z.tuple([
  /* batchNum: uint256 */ UINT256,
  /* index: uint64 */ UINT64,
]);

// nitroGenesisBlock()
export const nitroGenesisBlockSchema = z.tuple([]);

// === Lookup barrel (mirrors abiToZod) ===

export const schemas = {
  blockL1Num: blockL1NumSchema,
  constructOutboxProof: constructOutboxProofSchema,
  estimateRetryableTicket: estimateRetryableTicketSchema,
  findBatchContainingBlock: findBatchContainingBlockSchema,
  gasEstimateComponents: gasEstimateComponentsSchema,
  gasEstimateL1Component: gasEstimateL1ComponentSchema,
  getL1Confirmations: getL1ConfirmationsSchema,
  l2BlockRangeForL1: l2BlockRangeForL1Schema,
  legacyLookupMessageBatchProof: legacyLookupMessageBatchProofSchema,
  nitroGenesisBlock: nitroGenesisBlockSchema,
  'blockL1Num(uint64)': blockL1NumSchema,
  'constructOutboxProof(uint64,uint64)': constructOutboxProofSchema,
  'estimateRetryableTicket(address,uint256,address,uint256,address,address,bytes)': estimateRetryableTicketSchema,
  'findBatchContainingBlock(uint64)': findBatchContainingBlockSchema,
  'gasEstimateComponents(address,bool,bytes)': gasEstimateComponentsSchema,
  'gasEstimateL1Component(address,bool,bytes)': gasEstimateL1ComponentSchema,
  'getL1Confirmations(bytes32)': getL1ConfirmationsSchema,
  'l2BlockRangeForL1(uint64)': l2BlockRangeForL1Schema,
  'legacyLookupMessageBatchProof(uint256,uint64)': legacyLookupMessageBatchProofSchema,
  'nitroGenesisBlock()': nitroGenesisBlockSchema,
} as const;
