// Generated by abi-to-zod v0.0.0 from Outbox.json
// Do not edit manually -- regenerate from source.

import { z } from 'zod';

// === Primitive schemas (edit once to customise all uses) ===

const ADDRESS = z.string().regex(/^0x[0-9a-fA-F]{40}$/).transform((v) => v as `0x${string}`);
const BYTES = z.string().regex(/^0x([0-9a-fA-F]{2})*$/).transform((v) => v as `0x${string}`);
const BYTES32 = z.string().regex(/^0x[0-9a-fA-F]{64}$/).transform((v) => v as `0x${string}`);
const UINT256 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 256n) - 1n);

// === Function schemas ===

// OUTBOX_VERSION()
export const OUTBOX_VERSIONSchema = z.tuple([]);

// bridge()
export const bridgeSchema = z.tuple([]);

// calculateItemHash(address,address,uint256,uint256,uint256,uint256,bytes)
export const calculateItemHashSchema = z.tuple([
  /* l2Sender: address */ ADDRESS,
  /* to: address */ ADDRESS,
  /* l2Block: uint256 */ UINT256,
  /* l1Block: uint256 */ UINT256,
  /* l2Timestamp: uint256 */ UINT256,
  /* value: uint256 */ UINT256,
  /* data: bytes */ BYTES,
]);

// calculateMerkleRoot(bytes32[],uint256,bytes32)
export const calculateMerkleRootSchema = z.tuple([
  /* proof: bytes32[] */ z.array(BYTES32),
  /* path: uint256 */ UINT256,
  /* item: bytes32 */ BYTES32,
]);

// executeTransaction(bytes32[],uint256,address,address,uint256,uint256,uint256,uint256,bytes)
export const executeTransactionSchema = z.tuple([
  /* proof: bytes32[] */ z.array(BYTES32),
  /* index: uint256 */ UINT256,
  /* l2Sender: address */ ADDRESS,
  /* to: address */ ADDRESS,
  /* l2Block: uint256 */ UINT256,
  /* l1Block: uint256 */ UINT256,
  /* l2Timestamp: uint256 */ UINT256,
  /* value: uint256 */ UINT256,
  /* data: bytes */ BYTES,
]);

// executeTransactionSimulation(uint256,address,address,uint256,uint256,uint256,uint256,bytes)
export const executeTransactionSimulationSchema = z.tuple([
  /* index: uint256 */ UINT256,
  /* l2Sender: address */ ADDRESS,
  /* to: address */ ADDRESS,
  /* l2Block: uint256 */ UINT256,
  /* l1Block: uint256 */ UINT256,
  /* l2Timestamp: uint256 */ UINT256,
  /* value: uint256 */ UINT256,
  /* data: bytes */ BYTES,
]);

// initialize(address)
export const initializeSchema = z.tuple([
  /* _bridge: address */ ADDRESS,
]);

// isSpent(uint256)
export const isSpentSchema = z.tuple([
  /* index: uint256 */ UINT256,
]);

// l2ToL1BatchNum()
export const l2ToL1BatchNumSchema = z.tuple([]);

// l2ToL1Block()
export const l2ToL1BlockSchema = z.tuple([]);

// l2ToL1EthBlock()
export const l2ToL1EthBlockSchema = z.tuple([]);

// l2ToL1OutputId()
export const l2ToL1OutputIdSchema = z.tuple([]);

// l2ToL1Sender()
export const l2ToL1SenderSchema = z.tuple([]);

// l2ToL1Timestamp()
export const l2ToL1TimestampSchema = z.tuple([]);

// postUpgradeInit()
export const postUpgradeInitSchema = z.tuple([]);

// rollup()
export const rollupSchema = z.tuple([]);

// roots(bytes32)
export const rootsSchema = z.tuple([
  /* bytes32 */ BYTES32,
]);

// spent(uint256)
export const spentSchema = z.tuple([
  /* uint256 */ UINT256,
]);

// updateRollupAddress()
export const updateRollupAddressSchema = z.tuple([]);

// updateSendRoot(bytes32,bytes32)
export const updateSendRootSchema = z.tuple([
  /* root: bytes32 */ BYTES32,
  /* l2BlockHash: bytes32 */ BYTES32,
]);

// === Lookup barrel (mirrors abiToZod) ===

export const schemas = {
  OUTBOX_VERSION: OUTBOX_VERSIONSchema,
  bridge: bridgeSchema,
  calculateItemHash: calculateItemHashSchema,
  calculateMerkleRoot: calculateMerkleRootSchema,
  executeTransaction: executeTransactionSchema,
  executeTransactionSimulation: executeTransactionSimulationSchema,
  initialize: initializeSchema,
  isSpent: isSpentSchema,
  l2ToL1BatchNum: l2ToL1BatchNumSchema,
  l2ToL1Block: l2ToL1BlockSchema,
  l2ToL1EthBlock: l2ToL1EthBlockSchema,
  l2ToL1OutputId: l2ToL1OutputIdSchema,
  l2ToL1Sender: l2ToL1SenderSchema,
  l2ToL1Timestamp: l2ToL1TimestampSchema,
  postUpgradeInit: postUpgradeInitSchema,
  rollup: rollupSchema,
  roots: rootsSchema,
  spent: spentSchema,
  updateRollupAddress: updateRollupAddressSchema,
  updateSendRoot: updateSendRootSchema,
  'OUTBOX_VERSION()': OUTBOX_VERSIONSchema,
  'bridge()': bridgeSchema,
  'calculateItemHash(address,address,uint256,uint256,uint256,uint256,bytes)': calculateItemHashSchema,
  'calculateMerkleRoot(bytes32[],uint256,bytes32)': calculateMerkleRootSchema,
  'executeTransaction(bytes32[],uint256,address,address,uint256,uint256,uint256,uint256,bytes)': executeTransactionSchema,
  'executeTransactionSimulation(uint256,address,address,uint256,uint256,uint256,uint256,bytes)': executeTransactionSimulationSchema,
  'initialize(address)': initializeSchema,
  'isSpent(uint256)': isSpentSchema,
  'l2ToL1BatchNum()': l2ToL1BatchNumSchema,
  'l2ToL1Block()': l2ToL1BlockSchema,
  'l2ToL1EthBlock()': l2ToL1EthBlockSchema,
  'l2ToL1OutputId()': l2ToL1OutputIdSchema,
  'l2ToL1Sender()': l2ToL1SenderSchema,
  'l2ToL1Timestamp()': l2ToL1TimestampSchema,
  'postUpgradeInit()': postUpgradeInitSchema,
  'rollup()': rollupSchema,
  'roots(bytes32)': rootsSchema,
  'spent(uint256)': spentSchema,
  'updateRollupAddress()': updateRollupAddressSchema,
  'updateSendRoot(bytes32,bytes32)': updateSendRootSchema,
} as const;
