// Generated by abi-to-zod v0.0.0 from RollupAdminLogic.json
// Do not edit manually -- regenerate from source.

import { z } from 'zod';

// === Primitive schemas (edit once to customise all uses) ===

const ADDRESS = z.string().regex(/^0x[0-9a-fA-F]{40}$/).transform((v) => v as `0x${string}`);
const BOOL = z.boolean();
const BYTES = z.string().regex(/^0x([0-9a-fA-F]{2})*$/).transform((v) => v as `0x${string}`);
const BYTES32 = z.string().regex(/^0x[0-9a-fA-F]{64}$/).transform((v) => v as `0x${string}`);
const STRING = z.string();
const UINT256 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 256n) - 1n);
const UINT64 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 64n) - 1n);
const UINT8 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 8n) - 1n);

// === Function schemas ===

// _stakerMap(address)
export const _stakerMapSchema = z.tuple([
  /* address */ ADDRESS,
]);

// amountStaked(address)
export const amountStakedSchema = z.tuple([
  /* staker: address */ ADDRESS,
]);

// anyTrustFastConfirmer()
export const anyTrustFastConfirmerSchema = z.tuple([]);

// baseStake()
export const baseStakeSchema = z.tuple([]);

// bridge()
export const bridgeSchema = z.tuple([]);

// chainId()
export const chainIdSchema = z.tuple([]);

// challengeGracePeriodBlocks()
export const challengeGracePeriodBlocksSchema = z.tuple([]);

// challengeManager()
export const challengeManagerSchema = z.tuple([]);

// confirmPeriodBlocks()
export const confirmPeriodBlocksSchema = z.tuple([]);

// decreaseBaseStake(uint256,uint64)
export const decreaseBaseStakeSchema = z.tuple([
  /* newBaseStake: uint256 */ UINT256,
  /* latestNextInboxPosition: uint64 */ UINT64,
]);

// forceConfirmAssertion(bytes32,bytes32,((bytes32[2],uint64[2]),uint8,bytes32),bytes32)
export const forceConfirmAssertionSchema = z.tuple([
  /* assertionHash: bytes32 */ BYTES32,
  /* parentAssertionHash: bytes32 */ BYTES32,
  /* confirmState: ((bytes32[2],uint64[2]),uint8,bytes32) */ z.tuple([
    /* globalState: (bytes32[2],uint64[2]) */ z.tuple([
      /* bytes32Vals: bytes32[2] */ z.array(BYTES32).length(2),
      /* u64Vals: uint64[2] */ z.array(UINT64).length(2),
    ]),
    /* machineStatus: uint8 */ UINT8,
    /* endHistoryRoot: bytes32 */ BYTES32,
  ]),
  /* inboxAcc: bytes32 */ BYTES32,
]);

// forceCreateAssertion(bytes32,((bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)),((bytes32[2],uint64[2]),uint8,bytes32),((bytes32[2],uint64[2]),uint8,bytes32)),bytes32)
export const forceCreateAssertionSchema = z.tuple([
  /* prevAssertionHash: bytes32 */ BYTES32,
  /* assertion: ((bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)),((bytes32[2],uint64[2]),uint8,bytes32),((bytes32[2],uint64[2]),uint8,bytes32)) */ z.tuple([
    /* beforeStateData: (bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)) */ z.tuple([
      /* prevPrevAssertionHash: bytes32 */ BYTES32,
      /* sequencerBatchAcc: bytes32 */ BYTES32,
      /* configData: (bytes32,uint256,address,uint64,uint64) */ z.tuple([
        /* wasmModuleRoot: bytes32 */ BYTES32,
        /* requiredStake: uint256 */ UINT256,
        /* challengeManager: address */ ADDRESS,
        /* confirmPeriodBlocks: uint64 */ UINT64,
        /* nextInboxPosition: uint64 */ UINT64,
      ]),
    ]),
    /* beforeState: ((bytes32[2],uint64[2]),uint8,bytes32) */ z.tuple([
      /* globalState: (bytes32[2],uint64[2]) */ z.tuple([
        /* bytes32Vals: bytes32[2] */ z.array(BYTES32).length(2),
        /* u64Vals: uint64[2] */ z.array(UINT64).length(2),
      ]),
      /* machineStatus: uint8 */ UINT8,
      /* endHistoryRoot: bytes32 */ BYTES32,
    ]),
    /* afterState: ((bytes32[2],uint64[2]),uint8,bytes32) */ z.tuple([
      /* globalState: (bytes32[2],uint64[2]) */ z.tuple([
        /* bytes32Vals: bytes32[2] */ z.array(BYTES32).length(2),
        /* u64Vals: uint64[2] */ z.array(UINT64).length(2),
      ]),
      /* machineStatus: uint8 */ UINT8,
      /* endHistoryRoot: bytes32 */ BYTES32,
    ]),
  ]),
  /* expectedAssertionHash: bytes32 */ BYTES32,
]);

// forceRefundStaker(address[])
export const forceRefundStakerSchema = z.tuple([
  /* staker: address[] */ z.array(ADDRESS),
]);

// genesisAssertionHash()
export const genesisAssertionHashSchema = z.tuple([]);

// getAssertion(bytes32)
export const getAssertionSchema = z.tuple([
  /* assertionHash: bytes32 */ BYTES32,
]);

// getAssertionCreationBlockForLogLookup(bytes32)
export const getAssertionCreationBlockForLogLookupSchema = z.tuple([
  /* assertionHash: bytes32 */ BYTES32,
]);

// getFirstChildCreationBlock(bytes32)
export const getFirstChildCreationBlockSchema = z.tuple([
  /* assertionHash: bytes32 */ BYTES32,
]);

// getSecondChildCreationBlock(bytes32)
export const getSecondChildCreationBlockSchema = z.tuple([
  /* assertionHash: bytes32 */ BYTES32,
]);

// getStaker(address)
export const getStakerSchema = z.tuple([
  /* staker: address */ ADDRESS,
]);

// getStakerAddress(uint64)
export const getStakerAddressSchema = z.tuple([
  /* stakerNum: uint64 */ UINT64,
]);

// getValidators()
export const getValidatorsSchema = z.tuple([]);

// inbox()
export const inboxSchema = z.tuple([]);

// increaseBaseStake(uint256)
export const increaseBaseStakeSchema = z.tuple([
  /* newBaseStake: uint256 */ UINT256,
]);

// initialize((uint64,address,uint256,bytes32,address,address,uint256,string,uint256,uint64,uint256[],(uint256,uint256,uint256,uint256),uint256,uint256,uint256,((bytes32[2],uint64[2]),uint8,bytes32),uint256,address,uint8,uint64,(uint64,uint64,uint64),uint256),(address,address,address,address,address,address,address,address,address))
export const initializeSchema = z.tuple([
  /* config: (uint64,address,uint256,bytes32,address,address,uint256,string,uint256,uint64,uint256[],(uint256,uint256,uint256,uint256),uint256,uint256,uint256,((bytes32[2],uint64[2]),uint8,bytes32),uint256,address,uint8,uint64,(uint64,uint64,uint64),uint256) */ z.tuple([
    /* confirmPeriodBlocks: uint64 */ UINT64,
    /* stakeToken: address */ ADDRESS,
    /* baseStake: uint256 */ UINT256,
    /* wasmModuleRoot: bytes32 */ BYTES32,
    /* owner: address */ ADDRESS,
    /* loserStakeEscrow: address */ ADDRESS,
    /* chainId: uint256 */ UINT256,
    /* chainConfig: string */ STRING,
    /* minimumAssertionPeriod: uint256 */ UINT256,
    /* validatorAfkBlocks: uint64 */ UINT64,
    /* miniStakeValues: uint256[] */ z.array(UINT256),
    /* sequencerInboxMaxTimeVariation: (uint256,uint256,uint256,uint256) */ z.tuple([
      /* delayBlocks: uint256 */ UINT256,
      /* futureBlocks: uint256 */ UINT256,
      /* delaySeconds: uint256 */ UINT256,
      /* futureSeconds: uint256 */ UINT256,
    ]),
    /* layerZeroBlockEdgeHeight: uint256 */ UINT256,
    /* layerZeroBigStepEdgeHeight: uint256 */ UINT256,
    /* layerZeroSmallStepEdgeHeight: uint256 */ UINT256,
    /* genesisAssertionState: ((bytes32[2],uint64[2]),uint8,bytes32) */ z.tuple([
      /* globalState: (bytes32[2],uint64[2]) */ z.tuple([
        /* bytes32Vals: bytes32[2] */ z.array(BYTES32).length(2),
        /* u64Vals: uint64[2] */ z.array(UINT64).length(2),
      ]),
      /* machineStatus: uint8 */ UINT8,
      /* endHistoryRoot: bytes32 */ BYTES32,
    ]),
    /* genesisInboxCount: uint256 */ UINT256,
    /* anyTrustFastConfirmer: address */ ADDRESS,
    /* numBigStepLevel: uint8 */ UINT8,
    /* challengeGracePeriodBlocks: uint64 */ UINT64,
    /* bufferConfig: (uint64,uint64,uint64) */ z.tuple([
      /* threshold: uint64 */ UINT64,
      /* max: uint64 */ UINT64,
      /* replenishRateInBasis: uint64 */ UINT64,
    ]),
    /* dataCostEstimate: uint256 */ UINT256,
  ]),
  /* connectedContracts: (address,address,address,address,address,address,address,address,address) */ z.tuple([
    /* bridge: address */ ADDRESS,
    /* sequencerInbox: address */ ADDRESS,
    /* inbox: address */ ADDRESS,
    /* outbox: address */ ADDRESS,
    /* rollupEventInbox: address */ ADDRESS,
    /* challengeManager: address */ ADDRESS,
    /* rollupAdminLogic: address */ ADDRESS,
    /* rollupUserLogic: address */ ADDRESS,
    /* validatorWalletCreator: address */ ADDRESS,
  ]),
]);

// isFirstChild(bytes32)
export const isFirstChildSchema = z.tuple([
  /* assertionHash: bytes32 */ BYTES32,
]);

// isPending(bytes32)
export const isPendingSchema = z.tuple([
  /* assertionHash: bytes32 */ BYTES32,
]);

// isStaked(address)
export const isStakedSchema = z.tuple([
  /* staker: address */ ADDRESS,
]);

// isValidator(address)
export const isValidatorSchema = z.tuple([
  /* validator: address */ ADDRESS,
]);

// latestConfirmed()
export const latestConfirmedSchema = z.tuple([]);

// latestStakedAssertion(address)
export const latestStakedAssertionSchema = z.tuple([
  /* staker: address */ ADDRESS,
]);

// loserStakeEscrow()
export const loserStakeEscrowSchema = z.tuple([]);

// minimumAssertionPeriod()
export const minimumAssertionPeriodSchema = z.tuple([]);

// outbox()
export const outboxSchema = z.tuple([]);

// pause()
export const pauseSchema = z.tuple([]);

// paused()
export const pausedSchema = z.tuple([]);

// proxiableUUID()
export const proxiableUUIDSchema = z.tuple([]);

// removeOldOutbox(address)
export const removeOldOutboxSchema = z.tuple([
  /* _outbox: address */ ADDRESS,
]);

// resume()
export const resumeSchema = z.tuple([]);

// rollupDeploymentBlock()
export const rollupDeploymentBlockSchema = z.tuple([]);

// rollupEventInbox()
export const rollupEventInboxSchema = z.tuple([]);

// sequencerInbox()
export const sequencerInboxSchema = z.tuple([]);

// setAnyTrustFastConfirmer(address)
export const setAnyTrustFastConfirmerSchema = z.tuple([
  /* _anyTrustFastConfirmer: address */ ADDRESS,
]);

// setChallengeManager(address)
export const setChallengeManagerSchema = z.tuple([
  /* _challengeManager: address */ ADDRESS,
]);

// setConfirmPeriodBlocks(uint64)
export const setConfirmPeriodBlocksSchema = z.tuple([
  /* newConfirmPeriod: uint64 */ UINT64,
]);

// setDelayedInbox(address,bool)
export const setDelayedInboxSchema = z.tuple([
  /* _inbox: address */ ADDRESS,
  /* _enabled: bool */ BOOL,
]);

// setInbox(address)
export const setInboxSchema = z.tuple([
  /* newInbox: address */ ADDRESS,
]);

// setLoserStakeEscrow(address)
export const setLoserStakeEscrowSchema = z.tuple([
  /* newLoserStakerEscrow: address */ ADDRESS,
]);

// setMinimumAssertionPeriod(uint256)
export const setMinimumAssertionPeriodSchema = z.tuple([
  /* newPeriod: uint256 */ UINT256,
]);

// setOutbox(address)
export const setOutboxSchema = z.tuple([
  /* _outbox: address */ ADDRESS,
]);

// setOwner(address)
export const setOwnerSchema = z.tuple([
  /* newOwner: address */ ADDRESS,
]);

// setSequencerInbox(address)
export const setSequencerInboxSchema = z.tuple([
  /* _sequencerInbox: address */ ADDRESS,
]);

// setValidator(address[],bool[])
export const setValidatorSchema = z.tuple([
  /* _validator: address[] */ z.array(ADDRESS),
  /* _val: bool[] */ z.array(BOOL),
]);

// setValidatorAfkBlocks(uint64)
export const setValidatorAfkBlocksSchema = z.tuple([
  /* newAfkBlocks: uint64 */ UINT64,
]);

// setValidatorWhitelistDisabled(bool)
export const setValidatorWhitelistDisabledSchema = z.tuple([
  /* _validatorWhitelistDisabled: bool */ BOOL,
]);

// setWasmModuleRoot(bytes32)
export const setWasmModuleRootSchema = z.tuple([
  /* newWasmModuleRoot: bytes32 */ BYTES32,
]);

// stakeToken()
export const stakeTokenSchema = z.tuple([]);

// stakerCount()
export const stakerCountSchema = z.tuple([]);

// totalWithdrawableFunds()
export const totalWithdrawableFundsSchema = z.tuple([]);

// upgradeSecondaryTo(address)
export const upgradeSecondaryToSchema = z.tuple([
  /* newImplementation: address */ ADDRESS,
]);

// upgradeSecondaryToAndCall(address,bytes)
export const upgradeSecondaryToAndCallSchema = z.tuple([
  /* newImplementation: address */ ADDRESS,
  /* data: bytes */ BYTES,
]);

// upgradeTo(address)
export const upgradeToSchema = z.tuple([
  /* newImplementation: address */ ADDRESS,
]);

// upgradeToAndCall(address,bytes)
export const upgradeToAndCallSchema = z.tuple([
  /* newImplementation: address */ ADDRESS,
  /* data: bytes */ BYTES,
]);

// validateAssertionHash(bytes32,((bytes32[2],uint64[2]),uint8,bytes32),bytes32,bytes32)
export const validateAssertionHashSchema = z.tuple([
  /* assertionHash: bytes32 */ BYTES32,
  /* state: ((bytes32[2],uint64[2]),uint8,bytes32) */ z.tuple([
    /* globalState: (bytes32[2],uint64[2]) */ z.tuple([
      /* bytes32Vals: bytes32[2] */ z.array(BYTES32).length(2),
      /* u64Vals: uint64[2] */ z.array(UINT64).length(2),
    ]),
    /* machineStatus: uint8 */ UINT8,
    /* endHistoryRoot: bytes32 */ BYTES32,
  ]),
  /* prevAssertionHash: bytes32 */ BYTES32,
  /* inboxAcc: bytes32 */ BYTES32,
]);

// validateConfig(bytes32,(bytes32,uint256,address,uint64,uint64))
export const validateConfigSchema = z.tuple([
  /* assertionHash: bytes32 */ BYTES32,
  /* configData: (bytes32,uint256,address,uint64,uint64) */ z.tuple([
    /* wasmModuleRoot: bytes32 */ BYTES32,
    /* requiredStake: uint256 */ UINT256,
    /* challengeManager: address */ ADDRESS,
    /* confirmPeriodBlocks: uint64 */ UINT64,
    /* nextInboxPosition: uint64 */ UINT64,
  ]),
]);

// validatorAfkBlocks()
export const validatorAfkBlocksSchema = z.tuple([]);

// validatorWalletCreator()
export const validatorWalletCreatorSchema = z.tuple([]);

// validatorWhitelistDisabled()
export const validatorWhitelistDisabledSchema = z.tuple([]);

// wasmModuleRoot()
export const wasmModuleRootSchema = z.tuple([]);

// withdrawableFunds(address)
export const withdrawableFundsSchema = z.tuple([
  /* user: address */ ADDRESS,
]);

// withdrawalAddress(address)
export const withdrawalAddressSchema = z.tuple([
  /* staker: address */ ADDRESS,
]);

// === Lookup barrel (mirrors abiToZod) ===

export const schemas = {
  _stakerMap: _stakerMapSchema,
  amountStaked: amountStakedSchema,
  anyTrustFastConfirmer: anyTrustFastConfirmerSchema,
  baseStake: baseStakeSchema,
  bridge: bridgeSchema,
  chainId: chainIdSchema,
  challengeGracePeriodBlocks: challengeGracePeriodBlocksSchema,
  challengeManager: challengeManagerSchema,
  confirmPeriodBlocks: confirmPeriodBlocksSchema,
  decreaseBaseStake: decreaseBaseStakeSchema,
  forceConfirmAssertion: forceConfirmAssertionSchema,
  forceCreateAssertion: forceCreateAssertionSchema,
  forceRefundStaker: forceRefundStakerSchema,
  genesisAssertionHash: genesisAssertionHashSchema,
  getAssertion: getAssertionSchema,
  getAssertionCreationBlockForLogLookup: getAssertionCreationBlockForLogLookupSchema,
  getFirstChildCreationBlock: getFirstChildCreationBlockSchema,
  getSecondChildCreationBlock: getSecondChildCreationBlockSchema,
  getStaker: getStakerSchema,
  getStakerAddress: getStakerAddressSchema,
  getValidators: getValidatorsSchema,
  inbox: inboxSchema,
  increaseBaseStake: increaseBaseStakeSchema,
  initialize: initializeSchema,
  isFirstChild: isFirstChildSchema,
  isPending: isPendingSchema,
  isStaked: isStakedSchema,
  isValidator: isValidatorSchema,
  latestConfirmed: latestConfirmedSchema,
  latestStakedAssertion: latestStakedAssertionSchema,
  loserStakeEscrow: loserStakeEscrowSchema,
  minimumAssertionPeriod: minimumAssertionPeriodSchema,
  outbox: outboxSchema,
  pause: pauseSchema,
  paused: pausedSchema,
  proxiableUUID: proxiableUUIDSchema,
  removeOldOutbox: removeOldOutboxSchema,
  resume: resumeSchema,
  rollupDeploymentBlock: rollupDeploymentBlockSchema,
  rollupEventInbox: rollupEventInboxSchema,
  sequencerInbox: sequencerInboxSchema,
  setAnyTrustFastConfirmer: setAnyTrustFastConfirmerSchema,
  setChallengeManager: setChallengeManagerSchema,
  setConfirmPeriodBlocks: setConfirmPeriodBlocksSchema,
  setDelayedInbox: setDelayedInboxSchema,
  setInbox: setInboxSchema,
  setLoserStakeEscrow: setLoserStakeEscrowSchema,
  setMinimumAssertionPeriod: setMinimumAssertionPeriodSchema,
  setOutbox: setOutboxSchema,
  setOwner: setOwnerSchema,
  setSequencerInbox: setSequencerInboxSchema,
  setValidator: setValidatorSchema,
  setValidatorAfkBlocks: setValidatorAfkBlocksSchema,
  setValidatorWhitelistDisabled: setValidatorWhitelistDisabledSchema,
  setWasmModuleRoot: setWasmModuleRootSchema,
  stakeToken: stakeTokenSchema,
  stakerCount: stakerCountSchema,
  totalWithdrawableFunds: totalWithdrawableFundsSchema,
  upgradeSecondaryTo: upgradeSecondaryToSchema,
  upgradeSecondaryToAndCall: upgradeSecondaryToAndCallSchema,
  upgradeTo: upgradeToSchema,
  upgradeToAndCall: upgradeToAndCallSchema,
  validateAssertionHash: validateAssertionHashSchema,
  validateConfig: validateConfigSchema,
  validatorAfkBlocks: validatorAfkBlocksSchema,
  validatorWalletCreator: validatorWalletCreatorSchema,
  validatorWhitelistDisabled: validatorWhitelistDisabledSchema,
  wasmModuleRoot: wasmModuleRootSchema,
  withdrawableFunds: withdrawableFundsSchema,
  withdrawalAddress: withdrawalAddressSchema,
  '_stakerMap(address)': _stakerMapSchema,
  'amountStaked(address)': amountStakedSchema,
  'anyTrustFastConfirmer()': anyTrustFastConfirmerSchema,
  'baseStake()': baseStakeSchema,
  'bridge()': bridgeSchema,
  'chainId()': chainIdSchema,
  'challengeGracePeriodBlocks()': challengeGracePeriodBlocksSchema,
  'challengeManager()': challengeManagerSchema,
  'confirmPeriodBlocks()': confirmPeriodBlocksSchema,
  'decreaseBaseStake(uint256,uint64)': decreaseBaseStakeSchema,
  'forceConfirmAssertion(bytes32,bytes32,((bytes32[2],uint64[2]),uint8,bytes32),bytes32)': forceConfirmAssertionSchema,
  'forceCreateAssertion(bytes32,((bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)),((bytes32[2],uint64[2]),uint8,bytes32),((bytes32[2],uint64[2]),uint8,bytes32)),bytes32)': forceCreateAssertionSchema,
  'forceRefundStaker(address[])': forceRefundStakerSchema,
  'genesisAssertionHash()': genesisAssertionHashSchema,
  'getAssertion(bytes32)': getAssertionSchema,
  'getAssertionCreationBlockForLogLookup(bytes32)': getAssertionCreationBlockForLogLookupSchema,
  'getFirstChildCreationBlock(bytes32)': getFirstChildCreationBlockSchema,
  'getSecondChildCreationBlock(bytes32)': getSecondChildCreationBlockSchema,
  'getStaker(address)': getStakerSchema,
  'getStakerAddress(uint64)': getStakerAddressSchema,
  'getValidators()': getValidatorsSchema,
  'inbox()': inboxSchema,
  'increaseBaseStake(uint256)': increaseBaseStakeSchema,
  'initialize((uint64,address,uint256,bytes32,address,address,uint256,string,uint256,uint64,uint256[],(uint256,uint256,uint256,uint256),uint256,uint256,uint256,((bytes32[2],uint64[2]),uint8,bytes32),uint256,address,uint8,uint64,(uint64,uint64,uint64),uint256),(address,address,address,address,address,address,address,address,address))': initializeSchema,
  'isFirstChild(bytes32)': isFirstChildSchema,
  'isPending(bytes32)': isPendingSchema,
  'isStaked(address)': isStakedSchema,
  'isValidator(address)': isValidatorSchema,
  'latestConfirmed()': latestConfirmedSchema,
  'latestStakedAssertion(address)': latestStakedAssertionSchema,
  'loserStakeEscrow()': loserStakeEscrowSchema,
  'minimumAssertionPeriod()': minimumAssertionPeriodSchema,
  'outbox()': outboxSchema,
  'pause()': pauseSchema,
  'paused()': pausedSchema,
  'proxiableUUID()': proxiableUUIDSchema,
  'removeOldOutbox(address)': removeOldOutboxSchema,
  'resume()': resumeSchema,
  'rollupDeploymentBlock()': rollupDeploymentBlockSchema,
  'rollupEventInbox()': rollupEventInboxSchema,
  'sequencerInbox()': sequencerInboxSchema,
  'setAnyTrustFastConfirmer(address)': setAnyTrustFastConfirmerSchema,
  'setChallengeManager(address)': setChallengeManagerSchema,
  'setConfirmPeriodBlocks(uint64)': setConfirmPeriodBlocksSchema,
  'setDelayedInbox(address,bool)': setDelayedInboxSchema,
  'setInbox(address)': setInboxSchema,
  'setLoserStakeEscrow(address)': setLoserStakeEscrowSchema,
  'setMinimumAssertionPeriod(uint256)': setMinimumAssertionPeriodSchema,
  'setOutbox(address)': setOutboxSchema,
  'setOwner(address)': setOwnerSchema,
  'setSequencerInbox(address)': setSequencerInboxSchema,
  'setValidator(address[],bool[])': setValidatorSchema,
  'setValidatorAfkBlocks(uint64)': setValidatorAfkBlocksSchema,
  'setValidatorWhitelistDisabled(bool)': setValidatorWhitelistDisabledSchema,
  'setWasmModuleRoot(bytes32)': setWasmModuleRootSchema,
  'stakeToken()': stakeTokenSchema,
  'stakerCount()': stakerCountSchema,
  'totalWithdrawableFunds()': totalWithdrawableFundsSchema,
  'upgradeSecondaryTo(address)': upgradeSecondaryToSchema,
  'upgradeSecondaryToAndCall(address,bytes)': upgradeSecondaryToAndCallSchema,
  'upgradeTo(address)': upgradeToSchema,
  'upgradeToAndCall(address,bytes)': upgradeToAndCallSchema,
  'validateAssertionHash(bytes32,((bytes32[2],uint64[2]),uint8,bytes32),bytes32,bytes32)': validateAssertionHashSchema,
  'validateConfig(bytes32,(bytes32,uint256,address,uint64,uint64))': validateConfigSchema,
  'validatorAfkBlocks()': validatorAfkBlocksSchema,
  'validatorWalletCreator()': validatorWalletCreatorSchema,
  'validatorWhitelistDisabled()': validatorWhitelistDisabledSchema,
  'wasmModuleRoot()': wasmModuleRootSchema,
  'withdrawableFunds(address)': withdrawableFundsSchema,
  'withdrawalAddress(address)': withdrawalAddressSchema,
} as const;
