// Generated by abi-to-zod v0.0.0 from RollupUserLogic.json
// Do not edit manually -- regenerate from source.

import { z } from 'zod';

// === Primitive schemas (edit once to customise all uses) ===

const ADDRESS = z.string().regex(/^0x[0-9a-fA-F]{40}$/).transform((v) => v as `0x${string}`);
const BYTES32 = z.string().regex(/^0x[0-9a-fA-F]{64}$/).transform((v) => v as `0x${string}`);
const UINT256 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 256n) - 1n);
const UINT64 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 64n) - 1n);
const UINT8 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 8n) - 1n);

// === Function schemas ===

// _stakerMap(address)
export const _stakerMapSchema = z.tuple([
  /* address */ ADDRESS,
]);

// addToDeposit(address,address,uint256)
export const addToDepositSchema = z.tuple([
  /* stakerAddress: address */ ADDRESS,
  /* expectedWithdrawalAddress: address */ ADDRESS,
  /* tokenAmount: uint256 */ UINT256,
]);

// amountStaked(address)
export const amountStakedSchema = z.tuple([
  /* staker: address */ ADDRESS,
]);

// anyTrustFastConfirmer()
export const anyTrustFastConfirmerSchema = z.tuple([]);

// baseStake()
export const baseStakeSchema = z.tuple([]);

// bridge()
export const bridgeSchema = z.tuple([]);

// chainId()
export const chainIdSchema = z.tuple([]);

// challengeGracePeriodBlocks()
export const challengeGracePeriodBlocksSchema = z.tuple([]);

// challengeManager()
export const challengeManagerSchema = z.tuple([]);

// computeAssertionHash(bytes32,((bytes32[2],uint64[2]),uint8,bytes32),bytes32)
export const computeAssertionHashSchema = z.tuple([
  /* prevAssertionHash: bytes32 */ BYTES32,
  /* state: ((bytes32[2],uint64[2]),uint8,bytes32) */ z.tuple([
    /* globalState: (bytes32[2],uint64[2]) */ z.tuple([
      /* bytes32Vals: bytes32[2] */ z.array(BYTES32).length(2),
      /* u64Vals: uint64[2] */ z.array(UINT64).length(2),
    ]),
    /* machineStatus: uint8 */ UINT8,
    /* endHistoryRoot: bytes32 */ BYTES32,
  ]),
  /* inboxAcc: bytes32 */ BYTES32,
]);

// confirmAssertion(bytes32,bytes32,((bytes32[2],uint64[2]),uint8,bytes32),bytes32,(bytes32,uint256,address,uint64,uint64),bytes32)
export const confirmAssertionSchema = z.tuple([
  /* assertionHash: bytes32 */ BYTES32,
  /* prevAssertionHash: bytes32 */ BYTES32,
  /* confirmState: ((bytes32[2],uint64[2]),uint8,bytes32) */ z.tuple([
    /* globalState: (bytes32[2],uint64[2]) */ z.tuple([
      /* bytes32Vals: bytes32[2] */ z.array(BYTES32).length(2),
      /* u64Vals: uint64[2] */ z.array(UINT64).length(2),
    ]),
    /* machineStatus: uint8 */ UINT8,
    /* endHistoryRoot: bytes32 */ BYTES32,
  ]),
  /* winningEdgeId: bytes32 */ BYTES32,
  /* prevConfig: (bytes32,uint256,address,uint64,uint64) */ z.tuple([
    /* wasmModuleRoot: bytes32 */ BYTES32,
    /* requiredStake: uint256 */ UINT256,
    /* challengeManager: address */ ADDRESS,
    /* confirmPeriodBlocks: uint64 */ UINT64,
    /* nextInboxPosition: uint64 */ UINT64,
  ]),
  /* inboxAcc: bytes32 */ BYTES32,
]);

// confirmPeriodBlocks()
export const confirmPeriodBlocksSchema = z.tuple([]);

// fastConfirmAssertion(bytes32,bytes32,((bytes32[2],uint64[2]),uint8,bytes32),bytes32)
export const fastConfirmAssertionSchema = z.tuple([
  /* assertionHash: bytes32 */ BYTES32,
  /* parentAssertionHash: bytes32 */ BYTES32,
  /* confirmState: ((bytes32[2],uint64[2]),uint8,bytes32) */ z.tuple([
    /* globalState: (bytes32[2],uint64[2]) */ z.tuple([
      /* bytes32Vals: bytes32[2] */ z.array(BYTES32).length(2),
      /* u64Vals: uint64[2] */ z.array(UINT64).length(2),
    ]),
    /* machineStatus: uint8 */ UINT8,
    /* endHistoryRoot: bytes32 */ BYTES32,
  ]),
  /* inboxAcc: bytes32 */ BYTES32,
]);

// fastConfirmNewAssertion(((bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)),((bytes32[2],uint64[2]),uint8,bytes32),((bytes32[2],uint64[2]),uint8,bytes32)),bytes32)
export const fastConfirmNewAssertionSchema = z.tuple([
  /* assertion: ((bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)),((bytes32[2],uint64[2]),uint8,bytes32),((bytes32[2],uint64[2]),uint8,bytes32)) */ z.tuple([
    /* beforeStateData: (bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)) */ z.tuple([
      /* prevPrevAssertionHash: bytes32 */ BYTES32,
      /* sequencerBatchAcc: bytes32 */ BYTES32,
      /* configData: (bytes32,uint256,address,uint64,uint64) */ z.tuple([
        /* wasmModuleRoot: bytes32 */ BYTES32,
        /* requiredStake: uint256 */ UINT256,
        /* challengeManager: address */ ADDRESS,
        /* confirmPeriodBlocks: uint64 */ UINT64,
        /* nextInboxPosition: uint64 */ UINT64,
      ]),
    ]),
    /* beforeState: ((bytes32[2],uint64[2]),uint8,bytes32) */ z.tuple([
      /* globalState: (bytes32[2],uint64[2]) */ z.tuple([
        /* bytes32Vals: bytes32[2] */ z.array(BYTES32).length(2),
        /* u64Vals: uint64[2] */ z.array(UINT64).length(2),
      ]),
      /* machineStatus: uint8 */ UINT8,
      /* endHistoryRoot: bytes32 */ BYTES32,
    ]),
    /* afterState: ((bytes32[2],uint64[2]),uint8,bytes32) */ z.tuple([
      /* globalState: (bytes32[2],uint64[2]) */ z.tuple([
        /* bytes32Vals: bytes32[2] */ z.array(BYTES32).length(2),
        /* u64Vals: uint64[2] */ z.array(UINT64).length(2),
      ]),
      /* machineStatus: uint8 */ UINT8,
      /* endHistoryRoot: bytes32 */ BYTES32,
    ]),
  ]),
  /* expectedAssertionHash: bytes32 */ BYTES32,
]);

// genesisAssertionHash()
export const genesisAssertionHashSchema = z.tuple([]);

// getAssertion(bytes32)
export const getAssertionSchema = z.tuple([
  /* assertionHash: bytes32 */ BYTES32,
]);

// getAssertionCreationBlockForLogLookup(bytes32)
export const getAssertionCreationBlockForLogLookupSchema = z.tuple([
  /* assertionHash: bytes32 */ BYTES32,
]);

// getFirstChildCreationBlock(bytes32)
export const getFirstChildCreationBlockSchema = z.tuple([
  /* assertionHash: bytes32 */ BYTES32,
]);

// getSecondChildCreationBlock(bytes32)
export const getSecondChildCreationBlockSchema = z.tuple([
  /* assertionHash: bytes32 */ BYTES32,
]);

// getStaker(address)
export const getStakerSchema = z.tuple([
  /* staker: address */ ADDRESS,
]);

// getStakerAddress(uint64)
export const getStakerAddressSchema = z.tuple([
  /* stakerNum: uint64 */ UINT64,
]);

// getValidators()
export const getValidatorsSchema = z.tuple([]);

// inbox()
export const inboxSchema = z.tuple([]);

// initialize(address)
export const initializeSchema = z.tuple([
  /* _stakeToken: address */ ADDRESS,
]);

// isFirstChild(bytes32)
export const isFirstChildSchema = z.tuple([
  /* assertionHash: bytes32 */ BYTES32,
]);

// isPending(bytes32)
export const isPendingSchema = z.tuple([
  /* assertionHash: bytes32 */ BYTES32,
]);

// isStaked(address)
export const isStakedSchema = z.tuple([
  /* staker: address */ ADDRESS,
]);

// isValidator(address)
export const isValidatorSchema = z.tuple([
  /* validator: address */ ADDRESS,
]);

// latestConfirmed()
export const latestConfirmedSchema = z.tuple([]);

// latestStakedAssertion(address)
export const latestStakedAssertionSchema = z.tuple([
  /* staker: address */ ADDRESS,
]);

// loserStakeEscrow()
export const loserStakeEscrowSchema = z.tuple([]);

// minimumAssertionPeriod()
export const minimumAssertionPeriodSchema = z.tuple([]);

// newStake(uint256,address)
export const newStakeSchema = z.tuple([
  /* tokenAmount: uint256 */ UINT256,
  /* _withdrawalAddress: address */ ADDRESS,
]);

// outbox()
export const outboxSchema = z.tuple([]);

// owner()
export const ownerSchema = z.tuple([]);

// paused()
export const pausedSchema = z.tuple([]);

// proxiableUUID()
export const proxiableUUIDSchema = z.tuple([]);

// reduceDeposit(uint256)
export const reduceDepositSchema = z.tuple([
  /* target: uint256 */ UINT256,
]);

// removeWhitelistAfterFork()
export const removeWhitelistAfterForkSchema = z.tuple([]);

// removeWhitelistAfterValidatorAfk()
export const removeWhitelistAfterValidatorAfkSchema = z.tuple([]);

// returnOldDeposit()
export const returnOldDepositSchema = z.tuple([]);

// returnOldDepositFor(address)
export const returnOldDepositForSchema = z.tuple([
  /* stakerAddress: address */ ADDRESS,
]);

// rollupDeploymentBlock()
export const rollupDeploymentBlockSchema = z.tuple([]);

// rollupEventInbox()
export const rollupEventInboxSchema = z.tuple([]);

// sequencerInbox()
export const sequencerInboxSchema = z.tuple([]);

// stakeOnNewAssertion(((bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)),((bytes32[2],uint64[2]),uint8,bytes32),((bytes32[2],uint64[2]),uint8,bytes32)),bytes32)
export const stakeOnNewAssertionSchema = z.tuple([
  /* assertion: ((bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)),((bytes32[2],uint64[2]),uint8,bytes32),((bytes32[2],uint64[2]),uint8,bytes32)) */ z.tuple([
    /* beforeStateData: (bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)) */ z.tuple([
      /* prevPrevAssertionHash: bytes32 */ BYTES32,
      /* sequencerBatchAcc: bytes32 */ BYTES32,
      /* configData: (bytes32,uint256,address,uint64,uint64) */ z.tuple([
        /* wasmModuleRoot: bytes32 */ BYTES32,
        /* requiredStake: uint256 */ UINT256,
        /* challengeManager: address */ ADDRESS,
        /* confirmPeriodBlocks: uint64 */ UINT64,
        /* nextInboxPosition: uint64 */ UINT64,
      ]),
    ]),
    /* beforeState: ((bytes32[2],uint64[2]),uint8,bytes32) */ z.tuple([
      /* globalState: (bytes32[2],uint64[2]) */ z.tuple([
        /* bytes32Vals: bytes32[2] */ z.array(BYTES32).length(2),
        /* u64Vals: uint64[2] */ z.array(UINT64).length(2),
      ]),
      /* machineStatus: uint8 */ UINT8,
      /* endHistoryRoot: bytes32 */ BYTES32,
    ]),
    /* afterState: ((bytes32[2],uint64[2]),uint8,bytes32) */ z.tuple([
      /* globalState: (bytes32[2],uint64[2]) */ z.tuple([
        /* bytes32Vals: bytes32[2] */ z.array(BYTES32).length(2),
        /* u64Vals: uint64[2] */ z.array(UINT64).length(2),
      ]),
      /* machineStatus: uint8 */ UINT8,
      /* endHistoryRoot: bytes32 */ BYTES32,
    ]),
  ]),
  /* expectedAssertionHash: bytes32 */ BYTES32,
]);

// stakeToken()
export const stakeTokenSchema = z.tuple([]);

// stakerCount()
export const stakerCountSchema = z.tuple([]);

// totalWithdrawableFunds()
export const totalWithdrawableFundsSchema = z.tuple([]);

// validateAssertionHash(bytes32,((bytes32[2],uint64[2]),uint8,bytes32),bytes32,bytes32)
export const validateAssertionHashSchema = z.tuple([
  /* assertionHash: bytes32 */ BYTES32,
  /* state: ((bytes32[2],uint64[2]),uint8,bytes32) */ z.tuple([
    /* globalState: (bytes32[2],uint64[2]) */ z.tuple([
      /* bytes32Vals: bytes32[2] */ z.array(BYTES32).length(2),
      /* u64Vals: uint64[2] */ z.array(UINT64).length(2),
    ]),
    /* machineStatus: uint8 */ UINT8,
    /* endHistoryRoot: bytes32 */ BYTES32,
  ]),
  /* prevAssertionHash: bytes32 */ BYTES32,
  /* inboxAcc: bytes32 */ BYTES32,
]);

// validateConfig(bytes32,(bytes32,uint256,address,uint64,uint64))
export const validateConfigSchema = z.tuple([
  /* assertionHash: bytes32 */ BYTES32,
  /* configData: (bytes32,uint256,address,uint64,uint64) */ z.tuple([
    /* wasmModuleRoot: bytes32 */ BYTES32,
    /* requiredStake: uint256 */ UINT256,
    /* challengeManager: address */ ADDRESS,
    /* confirmPeriodBlocks: uint64 */ UINT64,
    /* nextInboxPosition: uint64 */ UINT64,
  ]),
]);

// validatorAfkBlocks()
export const validatorAfkBlocksSchema = z.tuple([]);

// validatorWalletCreator()
export const validatorWalletCreatorSchema = z.tuple([]);

// validatorWhitelistDisabled()
export const validatorWhitelistDisabledSchema = z.tuple([]);

// wasmModuleRoot()
export const wasmModuleRootSchema = z.tuple([]);

// withdrawStakerFunds()
export const withdrawStakerFundsSchema = z.tuple([]);

// withdrawableFunds(address)
export const withdrawableFundsSchema = z.tuple([
  /* user: address */ ADDRESS,
]);

// withdrawalAddress(address)
export const withdrawalAddressSchema = z.tuple([
  /* staker: address */ ADDRESS,
]);

// === Lookup barrel (mirrors abiToZod) ===

export const schemas = {
  _stakerMap: _stakerMapSchema,
  addToDeposit: addToDepositSchema,
  amountStaked: amountStakedSchema,
  anyTrustFastConfirmer: anyTrustFastConfirmerSchema,
  baseStake: baseStakeSchema,
  bridge: bridgeSchema,
  chainId: chainIdSchema,
  challengeGracePeriodBlocks: challengeGracePeriodBlocksSchema,
  challengeManager: challengeManagerSchema,
  computeAssertionHash: computeAssertionHashSchema,
  confirmAssertion: confirmAssertionSchema,
  confirmPeriodBlocks: confirmPeriodBlocksSchema,
  fastConfirmAssertion: fastConfirmAssertionSchema,
  fastConfirmNewAssertion: fastConfirmNewAssertionSchema,
  genesisAssertionHash: genesisAssertionHashSchema,
  getAssertion: getAssertionSchema,
  getAssertionCreationBlockForLogLookup: getAssertionCreationBlockForLogLookupSchema,
  getFirstChildCreationBlock: getFirstChildCreationBlockSchema,
  getSecondChildCreationBlock: getSecondChildCreationBlockSchema,
  getStaker: getStakerSchema,
  getStakerAddress: getStakerAddressSchema,
  getValidators: getValidatorsSchema,
  inbox: inboxSchema,
  initialize: initializeSchema,
  isFirstChild: isFirstChildSchema,
  isPending: isPendingSchema,
  isStaked: isStakedSchema,
  isValidator: isValidatorSchema,
  latestConfirmed: latestConfirmedSchema,
  latestStakedAssertion: latestStakedAssertionSchema,
  loserStakeEscrow: loserStakeEscrowSchema,
  minimumAssertionPeriod: minimumAssertionPeriodSchema,
  newStake: newStakeSchema,
  outbox: outboxSchema,
  owner: ownerSchema,
  paused: pausedSchema,
  proxiableUUID: proxiableUUIDSchema,
  reduceDeposit: reduceDepositSchema,
  removeWhitelistAfterFork: removeWhitelistAfterForkSchema,
  removeWhitelistAfterValidatorAfk: removeWhitelistAfterValidatorAfkSchema,
  returnOldDeposit: returnOldDepositSchema,
  returnOldDepositFor: returnOldDepositForSchema,
  rollupDeploymentBlock: rollupDeploymentBlockSchema,
  rollupEventInbox: rollupEventInboxSchema,
  sequencerInbox: sequencerInboxSchema,
  stakeOnNewAssertion: stakeOnNewAssertionSchema,
  stakeToken: stakeTokenSchema,
  stakerCount: stakerCountSchema,
  totalWithdrawableFunds: totalWithdrawableFundsSchema,
  validateAssertionHash: validateAssertionHashSchema,
  validateConfig: validateConfigSchema,
  validatorAfkBlocks: validatorAfkBlocksSchema,
  validatorWalletCreator: validatorWalletCreatorSchema,
  validatorWhitelistDisabled: validatorWhitelistDisabledSchema,
  wasmModuleRoot: wasmModuleRootSchema,
  withdrawStakerFunds: withdrawStakerFundsSchema,
  withdrawableFunds: withdrawableFundsSchema,
  withdrawalAddress: withdrawalAddressSchema,
  '_stakerMap(address)': _stakerMapSchema,
  'addToDeposit(address,address,uint256)': addToDepositSchema,
  'amountStaked(address)': amountStakedSchema,
  'anyTrustFastConfirmer()': anyTrustFastConfirmerSchema,
  'baseStake()': baseStakeSchema,
  'bridge()': bridgeSchema,
  'chainId()': chainIdSchema,
  'challengeGracePeriodBlocks()': challengeGracePeriodBlocksSchema,
  'challengeManager()': challengeManagerSchema,
  'computeAssertionHash(bytes32,((bytes32[2],uint64[2]),uint8,bytes32),bytes32)': computeAssertionHashSchema,
  'confirmAssertion(bytes32,bytes32,((bytes32[2],uint64[2]),uint8,bytes32),bytes32,(bytes32,uint256,address,uint64,uint64),bytes32)': confirmAssertionSchema,
  'confirmPeriodBlocks()': confirmPeriodBlocksSchema,
  'fastConfirmAssertion(bytes32,bytes32,((bytes32[2],uint64[2]),uint8,bytes32),bytes32)': fastConfirmAssertionSchema,
  'fastConfirmNewAssertion(((bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)),((bytes32[2],uint64[2]),uint8,bytes32),((bytes32[2],uint64[2]),uint8,bytes32)),bytes32)': fastConfirmNewAssertionSchema,
  'genesisAssertionHash()': genesisAssertionHashSchema,
  'getAssertion(bytes32)': getAssertionSchema,
  'getAssertionCreationBlockForLogLookup(bytes32)': getAssertionCreationBlockForLogLookupSchema,
  'getFirstChildCreationBlock(bytes32)': getFirstChildCreationBlockSchema,
  'getSecondChildCreationBlock(bytes32)': getSecondChildCreationBlockSchema,
  'getStaker(address)': getStakerSchema,
  'getStakerAddress(uint64)': getStakerAddressSchema,
  'getValidators()': getValidatorsSchema,
  'inbox()': inboxSchema,
  'initialize(address)': initializeSchema,
  'isFirstChild(bytes32)': isFirstChildSchema,
  'isPending(bytes32)': isPendingSchema,
  'isStaked(address)': isStakedSchema,
  'isValidator(address)': isValidatorSchema,
  'latestConfirmed()': latestConfirmedSchema,
  'latestStakedAssertion(address)': latestStakedAssertionSchema,
  'loserStakeEscrow()': loserStakeEscrowSchema,
  'minimumAssertionPeriod()': minimumAssertionPeriodSchema,
  'newStake(uint256,address)': newStakeSchema,
  'newStakeOnNewAssertion(uint256,((bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)),((bytes32[2],uint64[2]),uint8,bytes32),((bytes32[2],uint64[2]),uint8,bytes32)),bytes32)': z.tuple([
    /* tokenAmount: uint256 */ UINT256,
    /* assertion: ((bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)),((bytes32[2],uint64[2]),uint8,bytes32),((bytes32[2],uint64[2]),uint8,bytes32)) */ z.tuple([
      /* beforeStateData: (bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)) */ z.tuple([
        /* prevPrevAssertionHash: bytes32 */ BYTES32,
        /* sequencerBatchAcc: bytes32 */ BYTES32,
        /* configData: (bytes32,uint256,address,uint64,uint64) */ z.tuple([
          /* wasmModuleRoot: bytes32 */ BYTES32,
          /* requiredStake: uint256 */ UINT256,
          /* challengeManager: address */ ADDRESS,
          /* confirmPeriodBlocks: uint64 */ UINT64,
          /* nextInboxPosition: uint64 */ UINT64,
        ]),
      ]),
      /* beforeState: ((bytes32[2],uint64[2]),uint8,bytes32) */ z.tuple([
        /* globalState: (bytes32[2],uint64[2]) */ z.tuple([
          /* bytes32Vals: bytes32[2] */ z.array(BYTES32).length(2),
          /* u64Vals: uint64[2] */ z.array(UINT64).length(2),
        ]),
        /* machineStatus: uint8 */ UINT8,
        /* endHistoryRoot: bytes32 */ BYTES32,
      ]),
      /* afterState: ((bytes32[2],uint64[2]),uint8,bytes32) */ z.tuple([
        /* globalState: (bytes32[2],uint64[2]) */ z.tuple([
          /* bytes32Vals: bytes32[2] */ z.array(BYTES32).length(2),
          /* u64Vals: uint64[2] */ z.array(UINT64).length(2),
        ]),
        /* machineStatus: uint8 */ UINT8,
        /* endHistoryRoot: bytes32 */ BYTES32,
      ]),
    ]),
    /* expectedAssertionHash: bytes32 */ BYTES32,
  ]),
  'newStakeOnNewAssertion(uint256,((bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)),((bytes32[2],uint64[2]),uint8,bytes32),((bytes32[2],uint64[2]),uint8,bytes32)),bytes32,address)': z.tuple([
    /* tokenAmount: uint256 */ UINT256,
    /* assertion: ((bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)),((bytes32[2],uint64[2]),uint8,bytes32),((bytes32[2],uint64[2]),uint8,bytes32)) */ z.tuple([
      /* beforeStateData: (bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)) */ z.tuple([
        /* prevPrevAssertionHash: bytes32 */ BYTES32,
        /* sequencerBatchAcc: bytes32 */ BYTES32,
        /* configData: (bytes32,uint256,address,uint64,uint64) */ z.tuple([
          /* wasmModuleRoot: bytes32 */ BYTES32,
          /* requiredStake: uint256 */ UINT256,
          /* challengeManager: address */ ADDRESS,
          /* confirmPeriodBlocks: uint64 */ UINT64,
          /* nextInboxPosition: uint64 */ UINT64,
        ]),
      ]),
      /* beforeState: ((bytes32[2],uint64[2]),uint8,bytes32) */ z.tuple([
        /* globalState: (bytes32[2],uint64[2]) */ z.tuple([
          /* bytes32Vals: bytes32[2] */ z.array(BYTES32).length(2),
          /* u64Vals: uint64[2] */ z.array(UINT64).length(2),
        ]),
        /* machineStatus: uint8 */ UINT8,
        /* endHistoryRoot: bytes32 */ BYTES32,
      ]),
      /* afterState: ((bytes32[2],uint64[2]),uint8,bytes32) */ z.tuple([
        /* globalState: (bytes32[2],uint64[2]) */ z.tuple([
          /* bytes32Vals: bytes32[2] */ z.array(BYTES32).length(2),
          /* u64Vals: uint64[2] */ z.array(UINT64).length(2),
        ]),
        /* machineStatus: uint8 */ UINT8,
        /* endHistoryRoot: bytes32 */ BYTES32,
      ]),
    ]),
    /* expectedAssertionHash: bytes32 */ BYTES32,
    /* _withdrawalAddress: address */ ADDRESS,
  ]),
  'outbox()': outboxSchema,
  'owner()': ownerSchema,
  'paused()': pausedSchema,
  'proxiableUUID()': proxiableUUIDSchema,
  'reduceDeposit(uint256)': reduceDepositSchema,
  'removeWhitelistAfterFork()': removeWhitelistAfterForkSchema,
  'removeWhitelistAfterValidatorAfk()': removeWhitelistAfterValidatorAfkSchema,
  'returnOldDeposit()': returnOldDepositSchema,
  'returnOldDepositFor(address)': returnOldDepositForSchema,
  'rollupDeploymentBlock()': rollupDeploymentBlockSchema,
  'rollupEventInbox()': rollupEventInboxSchema,
  'sequencerInbox()': sequencerInboxSchema,
  'stakeOnNewAssertion(((bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)),((bytes32[2],uint64[2]),uint8,bytes32),((bytes32[2],uint64[2]),uint8,bytes32)),bytes32)': stakeOnNewAssertionSchema,
  'stakeToken()': stakeTokenSchema,
  'stakerCount()': stakerCountSchema,
  'totalWithdrawableFunds()': totalWithdrawableFundsSchema,
  'validateAssertionHash(bytes32,((bytes32[2],uint64[2]),uint8,bytes32),bytes32,bytes32)': validateAssertionHashSchema,
  'validateConfig(bytes32,(bytes32,uint256,address,uint64,uint64))': validateConfigSchema,
  'validatorAfkBlocks()': validatorAfkBlocksSchema,
  'validatorWalletCreator()': validatorWalletCreatorSchema,
  'validatorWhitelistDisabled()': validatorWhitelistDisabledSchema,
  'wasmModuleRoot()': wasmModuleRootSchema,
  'withdrawStakerFunds()': withdrawStakerFundsSchema,
  'withdrawableFunds(address)': withdrawableFundsSchema,
  'withdrawalAddress(address)': withdrawalAddressSchema,
} as const;
