// Generated by abi-to-zod v0.0.0 from SequencerInbox.json
// Do not edit manually -- regenerate from source.

import { z } from 'zod';

// === Primitive schemas (edit once to customise all uses) ===

const ADDRESS = z.string().regex(/^0x[0-9a-fA-F]{40}$/).transform((v) => v as `0x${string}`);
const BOOL = z.boolean();
const BYTES = z.string().regex(/^0x([0-9a-fA-F]{2})*$/).transform((v) => v as `0x${string}`);
const BYTES32 = z.string().regex(/^0x[0-9a-fA-F]{64}$/).transform((v) => v as `0x${string}`);
const UINT256 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 256n) - 1n);
const UINT64 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 64n) - 1n);
const UINT8 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 8n) - 1n);

// === Function schemas ===

// BROTLI_MESSAGE_HEADER_FLAG()
export const BROTLI_MESSAGE_HEADER_FLAGSchema = z.tuple([]);

// CUSTOM_DA_MESSAGE_HEADER_FLAG()
export const CUSTOM_DA_MESSAGE_HEADER_FLAGSchema = z.tuple([]);

// DAS_MESSAGE_HEADER_FLAG()
export const DAS_MESSAGE_HEADER_FLAGSchema = z.tuple([]);

// DATA_AUTHENTICATED_FLAG()
export const DATA_AUTHENTICATED_FLAGSchema = z.tuple([]);

// DATA_BLOB_HEADER_FLAG()
export const DATA_BLOB_HEADER_FLAGSchema = z.tuple([]);

// HEADER_LENGTH()
export const HEADER_LENGTHSchema = z.tuple([]);

// TREE_DAS_MESSAGE_HEADER_FLAG()
export const TREE_DAS_MESSAGE_HEADER_FLAGSchema = z.tuple([]);

// ZERO_HEAVY_MESSAGE_HEADER_FLAG()
export const ZERO_HEAVY_MESSAGE_HEADER_FLAGSchema = z.tuple([]);

// addSequencerL2Batch(uint256,bytes,uint256,address,uint256,uint256)
export const addSequencerL2BatchSchema = z.tuple([
  /* sequenceNumber: uint256 */ UINT256,
  /* data: bytes */ BYTES,
  /* afterDelayedMessagesRead: uint256 */ UINT256,
  /* gasRefunder: address */ ADDRESS,
  /* prevMessageCount: uint256 */ UINT256,
  /* newMessageCount: uint256 */ UINT256,
]);

// addSequencerL2BatchDelayProof(uint256,bytes,uint256,address,uint256,uint256,(bytes32,(uint8,address,uint64,uint64,uint256,uint256,bytes32)))
export const addSequencerL2BatchDelayProofSchema = z.tuple([
  /* sequenceNumber: uint256 */ UINT256,
  /* data: bytes */ BYTES,
  /* afterDelayedMessagesRead: uint256 */ UINT256,
  /* gasRefunder: address */ ADDRESS,
  /* prevMessageCount: uint256 */ UINT256,
  /* newMessageCount: uint256 */ UINT256,
  /* delayProof: (bytes32,(uint8,address,uint64,uint64,uint256,uint256,bytes32)) */ z.tuple([
    /* beforeDelayedAcc: bytes32 */ BYTES32,
    /* delayedMessage: (uint8,address,uint64,uint64,uint256,uint256,bytes32) */ z.tuple([
      /* kind: uint8 */ UINT8,
      /* sender: address */ ADDRESS,
      /* blockNumber: uint64 */ UINT64,
      /* timestamp: uint64 */ UINT64,
      /* inboxSeqNum: uint256 */ UINT256,
      /* baseFeeL1: uint256 */ UINT256,
      /* messageDataHash: bytes32 */ BYTES32,
    ]),
  ]),
]);

// addSequencerL2BatchFromBlobs(uint256,uint256,address,uint256,uint256)
export const addSequencerL2BatchFromBlobsSchema = z.tuple([
  /* sequenceNumber: uint256 */ UINT256,
  /* afterDelayedMessagesRead: uint256 */ UINT256,
  /* gasRefunder: address */ ADDRESS,
  /* prevMessageCount: uint256 */ UINT256,
  /* newMessageCount: uint256 */ UINT256,
]);

// addSequencerL2BatchFromBlobsDelayProof(uint256,uint256,address,uint256,uint256,(bytes32,(uint8,address,uint64,uint64,uint256,uint256,bytes32)))
export const addSequencerL2BatchFromBlobsDelayProofSchema = z.tuple([
  /* sequenceNumber: uint256 */ UINT256,
  /* afterDelayedMessagesRead: uint256 */ UINT256,
  /* gasRefunder: address */ ADDRESS,
  /* prevMessageCount: uint256 */ UINT256,
  /* newMessageCount: uint256 */ UINT256,
  /* delayProof: (bytes32,(uint8,address,uint64,uint64,uint256,uint256,bytes32)) */ z.tuple([
    /* beforeDelayedAcc: bytes32 */ BYTES32,
    /* delayedMessage: (uint8,address,uint64,uint64,uint256,uint256,bytes32) */ z.tuple([
      /* kind: uint8 */ UINT8,
      /* sender: address */ ADDRESS,
      /* blockNumber: uint64 */ UINT64,
      /* timestamp: uint64 */ UINT64,
      /* inboxSeqNum: uint256 */ UINT256,
      /* baseFeeL1: uint256 */ UINT256,
      /* messageDataHash: bytes32 */ BYTES32,
    ]),
  ]),
]);

// addSequencerL2BatchFromOriginDelayProof(uint256,bytes,uint256,address,uint256,uint256,(bytes32,(uint8,address,uint64,uint64,uint256,uint256,bytes32)))
export const addSequencerL2BatchFromOriginDelayProofSchema = z.tuple([
  /* sequenceNumber: uint256 */ UINT256,
  /* data: bytes */ BYTES,
  /* afterDelayedMessagesRead: uint256 */ UINT256,
  /* gasRefunder: address */ ADDRESS,
  /* prevMessageCount: uint256 */ UINT256,
  /* newMessageCount: uint256 */ UINT256,
  /* delayProof: (bytes32,(uint8,address,uint64,uint64,uint256,uint256,bytes32)) */ z.tuple([
    /* beforeDelayedAcc: bytes32 */ BYTES32,
    /* delayedMessage: (uint8,address,uint64,uint64,uint256,uint256,bytes32) */ z.tuple([
      /* kind: uint8 */ UINT8,
      /* sender: address */ ADDRESS,
      /* blockNumber: uint64 */ UINT64,
      /* timestamp: uint64 */ UINT64,
      /* inboxSeqNum: uint256 */ UINT256,
      /* baseFeeL1: uint256 */ UINT256,
      /* messageDataHash: bytes32 */ BYTES32,
    ]),
  ]),
]);

// batchCount()
export const batchCountSchema = z.tuple([]);

// batchPosterManager()
export const batchPosterManagerSchema = z.tuple([]);

// bridge()
export const bridgeSchema = z.tuple([]);

// buffer()
export const bufferSchema = z.tuple([]);

// dasKeySetInfo(bytes32)
export const dasKeySetInfoSchema = z.tuple([
  /* bytes32 */ BYTES32,
]);

// feeTokenPricer()
export const feeTokenPricerSchema = z.tuple([]);

// forceInclusion(uint256,uint8,uint64[2],uint256,address,bytes32)
export const forceInclusionSchema = z.tuple([
  /* _totalDelayedMessagesRead: uint256 */ UINT256,
  /* kind: uint8 */ UINT8,
  /* l1BlockAndTime: uint64[2] */ z.array(UINT64).length(2),
  /* baseFeeL1: uint256 */ UINT256,
  /* sender: address */ ADDRESS,
  /* messageDataHash: bytes32 */ BYTES32,
]);

// forceInclusionDeadline(uint64)
export const forceInclusionDeadlineSchema = z.tuple([
  /* blockNumber: uint64 */ UINT64,
]);

// getKeysetCreationBlock(bytes32)
export const getKeysetCreationBlockSchema = z.tuple([
  /* ksHash: bytes32 */ BYTES32,
]);

// inboxAccs(uint256)
export const inboxAccsSchema = z.tuple([
  /* index: uint256 */ UINT256,
]);

// initialize(address,(uint256,uint256,uint256,uint256),(uint64,uint64,uint64),address)
export const initializeSchema = z.tuple([
  /* bridge_: address */ ADDRESS,
  /* maxTimeVariation_: (uint256,uint256,uint256,uint256) */ z.tuple([
    /* delayBlocks: uint256 */ UINT256,
    /* futureBlocks: uint256 */ UINT256,
    /* delaySeconds: uint256 */ UINT256,
    /* futureSeconds: uint256 */ UINT256,
  ]),
  /* bufferConfig_: (uint64,uint64,uint64) */ z.tuple([
    /* threshold: uint64 */ UINT64,
    /* max: uint64 */ UINT64,
    /* replenishRateInBasis: uint64 */ UINT64,
  ]),
  /* feeTokenPricer_: address */ ADDRESS,
]);

// invalidateKeysetHash(bytes32)
export const invalidateKeysetHashSchema = z.tuple([
  /* ksHash: bytes32 */ BYTES32,
]);

// isBatchPoster(address)
export const isBatchPosterSchema = z.tuple([
  /* address */ ADDRESS,
]);

// isDelayBufferable()
export const isDelayBufferableSchema = z.tuple([]);

// isSequencer(address)
export const isSequencerSchema = z.tuple([
  /* address */ ADDRESS,
]);

// isUsingFeeToken()
export const isUsingFeeTokenSchema = z.tuple([]);

// isValidKeysetHash(bytes32)
export const isValidKeysetHashSchema = z.tuple([
  /* ksHash: bytes32 */ BYTES32,
]);

// maxDataSize()
export const maxDataSizeSchema = z.tuple([]);

// maxTimeVariation()
export const maxTimeVariationSchema = z.tuple([]);

// postUpgradeInit((uint64,uint64,uint64))
export const postUpgradeInitSchema = z.tuple([
  /* bufferConfig_: (uint64,uint64,uint64) */ z.tuple([
    /* threshold: uint64 */ UINT64,
    /* max: uint64 */ UINT64,
    /* replenishRateInBasis: uint64 */ UINT64,
  ]),
]);

// reader4844()
export const reader4844Schema = z.tuple([]);

// removeDelayAfterFork()
export const removeDelayAfterForkSchema = z.tuple([]);

// rollup()
export const rollupSchema = z.tuple([]);

// setBatchPosterManager(address)
export const setBatchPosterManagerSchema = z.tuple([
  /* newBatchPosterManager: address */ ADDRESS,
]);

// setBufferConfig((uint64,uint64,uint64))
export const setBufferConfigSchema = z.tuple([
  /* bufferConfig_: (uint64,uint64,uint64) */ z.tuple([
    /* threshold: uint64 */ UINT64,
    /* max: uint64 */ UINT64,
    /* replenishRateInBasis: uint64 */ UINT64,
  ]),
]);

// setFeeTokenPricer(address)
export const setFeeTokenPricerSchema = z.tuple([
  /* feeTokenPricer_: address */ ADDRESS,
]);

// setIsBatchPoster(address,bool)
export const setIsBatchPosterSchema = z.tuple([
  /* addr: address */ ADDRESS,
  /* isBatchPoster_: bool */ BOOL,
]);

// setIsSequencer(address,bool)
export const setIsSequencerSchema = z.tuple([
  /* addr: address */ ADDRESS,
  /* isSequencer_: bool */ BOOL,
]);

// setMaxTimeVariation((uint256,uint256,uint256,uint256))
export const setMaxTimeVariationSchema = z.tuple([
  /* maxTimeVariation_: (uint256,uint256,uint256,uint256) */ z.tuple([
    /* delayBlocks: uint256 */ UINT256,
    /* futureBlocks: uint256 */ UINT256,
    /* delaySeconds: uint256 */ UINT256,
    /* futureSeconds: uint256 */ UINT256,
  ]),
]);

// setValidKeyset(bytes)
export const setValidKeysetSchema = z.tuple([
  /* keysetBytes: bytes */ BYTES,
]);

// totalDelayedMessagesRead()
export const totalDelayedMessagesReadSchema = z.tuple([]);

// updateRollupAddress()
export const updateRollupAddressSchema = z.tuple([]);

// === Lookup barrel (mirrors abiToZod) ===

export const schemas = {
  BROTLI_MESSAGE_HEADER_FLAG: BROTLI_MESSAGE_HEADER_FLAGSchema,
  CUSTOM_DA_MESSAGE_HEADER_FLAG: CUSTOM_DA_MESSAGE_HEADER_FLAGSchema,
  DAS_MESSAGE_HEADER_FLAG: DAS_MESSAGE_HEADER_FLAGSchema,
  DATA_AUTHENTICATED_FLAG: DATA_AUTHENTICATED_FLAGSchema,
  DATA_BLOB_HEADER_FLAG: DATA_BLOB_HEADER_FLAGSchema,
  HEADER_LENGTH: HEADER_LENGTHSchema,
  TREE_DAS_MESSAGE_HEADER_FLAG: TREE_DAS_MESSAGE_HEADER_FLAGSchema,
  ZERO_HEAVY_MESSAGE_HEADER_FLAG: ZERO_HEAVY_MESSAGE_HEADER_FLAGSchema,
  addSequencerL2Batch: addSequencerL2BatchSchema,
  addSequencerL2BatchDelayProof: addSequencerL2BatchDelayProofSchema,
  addSequencerL2BatchFromBlobs: addSequencerL2BatchFromBlobsSchema,
  addSequencerL2BatchFromBlobsDelayProof: addSequencerL2BatchFromBlobsDelayProofSchema,
  addSequencerL2BatchFromOriginDelayProof: addSequencerL2BatchFromOriginDelayProofSchema,
  batchCount: batchCountSchema,
  batchPosterManager: batchPosterManagerSchema,
  bridge: bridgeSchema,
  buffer: bufferSchema,
  dasKeySetInfo: dasKeySetInfoSchema,
  feeTokenPricer: feeTokenPricerSchema,
  forceInclusion: forceInclusionSchema,
  forceInclusionDeadline: forceInclusionDeadlineSchema,
  getKeysetCreationBlock: getKeysetCreationBlockSchema,
  inboxAccs: inboxAccsSchema,
  initialize: initializeSchema,
  invalidateKeysetHash: invalidateKeysetHashSchema,
  isBatchPoster: isBatchPosterSchema,
  isDelayBufferable: isDelayBufferableSchema,
  isSequencer: isSequencerSchema,
  isUsingFeeToken: isUsingFeeTokenSchema,
  isValidKeysetHash: isValidKeysetHashSchema,
  maxDataSize: maxDataSizeSchema,
  maxTimeVariation: maxTimeVariationSchema,
  postUpgradeInit: postUpgradeInitSchema,
  reader4844: reader4844Schema,
  removeDelayAfterFork: removeDelayAfterForkSchema,
  rollup: rollupSchema,
  setBatchPosterManager: setBatchPosterManagerSchema,
  setBufferConfig: setBufferConfigSchema,
  setFeeTokenPricer: setFeeTokenPricerSchema,
  setIsBatchPoster: setIsBatchPosterSchema,
  setIsSequencer: setIsSequencerSchema,
  setMaxTimeVariation: setMaxTimeVariationSchema,
  setValidKeyset: setValidKeysetSchema,
  totalDelayedMessagesRead: totalDelayedMessagesReadSchema,
  updateRollupAddress: updateRollupAddressSchema,
  'BROTLI_MESSAGE_HEADER_FLAG()': BROTLI_MESSAGE_HEADER_FLAGSchema,
  'CUSTOM_DA_MESSAGE_HEADER_FLAG()': CUSTOM_DA_MESSAGE_HEADER_FLAGSchema,
  'DAS_MESSAGE_HEADER_FLAG()': DAS_MESSAGE_HEADER_FLAGSchema,
  'DATA_AUTHENTICATED_FLAG()': DATA_AUTHENTICATED_FLAGSchema,
  'DATA_BLOB_HEADER_FLAG()': DATA_BLOB_HEADER_FLAGSchema,
  'HEADER_LENGTH()': HEADER_LENGTHSchema,
  'TREE_DAS_MESSAGE_HEADER_FLAG()': TREE_DAS_MESSAGE_HEADER_FLAGSchema,
  'ZERO_HEAVY_MESSAGE_HEADER_FLAG()': ZERO_HEAVY_MESSAGE_HEADER_FLAGSchema,
  'addSequencerL2Batch(uint256,bytes,uint256,address,uint256,uint256)': addSequencerL2BatchSchema,
  'addSequencerL2BatchDelayProof(uint256,bytes,uint256,address,uint256,uint256,(bytes32,(uint8,address,uint64,uint64,uint256,uint256,bytes32)))': addSequencerL2BatchDelayProofSchema,
  'addSequencerL2BatchFromBlobs(uint256,uint256,address,uint256,uint256)': addSequencerL2BatchFromBlobsSchema,
  'addSequencerL2BatchFromBlobsDelayProof(uint256,uint256,address,uint256,uint256,(bytes32,(uint8,address,uint64,uint64,uint256,uint256,bytes32)))': addSequencerL2BatchFromBlobsDelayProofSchema,
  'addSequencerL2BatchFromOrigin(uint256,bytes,uint256,address)': z.tuple([
    /* uint256 */ UINT256,
    /* bytes */ BYTES,
    /* uint256 */ UINT256,
    /* address */ ADDRESS,
  ]),
  'addSequencerL2BatchFromOrigin(uint256,bytes,uint256,address,uint256,uint256)': z.tuple([
    /* sequenceNumber: uint256 */ UINT256,
    /* data: bytes */ BYTES,
    /* afterDelayedMessagesRead: uint256 */ UINT256,
    /* gasRefunder: address */ ADDRESS,
    /* prevMessageCount: uint256 */ UINT256,
    /* newMessageCount: uint256 */ UINT256,
  ]),
  'addSequencerL2BatchFromOriginDelayProof(uint256,bytes,uint256,address,uint256,uint256,(bytes32,(uint8,address,uint64,uint64,uint256,uint256,bytes32)))': addSequencerL2BatchFromOriginDelayProofSchema,
  'batchCount()': batchCountSchema,
  'batchPosterManager()': batchPosterManagerSchema,
  'bridge()': bridgeSchema,
  'buffer()': bufferSchema,
  'dasKeySetInfo(bytes32)': dasKeySetInfoSchema,
  'feeTokenPricer()': feeTokenPricerSchema,
  'forceInclusion(uint256,uint8,uint64[2],uint256,address,bytes32)': forceInclusionSchema,
  'forceInclusionDeadline(uint64)': forceInclusionDeadlineSchema,
  'getKeysetCreationBlock(bytes32)': getKeysetCreationBlockSchema,
  'inboxAccs(uint256)': inboxAccsSchema,
  'initialize(address,(uint256,uint256,uint256,uint256),(uint64,uint64,uint64),address)': initializeSchema,
  'invalidateKeysetHash(bytes32)': invalidateKeysetHashSchema,
  'isBatchPoster(address)': isBatchPosterSchema,
  'isDelayBufferable()': isDelayBufferableSchema,
  'isSequencer(address)': isSequencerSchema,
  'isUsingFeeToken()': isUsingFeeTokenSchema,
  'isValidKeysetHash(bytes32)': isValidKeysetHashSchema,
  'maxDataSize()': maxDataSizeSchema,
  'maxTimeVariation()': maxTimeVariationSchema,
  'postUpgradeInit((uint64,uint64,uint64))': postUpgradeInitSchema,
  'reader4844()': reader4844Schema,
  'removeDelayAfterFork()': removeDelayAfterForkSchema,
  'rollup()': rollupSchema,
  'setBatchPosterManager(address)': setBatchPosterManagerSchema,
  'setBufferConfig((uint64,uint64,uint64))': setBufferConfigSchema,
  'setFeeTokenPricer(address)': setFeeTokenPricerSchema,
  'setIsBatchPoster(address,bool)': setIsBatchPosterSchema,
  'setIsSequencer(address,bool)': setIsSequencerSchema,
  'setMaxTimeVariation((uint256,uint256,uint256,uint256))': setMaxTimeVariationSchema,
  'setValidKeyset(bytes)': setValidKeysetSchema,
  'totalDelayedMessagesRead()': totalDelayedMessagesReadSchema,
  'updateRollupAddress()': updateRollupAddressSchema,
} as const;
