// Generated by abi-to-zod v0.0.0 from ERC1155.json
// Do not edit manually -- regenerate from source.

import { z } from 'zod';

// === Primitive schemas (edit once to customise all uses) ===

const ADDRESS = z.string().regex(/^0x[0-9a-fA-F]{40}$/).transform((v) => v as `0x${string}`);
const BOOL = z.boolean();
const BYTES = z.string().regex(/^0x([0-9a-fA-F]{2})*$/).transform((v) => v as `0x${string}`);
const BYTES4 = z.string().regex(/^0x[0-9a-fA-F]{8}$/).transform((v) => v as `0x${string}`);
const UINT256 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 256n) - 1n);

// === Function schemas ===

// balanceOf(address,uint256)
export const balanceOfSchema = z.tuple([
  /* account: address */ ADDRESS,
  /* id: uint256 */ UINT256,
]);

// balanceOfBatch(address[],uint256[])
export const balanceOfBatchSchema = z.tuple([
  /* accounts: address[] */ z.array(ADDRESS),
  /* ids: uint256[] */ z.array(UINT256),
]);

// isApprovedForAll(address,address)
export const isApprovedForAllSchema = z.tuple([
  /* account: address */ ADDRESS,
  /* operator: address */ ADDRESS,
]);

// safeBatchTransferFrom(address,address,uint256[],uint256[],bytes)
export const safeBatchTransferFromSchema = z.tuple([
  /* from: address */ ADDRESS,
  /* to: address */ ADDRESS,
  /* ids: uint256[] */ z.array(UINT256),
  /* values: uint256[] */ z.array(UINT256),
  /* data: bytes */ BYTES,
]);

// safeTransferFrom(address,address,uint256,uint256,bytes)
export const safeTransferFromSchema = z.tuple([
  /* from: address */ ADDRESS,
  /* to: address */ ADDRESS,
  /* id: uint256 */ UINT256,
  /* value: uint256 */ UINT256,
  /* data: bytes */ BYTES,
]);

// setApprovalForAll(address,bool)
export const setApprovalForAllSchema = z.tuple([
  /* operator: address */ ADDRESS,
  /* approved: bool */ BOOL,
]);

// supportsInterface(bytes4)
export const supportsInterfaceSchema = z.tuple([
  /* interfaceId: bytes4 */ BYTES4,
]);

// === Lookup barrel (mirrors abiToZod) ===

export const schemas = {
  balanceOf: balanceOfSchema,
  balanceOfBatch: balanceOfBatchSchema,
  isApprovedForAll: isApprovedForAllSchema,
  safeBatchTransferFrom: safeBatchTransferFromSchema,
  safeTransferFrom: safeTransferFromSchema,
  setApprovalForAll: setApprovalForAllSchema,
  supportsInterface: supportsInterfaceSchema,
  'balanceOf(address,uint256)': balanceOfSchema,
  'balanceOfBatch(address[],uint256[])': balanceOfBatchSchema,
  'isApprovedForAll(address,address)': isApprovedForAllSchema,
  'safeBatchTransferFrom(address,address,uint256[],uint256[],bytes)': safeBatchTransferFromSchema,
  'safeTransferFrom(address,address,uint256,uint256,bytes)': safeTransferFromSchema,
  'setApprovalForAll(address,bool)': setApprovalForAllSchema,
  'supportsInterface(bytes4)': supportsInterfaceSchema,
} as const;
