// Generated by abi-to-zod v0.0.0 from ERC721.json
// Do not edit manually -- regenerate from source.

import { z } from 'zod';

// === Primitive schemas (edit once to customise all uses) ===

const ADDRESS = z.string().regex(/^0x[0-9a-fA-F]{40}$/).transform((v) => v as `0x${string}`);
const BOOL = z.boolean();
const BYTES = z.string().regex(/^0x([0-9a-fA-F]{2})*$/).transform((v) => v as `0x${string}`);
const BYTES4 = z.string().regex(/^0x[0-9a-fA-F]{8}$/).transform((v) => v as `0x${string}`);
const UINT256 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 256n) - 1n);

// === Function schemas ===

// approve(address,uint256)
export const approveSchema = z.tuple([
  /* to: address */ ADDRESS,
  /* tokenId: uint256 */ UINT256,
]);

// balanceOf(address)
export const balanceOfSchema = z.tuple([
  /* owner: address */ ADDRESS,
]);

// getApproved(uint256)
export const getApprovedSchema = z.tuple([
  /* tokenId: uint256 */ UINT256,
]);

// isApprovedForAll(address,address)
export const isApprovedForAllSchema = z.tuple([
  /* owner: address */ ADDRESS,
  /* operator: address */ ADDRESS,
]);

// ownerOf(uint256)
export const ownerOfSchema = z.tuple([
  /* tokenId: uint256 */ UINT256,
]);

// setApprovalForAll(address,bool)
export const setApprovalForAllSchema = z.tuple([
  /* operator: address */ ADDRESS,
  /* approved: bool */ BOOL,
]);

// supportsInterface(bytes4)
export const supportsInterfaceSchema = z.tuple([
  /* interfaceId: bytes4 */ BYTES4,
]);

// transferFrom(address,address,uint256)
export const transferFromSchema = z.tuple([
  /* from: address */ ADDRESS,
  /* to: address */ ADDRESS,
  /* tokenId: uint256 */ UINT256,
]);

// === Lookup barrel (mirrors abiToZod) ===

export const schemas = {
  approve: approveSchema,
  balanceOf: balanceOfSchema,
  getApproved: getApprovedSchema,
  isApprovedForAll: isApprovedForAllSchema,
  ownerOf: ownerOfSchema,
  setApprovalForAll: setApprovalForAllSchema,
  supportsInterface: supportsInterfaceSchema,
  transferFrom: transferFromSchema,
  'approve(address,uint256)': approveSchema,
  'balanceOf(address)': balanceOfSchema,
  'getApproved(uint256)': getApprovedSchema,
  'isApprovedForAll(address,address)': isApprovedForAllSchema,
  'ownerOf(uint256)': ownerOfSchema,
  'safeTransferFrom(address,address,uint256)': z.tuple([
    /* from: address */ ADDRESS,
    /* to: address */ ADDRESS,
    /* tokenId: uint256 */ UINT256,
  ]),
  'safeTransferFrom(address,address,uint256,bytes)': z.tuple([
    /* from: address */ ADDRESS,
    /* to: address */ ADDRESS,
    /* tokenId: uint256 */ UINT256,
    /* data: bytes */ BYTES,
  ]),
  'setApprovalForAll(address,bool)': setApprovalForAllSchema,
  'supportsInterface(bytes4)': supportsInterfaceSchema,
  'transferFrom(address,address,uint256)': transferFromSchema,
} as const;
