// Generated by abi-to-zod v0.0.0 from ArbAddressTable.json
// Do not edit manually -- regenerate from source.

import { z } from 'zod';

// === Primitive schemas (edit once to customise all uses) ===

const ADDRESS = z.string().regex(/^0x[0-9a-fA-F]{40}$/).transform((v) => v as `0x${string}`);
const BYTES = z.string().regex(/^0x([0-9a-fA-F]{2})*$/).transform((v) => v as `0x${string}`);
const UINT256 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 256n) - 1n);

// === Function schemas ===

// addressExists(address)
export const addressExistsSchema = z.tuple([
  /* addr: address */ ADDRESS,
]);

// compress(address)
export const compressSchema = z.tuple([
  /* addr: address */ ADDRESS,
]);

// decompress(bytes,uint256)
export const decompressSchema = z.tuple([
  /* buf: bytes */ BYTES,
  /* offset: uint256 */ UINT256,
]);

// lookup(address)
export const lookupSchema = z.tuple([
  /* addr: address */ ADDRESS,
]);

// lookupIndex(uint256)
export const lookupIndexSchema = z.tuple([
  /* index: uint256 */ UINT256,
]);

// register(address)
export const registerSchema = z.tuple([
  /* addr: address */ ADDRESS,
]);

// size()
export const sizeSchema = z.tuple([]);

// === Lookup barrel (mirrors abiToZod) ===

export const schemas = {
  addressExists: addressExistsSchema,
  compress: compressSchema,
  decompress: decompressSchema,
  lookup: lookupSchema,
  lookupIndex: lookupIndexSchema,
  register: registerSchema,
  size: sizeSchema,
  'addressExists(address)': addressExistsSchema,
  'compress(address)': compressSchema,
  'decompress(bytes,uint256)': decompressSchema,
  'lookup(address)': lookupSchema,
  'lookupIndex(uint256)': lookupIndexSchema,
  'register(address)': registerSchema,
  'size()': sizeSchema,
} as const;
