// Generated by abi-to-zod v0.0.0 from ArbAggregator.json
// Do not edit manually -- regenerate from source.

import { z } from 'zod';

// === Primitive schemas (edit once to customise all uses) ===

const ADDRESS = z.string().regex(/^0x[0-9a-fA-F]{40}$/).transform((v) => v as `0x${string}`);
const UINT256 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 256n) - 1n);

// === Function schemas ===

// addBatchPoster(address)
export const addBatchPosterSchema = z.tuple([
  /* newBatchPoster: address */ ADDRESS,
]);

// getBatchPosters()
export const getBatchPostersSchema = z.tuple([]);

// getDefaultAggregator()
export const getDefaultAggregatorSchema = z.tuple([]);

// getFeeCollector(address)
export const getFeeCollectorSchema = z.tuple([
  /* batchPoster: address */ ADDRESS,
]);

// getPreferredAggregator(address)
export const getPreferredAggregatorSchema = z.tuple([
  /* addr: address */ ADDRESS,
]);

// getTxBaseFee(address)
export const getTxBaseFeeSchema = z.tuple([
  /* aggregator: address */ ADDRESS,
]);

// setFeeCollector(address,address)
export const setFeeCollectorSchema = z.tuple([
  /* batchPoster: address */ ADDRESS,
  /* newFeeCollector: address */ ADDRESS,
]);

// setTxBaseFee(address,uint256)
export const setTxBaseFeeSchema = z.tuple([
  /* aggregator: address */ ADDRESS,
  /* feeInL1Gas: uint256 */ UINT256,
]);

// === Lookup barrel (mirrors abiToZod) ===

export const schemas = {
  addBatchPoster: addBatchPosterSchema,
  getBatchPosters: getBatchPostersSchema,
  getDefaultAggregator: getDefaultAggregatorSchema,
  getFeeCollector: getFeeCollectorSchema,
  getPreferredAggregator: getPreferredAggregatorSchema,
  getTxBaseFee: getTxBaseFeeSchema,
  setFeeCollector: setFeeCollectorSchema,
  setTxBaseFee: setTxBaseFeeSchema,
  'addBatchPoster(address)': addBatchPosterSchema,
  'getBatchPosters()': getBatchPostersSchema,
  'getDefaultAggregator()': getDefaultAggregatorSchema,
  'getFeeCollector(address)': getFeeCollectorSchema,
  'getPreferredAggregator(address)': getPreferredAggregatorSchema,
  'getTxBaseFee(address)': getTxBaseFeeSchema,
  'setFeeCollector(address,address)': setFeeCollectorSchema,
  'setTxBaseFee(address,uint256)': setTxBaseFeeSchema,
} as const;
