// Generated by abi-to-zod v0.0.0 from ArbGasInfo.json
// Do not edit manually -- regenerate from source.

import { z } from 'zod';

// === Primitive schemas (edit once to customise all uses) ===

const ADDRESS = z.string().regex(/^0x[0-9a-fA-F]{40}$/).transform((v) => v as `0x${string}`);

// === Function schemas ===

// getAmortizedCostCapBips()
export const getAmortizedCostCapBipsSchema = z.tuple([]);

// getCurrentTxL1GasFees()
export const getCurrentTxL1GasFeesSchema = z.tuple([]);

// getGasAccountingParams()
export const getGasAccountingParamsSchema = z.tuple([]);

// getGasBacklog()
export const getGasBacklogSchema = z.tuple([]);

// getGasBacklogTolerance()
export const getGasBacklogToleranceSchema = z.tuple([]);

// getGasPricingConstraints()
export const getGasPricingConstraintsSchema = z.tuple([]);

// getL1BaseFeeEstimate()
export const getL1BaseFeeEstimateSchema = z.tuple([]);

// getL1BaseFeeEstimateInertia()
export const getL1BaseFeeEstimateInertiaSchema = z.tuple([]);

// getL1FeesAvailable()
export const getL1FeesAvailableSchema = z.tuple([]);

// getL1GasPriceEstimate()
export const getL1GasPriceEstimateSchema = z.tuple([]);

// getL1PricingEquilibrationUnits()
export const getL1PricingEquilibrationUnitsSchema = z.tuple([]);

// getL1PricingFundsDueForRewards()
export const getL1PricingFundsDueForRewardsSchema = z.tuple([]);

// getL1PricingSurplus()
export const getL1PricingSurplusSchema = z.tuple([]);

// getL1PricingUnitsSinceUpdate()
export const getL1PricingUnitsSinceUpdateSchema = z.tuple([]);

// getL1RewardRate()
export const getL1RewardRateSchema = z.tuple([]);

// getL1RewardRecipient()
export const getL1RewardRecipientSchema = z.tuple([]);

// getLastL1PricingSurplus()
export const getLastL1PricingSurplusSchema = z.tuple([]);

// getLastL1PricingUpdateTime()
export const getLastL1PricingUpdateTimeSchema = z.tuple([]);

// getMaxBlockGasLimit()
export const getMaxBlockGasLimitSchema = z.tuple([]);

// getMaxTxGasLimit()
export const getMaxTxGasLimitSchema = z.tuple([]);

// getMinimumGasPrice()
export const getMinimumGasPriceSchema = z.tuple([]);

// getPerBatchGasCharge()
export const getPerBatchGasChargeSchema = z.tuple([]);

// getPricesInArbGas()
export const getPricesInArbGasSchema = z.tuple([]);

// getPricesInArbGasWithAggregator(address)
export const getPricesInArbGasWithAggregatorSchema = z.tuple([
  /* aggregator: address */ ADDRESS,
]);

// getPricesInWei()
export const getPricesInWeiSchema = z.tuple([]);

// getPricesInWeiWithAggregator(address)
export const getPricesInWeiWithAggregatorSchema = z.tuple([
  /* aggregator: address */ ADDRESS,
]);

// getPricingInertia()
export const getPricingInertiaSchema = z.tuple([]);

// === Lookup barrel (mirrors abiToZod) ===

export const schemas = {
  getAmortizedCostCapBips: getAmortizedCostCapBipsSchema,
  getCurrentTxL1GasFees: getCurrentTxL1GasFeesSchema,
  getGasAccountingParams: getGasAccountingParamsSchema,
  getGasBacklog: getGasBacklogSchema,
  getGasBacklogTolerance: getGasBacklogToleranceSchema,
  getGasPricingConstraints: getGasPricingConstraintsSchema,
  getL1BaseFeeEstimate: getL1BaseFeeEstimateSchema,
  getL1BaseFeeEstimateInertia: getL1BaseFeeEstimateInertiaSchema,
  getL1FeesAvailable: getL1FeesAvailableSchema,
  getL1GasPriceEstimate: getL1GasPriceEstimateSchema,
  getL1PricingEquilibrationUnits: getL1PricingEquilibrationUnitsSchema,
  getL1PricingFundsDueForRewards: getL1PricingFundsDueForRewardsSchema,
  getL1PricingSurplus: getL1PricingSurplusSchema,
  getL1PricingUnitsSinceUpdate: getL1PricingUnitsSinceUpdateSchema,
  getL1RewardRate: getL1RewardRateSchema,
  getL1RewardRecipient: getL1RewardRecipientSchema,
  getLastL1PricingSurplus: getLastL1PricingSurplusSchema,
  getLastL1PricingUpdateTime: getLastL1PricingUpdateTimeSchema,
  getMaxBlockGasLimit: getMaxBlockGasLimitSchema,
  getMaxTxGasLimit: getMaxTxGasLimitSchema,
  getMinimumGasPrice: getMinimumGasPriceSchema,
  getPerBatchGasCharge: getPerBatchGasChargeSchema,
  getPricesInArbGas: getPricesInArbGasSchema,
  getPricesInArbGasWithAggregator: getPricesInArbGasWithAggregatorSchema,
  getPricesInWei: getPricesInWeiSchema,
  getPricesInWeiWithAggregator: getPricesInWeiWithAggregatorSchema,
  getPricingInertia: getPricingInertiaSchema,
  'getAmortizedCostCapBips()': getAmortizedCostCapBipsSchema,
  'getCurrentTxL1GasFees()': getCurrentTxL1GasFeesSchema,
  'getGasAccountingParams()': getGasAccountingParamsSchema,
  'getGasBacklog()': getGasBacklogSchema,
  'getGasBacklogTolerance()': getGasBacklogToleranceSchema,
  'getGasPricingConstraints()': getGasPricingConstraintsSchema,
  'getL1BaseFeeEstimate()': getL1BaseFeeEstimateSchema,
  'getL1BaseFeeEstimateInertia()': getL1BaseFeeEstimateInertiaSchema,
  'getL1FeesAvailable()': getL1FeesAvailableSchema,
  'getL1GasPriceEstimate()': getL1GasPriceEstimateSchema,
  'getL1PricingEquilibrationUnits()': getL1PricingEquilibrationUnitsSchema,
  'getL1PricingFundsDueForRewards()': getL1PricingFundsDueForRewardsSchema,
  'getL1PricingSurplus()': getL1PricingSurplusSchema,
  'getL1PricingUnitsSinceUpdate()': getL1PricingUnitsSinceUpdateSchema,
  'getL1RewardRate()': getL1RewardRateSchema,
  'getL1RewardRecipient()': getL1RewardRecipientSchema,
  'getLastL1PricingSurplus()': getLastL1PricingSurplusSchema,
  'getLastL1PricingUpdateTime()': getLastL1PricingUpdateTimeSchema,
  'getMaxBlockGasLimit()': getMaxBlockGasLimitSchema,
  'getMaxTxGasLimit()': getMaxTxGasLimitSchema,
  'getMinimumGasPrice()': getMinimumGasPriceSchema,
  'getPerBatchGasCharge()': getPerBatchGasChargeSchema,
  'getPricesInArbGas()': getPricesInArbGasSchema,
  'getPricesInArbGasWithAggregator(address)': getPricesInArbGasWithAggregatorSchema,
  'getPricesInWei()': getPricesInWeiSchema,
  'getPricesInWeiWithAggregator(address)': getPricesInWeiWithAggregatorSchema,
  'getPricingInertia()': getPricingInertiaSchema,
} as const;
