// Generated by abi-to-zod v0.0.0 from ArbInfo.json
// Do not edit manually -- regenerate from source.

import { z } from 'zod';

// === Primitive schemas (edit once to customise all uses) ===

const ADDRESS = z.string().regex(/^0x[0-9a-fA-F]{40}$/).transform((v) => v as `0x${string}`);

// === Function schemas ===

// getBalance(address)
export const getBalanceSchema = z.tuple([
  /* account: address */ ADDRESS,
]);

// getCode(address)
export const getCodeSchema = z.tuple([
  /* account: address */ ADDRESS,
]);

// === Lookup barrel (mirrors abiToZod) ===

export const schemas = {
  getBalance: getBalanceSchema,
  getCode: getCodeSchema,
  'getBalance(address)': getBalanceSchema,
  'getCode(address)': getCodeSchema,
} as const;
