// Generated by abi-to-zod v0.0.0 from ArbOwnerPublic.json
// Do not edit manually -- regenerate from source.

import { z } from 'zod';

// === Primitive schemas (edit once to customise all uses) ===

const ADDRESS = z.string().regex(/^0x[0-9a-fA-F]{40}$/).transform((v) => v as `0x${string}`);

// === Function schemas ===

// getAllChainOwners()
export const getAllChainOwnersSchema = z.tuple([]);

// getAllNativeTokenOwners()
export const getAllNativeTokenOwnersSchema = z.tuple([]);

// getBrotliCompressionLevel()
export const getBrotliCompressionLevelSchema = z.tuple([]);

// getInfraFeeAccount()
export const getInfraFeeAccountSchema = z.tuple([]);

// getNativeTokenManagementFrom()
export const getNativeTokenManagementFromSchema = z.tuple([]);

// getNetworkFeeAccount()
export const getNetworkFeeAccountSchema = z.tuple([]);

// getParentGasFloorPerToken()
export const getParentGasFloorPerTokenSchema = z.tuple([]);

// getScheduledUpgrade()
export const getScheduledUpgradeSchema = z.tuple([]);

// isCalldataPriceIncreaseEnabled()
export const isCalldataPriceIncreaseEnabledSchema = z.tuple([]);

// isChainOwner(address)
export const isChainOwnerSchema = z.tuple([
  /* addr: address */ ADDRESS,
]);

// isNativeTokenOwner(address)
export const isNativeTokenOwnerSchema = z.tuple([
  /* addr: address */ ADDRESS,
]);

// rectifyChainOwner(address)
export const rectifyChainOwnerSchema = z.tuple([
  /* ownerToRectify: address */ ADDRESS,
]);

// === Lookup barrel (mirrors abiToZod) ===

export const schemas = {
  getAllChainOwners: getAllChainOwnersSchema,
  getAllNativeTokenOwners: getAllNativeTokenOwnersSchema,
  getBrotliCompressionLevel: getBrotliCompressionLevelSchema,
  getInfraFeeAccount: getInfraFeeAccountSchema,
  getNativeTokenManagementFrom: getNativeTokenManagementFromSchema,
  getNetworkFeeAccount: getNetworkFeeAccountSchema,
  getParentGasFloorPerToken: getParentGasFloorPerTokenSchema,
  getScheduledUpgrade: getScheduledUpgradeSchema,
  isCalldataPriceIncreaseEnabled: isCalldataPriceIncreaseEnabledSchema,
  isChainOwner: isChainOwnerSchema,
  isNativeTokenOwner: isNativeTokenOwnerSchema,
  rectifyChainOwner: rectifyChainOwnerSchema,
  'getAllChainOwners()': getAllChainOwnersSchema,
  'getAllNativeTokenOwners()': getAllNativeTokenOwnersSchema,
  'getBrotliCompressionLevel()': getBrotliCompressionLevelSchema,
  'getInfraFeeAccount()': getInfraFeeAccountSchema,
  'getNativeTokenManagementFrom()': getNativeTokenManagementFromSchema,
  'getNetworkFeeAccount()': getNetworkFeeAccountSchema,
  'getParentGasFloorPerToken()': getParentGasFloorPerTokenSchema,
  'getScheduledUpgrade()': getScheduledUpgradeSchema,
  'isCalldataPriceIncreaseEnabled()': isCalldataPriceIncreaseEnabledSchema,
  'isChainOwner(address)': isChainOwnerSchema,
  'isNativeTokenOwner(address)': isNativeTokenOwnerSchema,
  'rectifyChainOwner(address)': rectifyChainOwnerSchema,
} as const;
