// Generated by abi-to-zod v0.0.0 from ArbOwner.json
// Do not edit manually -- regenerate from source.

import { z } from 'zod';

// === Primitive schemas (edit once to customise all uses) ===

const ADDRESS = z.string().regex(/^0x[0-9a-fA-F]{40}$/).transform((v) => v as `0x${string}`);
const BOOL = z.boolean();
const INT64 = z.string().regex(/^-?\d+$/).transform((v) => BigInt(v)).refine((n) => n >= -(1n << 63n) && n <= (1n << 63n) - 1n);
const STRING = z.string();
const UINT16 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 16n) - 1n);
const UINT256 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 256n) - 1n);
const UINT32 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 32n) - 1n);
const UINT64 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 64n) - 1n);
const UINT8 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 8n) - 1n);

// === Function schemas ===

// addChainOwner(address)
export const addChainOwnerSchema = z.tuple([
  /* newOwner: address */ ADDRESS,
]);

// addNativeTokenOwner(address)
export const addNativeTokenOwnerSchema = z.tuple([
  /* newOwner: address */ ADDRESS,
]);

// addWasmCacheManager(address)
export const addWasmCacheManagerSchema = z.tuple([
  /* manager: address */ ADDRESS,
]);

// getAllChainOwners()
export const getAllChainOwnersSchema = z.tuple([]);

// getAllNativeTokenOwners()
export const getAllNativeTokenOwnersSchema = z.tuple([]);

// getInfraFeeAccount()
export const getInfraFeeAccountSchema = z.tuple([]);

// getNetworkFeeAccount()
export const getNetworkFeeAccountSchema = z.tuple([]);

// isChainOwner(address)
export const isChainOwnerSchema = z.tuple([
  /* addr: address */ ADDRESS,
]);

// isNativeTokenOwner(address)
export const isNativeTokenOwnerSchema = z.tuple([
  /* addr: address */ ADDRESS,
]);

// releaseL1PricerSurplusFunds(uint256)
export const releaseL1PricerSurplusFundsSchema = z.tuple([
  /* maxWeiToRelease: uint256 */ UINT256,
]);

// removeChainOwner(address)
export const removeChainOwnerSchema = z.tuple([
  /* ownerToRemove: address */ ADDRESS,
]);

// removeNativeTokenOwner(address)
export const removeNativeTokenOwnerSchema = z.tuple([
  /* ownerToRemove: address */ ADDRESS,
]);

// removeWasmCacheManager(address)
export const removeWasmCacheManagerSchema = z.tuple([
  /* manager: address */ ADDRESS,
]);

// scheduleArbOSUpgrade(uint64,uint64)
export const scheduleArbOSUpgradeSchema = z.tuple([
  /* newVersion: uint64 */ UINT64,
  /* timestamp: uint64 */ UINT64,
]);

// setAmortizedCostCapBips(uint64)
export const setAmortizedCostCapBipsSchema = z.tuple([
  /* cap: uint64 */ UINT64,
]);

// setBrotliCompressionLevel(uint64)
export const setBrotliCompressionLevelSchema = z.tuple([
  /* level: uint64 */ UINT64,
]);

// setCalldataPriceIncrease(bool)
export const setCalldataPriceIncreaseSchema = z.tuple([
  /* enable: bool */ BOOL,
]);

// setChainConfig(string)
export const setChainConfigSchema = z.tuple([
  /* chainConfig: string */ STRING,
]);

// setGasBacklog(uint64)
export const setGasBacklogSchema = z.tuple([
  /* backlog: uint64 */ UINT64,
]);

// setGasPricingConstraints(uint64[3][])
export const setGasPricingConstraintsSchema = z.tuple([
  /* constraints: uint64[3][] */ z.array(z.array(UINT64).length(3)),
]);

// setInfraFeeAccount(address)
export const setInfraFeeAccountSchema = z.tuple([
  /* newInfraFeeAccount: address */ ADDRESS,
]);

// setInkPrice(uint32)
export const setInkPriceSchema = z.tuple([
  /* price: uint32 */ UINT32,
]);

// setL1BaseFeeEstimateInertia(uint64)
export const setL1BaseFeeEstimateInertiaSchema = z.tuple([
  /* inertia: uint64 */ UINT64,
]);

// setL1PricePerUnit(uint256)
export const setL1PricePerUnitSchema = z.tuple([
  /* pricePerUnit: uint256 */ UINT256,
]);

// setL1PricingEquilibrationUnits(uint256)
export const setL1PricingEquilibrationUnitsSchema = z.tuple([
  /* equilibrationUnits: uint256 */ UINT256,
]);

// setL1PricingInertia(uint64)
export const setL1PricingInertiaSchema = z.tuple([
  /* inertia: uint64 */ UINT64,
]);

// setL1PricingRewardRate(uint64)
export const setL1PricingRewardRateSchema = z.tuple([
  /* weiPerUnit: uint64 */ UINT64,
]);

// setL1PricingRewardRecipient(address)
export const setL1PricingRewardRecipientSchema = z.tuple([
  /* recipient: address */ ADDRESS,
]);

// setL2BaseFee(uint256)
export const setL2BaseFeeSchema = z.tuple([
  /* priceInWei: uint256 */ UINT256,
]);

// setL2GasBacklogTolerance(uint64)
export const setL2GasBacklogToleranceSchema = z.tuple([
  /* sec: uint64 */ UINT64,
]);

// setL2GasPricingInertia(uint64)
export const setL2GasPricingInertiaSchema = z.tuple([
  /* sec: uint64 */ UINT64,
]);

// setMaxBlockGasLimit(uint64)
export const setMaxBlockGasLimitSchema = z.tuple([
  /* limit: uint64 */ UINT64,
]);

// setMaxTxGasLimit(uint64)
export const setMaxTxGasLimitSchema = z.tuple([
  /* limit: uint64 */ UINT64,
]);

// setMinimumL2BaseFee(uint256)
export const setMinimumL2BaseFeeSchema = z.tuple([
  /* priceInWei: uint256 */ UINT256,
]);

// setNativeTokenManagementFrom(uint64)
export const setNativeTokenManagementFromSchema = z.tuple([
  /* timestamp: uint64 */ UINT64,
]);

// setNetworkFeeAccount(address)
export const setNetworkFeeAccountSchema = z.tuple([
  /* newNetworkFeeAccount: address */ ADDRESS,
]);

// setParentGasFloorPerToken(uint64)
export const setParentGasFloorPerTokenSchema = z.tuple([
  /* floorPerToken: uint64 */ UINT64,
]);

// setPerBatchGasCharge(int64)
export const setPerBatchGasChargeSchema = z.tuple([
  /* cost: int64 */ INT64,
]);

// setSpeedLimit(uint64)
export const setSpeedLimitSchema = z.tuple([
  /* limit: uint64 */ UINT64,
]);

// setWasmBlockCacheSize(uint16)
export const setWasmBlockCacheSizeSchema = z.tuple([
  /* count: uint16 */ UINT16,
]);

// setWasmExpiryDays(uint16)
export const setWasmExpiryDaysSchema = z.tuple([
  /* _days: uint16 */ UINT16,
]);

// setWasmFreePages(uint16)
export const setWasmFreePagesSchema = z.tuple([
  /* pages: uint16 */ UINT16,
]);

// setWasmInitCostScalar(uint64)
export const setWasmInitCostScalarSchema = z.tuple([
  /* percent: uint64 */ UINT64,
]);

// setWasmKeepaliveDays(uint16)
export const setWasmKeepaliveDaysSchema = z.tuple([
  /* _days: uint16 */ UINT16,
]);

// setWasmMaxSize(uint32)
export const setWasmMaxSizeSchema = z.tuple([
  /* size: uint32 */ UINT32,
]);

// setWasmMaxStackDepth(uint32)
export const setWasmMaxStackDepthSchema = z.tuple([
  /* depth: uint32 */ UINT32,
]);

// setWasmMinInitGas(uint8,uint16)
export const setWasmMinInitGasSchema = z.tuple([
  /* gas: uint8 */ UINT8,
  /* cached: uint16 */ UINT16,
]);

// setWasmPageGas(uint16)
export const setWasmPageGasSchema = z.tuple([
  /* gas: uint16 */ UINT16,
]);

// setWasmPageLimit(uint16)
export const setWasmPageLimitSchema = z.tuple([
  /* limit: uint16 */ UINT16,
]);

// === Lookup barrel (mirrors abiToZod) ===

export const schemas = {
  addChainOwner: addChainOwnerSchema,
  addNativeTokenOwner: addNativeTokenOwnerSchema,
  addWasmCacheManager: addWasmCacheManagerSchema,
  getAllChainOwners: getAllChainOwnersSchema,
  getAllNativeTokenOwners: getAllNativeTokenOwnersSchema,
  getInfraFeeAccount: getInfraFeeAccountSchema,
  getNetworkFeeAccount: getNetworkFeeAccountSchema,
  isChainOwner: isChainOwnerSchema,
  isNativeTokenOwner: isNativeTokenOwnerSchema,
  releaseL1PricerSurplusFunds: releaseL1PricerSurplusFundsSchema,
  removeChainOwner: removeChainOwnerSchema,
  removeNativeTokenOwner: removeNativeTokenOwnerSchema,
  removeWasmCacheManager: removeWasmCacheManagerSchema,
  scheduleArbOSUpgrade: scheduleArbOSUpgradeSchema,
  setAmortizedCostCapBips: setAmortizedCostCapBipsSchema,
  setBrotliCompressionLevel: setBrotliCompressionLevelSchema,
  setCalldataPriceIncrease: setCalldataPriceIncreaseSchema,
  setChainConfig: setChainConfigSchema,
  setGasBacklog: setGasBacklogSchema,
  setGasPricingConstraints: setGasPricingConstraintsSchema,
  setInfraFeeAccount: setInfraFeeAccountSchema,
  setInkPrice: setInkPriceSchema,
  setL1BaseFeeEstimateInertia: setL1BaseFeeEstimateInertiaSchema,
  setL1PricePerUnit: setL1PricePerUnitSchema,
  setL1PricingEquilibrationUnits: setL1PricingEquilibrationUnitsSchema,
  setL1PricingInertia: setL1PricingInertiaSchema,
  setL1PricingRewardRate: setL1PricingRewardRateSchema,
  setL1PricingRewardRecipient: setL1PricingRewardRecipientSchema,
  setL2BaseFee: setL2BaseFeeSchema,
  setL2GasBacklogTolerance: setL2GasBacklogToleranceSchema,
  setL2GasPricingInertia: setL2GasPricingInertiaSchema,
  setMaxBlockGasLimit: setMaxBlockGasLimitSchema,
  setMaxTxGasLimit: setMaxTxGasLimitSchema,
  setMinimumL2BaseFee: setMinimumL2BaseFeeSchema,
  setNativeTokenManagementFrom: setNativeTokenManagementFromSchema,
  setNetworkFeeAccount: setNetworkFeeAccountSchema,
  setParentGasFloorPerToken: setParentGasFloorPerTokenSchema,
  setPerBatchGasCharge: setPerBatchGasChargeSchema,
  setSpeedLimit: setSpeedLimitSchema,
  setWasmBlockCacheSize: setWasmBlockCacheSizeSchema,
  setWasmExpiryDays: setWasmExpiryDaysSchema,
  setWasmFreePages: setWasmFreePagesSchema,
  setWasmInitCostScalar: setWasmInitCostScalarSchema,
  setWasmKeepaliveDays: setWasmKeepaliveDaysSchema,
  setWasmMaxSize: setWasmMaxSizeSchema,
  setWasmMaxStackDepth: setWasmMaxStackDepthSchema,
  setWasmMinInitGas: setWasmMinInitGasSchema,
  setWasmPageGas: setWasmPageGasSchema,
  setWasmPageLimit: setWasmPageLimitSchema,
  'addChainOwner(address)': addChainOwnerSchema,
  'addNativeTokenOwner(address)': addNativeTokenOwnerSchema,
  'addWasmCacheManager(address)': addWasmCacheManagerSchema,
  'getAllChainOwners()': getAllChainOwnersSchema,
  'getAllNativeTokenOwners()': getAllNativeTokenOwnersSchema,
  'getInfraFeeAccount()': getInfraFeeAccountSchema,
  'getNetworkFeeAccount()': getNetworkFeeAccountSchema,
  'isChainOwner(address)': isChainOwnerSchema,
  'isNativeTokenOwner(address)': isNativeTokenOwnerSchema,
  'releaseL1PricerSurplusFunds(uint256)': releaseL1PricerSurplusFundsSchema,
  'removeChainOwner(address)': removeChainOwnerSchema,
  'removeNativeTokenOwner(address)': removeNativeTokenOwnerSchema,
  'removeWasmCacheManager(address)': removeWasmCacheManagerSchema,
  'scheduleArbOSUpgrade(uint64,uint64)': scheduleArbOSUpgradeSchema,
  'setAmortizedCostCapBips(uint64)': setAmortizedCostCapBipsSchema,
  'setBrotliCompressionLevel(uint64)': setBrotliCompressionLevelSchema,
  'setCalldataPriceIncrease(bool)': setCalldataPriceIncreaseSchema,
  'setChainConfig(string)': setChainConfigSchema,
  'setGasBacklog(uint64)': setGasBacklogSchema,
  'setGasPricingConstraints(uint64[3][])': setGasPricingConstraintsSchema,
  'setInfraFeeAccount(address)': setInfraFeeAccountSchema,
  'setInkPrice(uint32)': setInkPriceSchema,
  'setL1BaseFeeEstimateInertia(uint64)': setL1BaseFeeEstimateInertiaSchema,
  'setL1PricePerUnit(uint256)': setL1PricePerUnitSchema,
  'setL1PricingEquilibrationUnits(uint256)': setL1PricingEquilibrationUnitsSchema,
  'setL1PricingInertia(uint64)': setL1PricingInertiaSchema,
  'setL1PricingRewardRate(uint64)': setL1PricingRewardRateSchema,
  'setL1PricingRewardRecipient(address)': setL1PricingRewardRecipientSchema,
  'setL2BaseFee(uint256)': setL2BaseFeeSchema,
  'setL2GasBacklogTolerance(uint64)': setL2GasBacklogToleranceSchema,
  'setL2GasPricingInertia(uint64)': setL2GasPricingInertiaSchema,
  'setMaxBlockGasLimit(uint64)': setMaxBlockGasLimitSchema,
  'setMaxTxGasLimit(uint64)': setMaxTxGasLimitSchema,
  'setMinimumL2BaseFee(uint256)': setMinimumL2BaseFeeSchema,
  'setNativeTokenManagementFrom(uint64)': setNativeTokenManagementFromSchema,
  'setNetworkFeeAccount(address)': setNetworkFeeAccountSchema,
  'setParentGasFloorPerToken(uint64)': setParentGasFloorPerTokenSchema,
  'setPerBatchGasCharge(int64)': setPerBatchGasChargeSchema,
  'setSpeedLimit(uint64)': setSpeedLimitSchema,
  'setWasmBlockCacheSize(uint16)': setWasmBlockCacheSizeSchema,
  'setWasmExpiryDays(uint16)': setWasmExpiryDaysSchema,
  'setWasmFreePages(uint16)': setWasmFreePagesSchema,
  'setWasmInitCostScalar(uint64)': setWasmInitCostScalarSchema,
  'setWasmKeepaliveDays(uint16)': setWasmKeepaliveDaysSchema,
  'setWasmMaxSize(uint32)': setWasmMaxSizeSchema,
  'setWasmMaxStackDepth(uint32)': setWasmMaxStackDepthSchema,
  'setWasmMinInitGas(uint8,uint16)': setWasmMinInitGasSchema,
  'setWasmPageGas(uint16)': setWasmPageGasSchema,
  'setWasmPageLimit(uint16)': setWasmPageLimitSchema,
} as const;
