// Generated by abi-to-zod v0.0.0 from ArbRetryableTx.json
// Do not edit manually -- regenerate from source.

import { z } from 'zod';

// === Primitive schemas (edit once to customise all uses) ===

const ADDRESS = z.string().regex(/^0x[0-9a-fA-F]{40}$/).transform((v) => v as `0x${string}`);
const BYTES = z.string().regex(/^0x([0-9a-fA-F]{2})*$/).transform((v) => v as `0x${string}`);
const BYTES32 = z.string().regex(/^0x[0-9a-fA-F]{64}$/).transform((v) => v as `0x${string}`);
const UINT256 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 256n) - 1n);
const UINT64 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 64n) - 1n);

// === Function schemas ===

// cancel(bytes32)
export const cancelSchema = z.tuple([
  /* ticketId: bytes32 */ BYTES32,
]);

// getBeneficiary(bytes32)
export const getBeneficiarySchema = z.tuple([
  /* ticketId: bytes32 */ BYTES32,
]);

// getCurrentRedeemer()
export const getCurrentRedeemerSchema = z.tuple([]);

// getLifetime()
export const getLifetimeSchema = z.tuple([]);

// getTimeout(bytes32)
export const getTimeoutSchema = z.tuple([
  /* ticketId: bytes32 */ BYTES32,
]);

// keepalive(bytes32)
export const keepaliveSchema = z.tuple([
  /* ticketId: bytes32 */ BYTES32,
]);

// redeem(bytes32)
export const redeemSchema = z.tuple([
  /* ticketId: bytes32 */ BYTES32,
]);

// submitRetryable(bytes32,uint256,uint256,uint256,uint256,uint64,uint256,address,address,address,bytes)
export const submitRetryableSchema = z.tuple([
  /* requestId: bytes32 */ BYTES32,
  /* l1BaseFee: uint256 */ UINT256,
  /* deposit: uint256 */ UINT256,
  /* callvalue: uint256 */ UINT256,
  /* gasFeeCap: uint256 */ UINT256,
  /* gasLimit: uint64 */ UINT64,
  /* maxSubmissionFee: uint256 */ UINT256,
  /* feeRefundAddress: address */ ADDRESS,
  /* beneficiary: address */ ADDRESS,
  /* retryTo: address */ ADDRESS,
  /* retryData: bytes */ BYTES,
]);

// === Lookup barrel (mirrors abiToZod) ===

export const schemas = {
  cancel: cancelSchema,
  getBeneficiary: getBeneficiarySchema,
  getCurrentRedeemer: getCurrentRedeemerSchema,
  getLifetime: getLifetimeSchema,
  getTimeout: getTimeoutSchema,
  keepalive: keepaliveSchema,
  redeem: redeemSchema,
  submitRetryable: submitRetryableSchema,
  'cancel(bytes32)': cancelSchema,
  'getBeneficiary(bytes32)': getBeneficiarySchema,
  'getCurrentRedeemer()': getCurrentRedeemerSchema,
  'getLifetime()': getLifetimeSchema,
  'getTimeout(bytes32)': getTimeoutSchema,
  'keepalive(bytes32)': keepaliveSchema,
  'redeem(bytes32)': redeemSchema,
  'submitRetryable(bytes32,uint256,uint256,uint256,uint256,uint64,uint256,address,address,address,bytes)': submitRetryableSchema,
} as const;
