// Generated by abi-to-zod v0.0.0 from ArbSys.json
// Do not edit manually -- regenerate from source.

import { z } from 'zod';

// === Primitive schemas (edit once to customise all uses) ===

const ADDRESS = z.string().regex(/^0x[0-9a-fA-F]{40}$/).transform((v) => v as `0x${string}`);
const BYTES = z.string().regex(/^0x([0-9a-fA-F]{2})*$/).transform((v) => v as `0x${string}`);
const UINT256 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 256n) - 1n);

// === Function schemas ===

// arbBlockHash(uint256)
export const arbBlockHashSchema = z.tuple([
  /* arbBlockNum: uint256 */ UINT256,
]);

// arbBlockNumber()
export const arbBlockNumberSchema = z.tuple([]);

// arbChainID()
export const arbChainIDSchema = z.tuple([]);

// arbOSVersion()
export const arbOSVersionSchema = z.tuple([]);

// getStorageGasAvailable()
export const getStorageGasAvailableSchema = z.tuple([]);

// isTopLevelCall()
export const isTopLevelCallSchema = z.tuple([]);

// mapL1SenderContractAddressToL2Alias(address,address)
export const mapL1SenderContractAddressToL2AliasSchema = z.tuple([
  /* sender: address */ ADDRESS,
  /* unused: address */ ADDRESS,
]);

// myCallersAddressWithoutAliasing()
export const myCallersAddressWithoutAliasingSchema = z.tuple([]);

// sendMerkleTreeState()
export const sendMerkleTreeStateSchema = z.tuple([]);

// sendTxToL1(address,bytes)
export const sendTxToL1Schema = z.tuple([
  /* destination: address */ ADDRESS,
  /* data: bytes */ BYTES,
]);

// wasMyCallersAddressAliased()
export const wasMyCallersAddressAliasedSchema = z.tuple([]);

// withdrawEth(address)
export const withdrawEthSchema = z.tuple([
  /* destination: address */ ADDRESS,
]);

// === Lookup barrel (mirrors abiToZod) ===

export const schemas = {
  arbBlockHash: arbBlockHashSchema,
  arbBlockNumber: arbBlockNumberSchema,
  arbChainID: arbChainIDSchema,
  arbOSVersion: arbOSVersionSchema,
  getStorageGasAvailable: getStorageGasAvailableSchema,
  isTopLevelCall: isTopLevelCallSchema,
  mapL1SenderContractAddressToL2Alias: mapL1SenderContractAddressToL2AliasSchema,
  myCallersAddressWithoutAliasing: myCallersAddressWithoutAliasingSchema,
  sendMerkleTreeState: sendMerkleTreeStateSchema,
  sendTxToL1: sendTxToL1Schema,
  wasMyCallersAddressAliased: wasMyCallersAddressAliasedSchema,
  withdrawEth: withdrawEthSchema,
  'arbBlockHash(uint256)': arbBlockHashSchema,
  'arbBlockNumber()': arbBlockNumberSchema,
  'arbChainID()': arbChainIDSchema,
  'arbOSVersion()': arbOSVersionSchema,
  'getStorageGasAvailable()': getStorageGasAvailableSchema,
  'isTopLevelCall()': isTopLevelCallSchema,
  'mapL1SenderContractAddressToL2Alias(address,address)': mapL1SenderContractAddressToL2AliasSchema,
  'myCallersAddressWithoutAliasing()': myCallersAddressWithoutAliasingSchema,
  'sendMerkleTreeState()': sendMerkleTreeStateSchema,
  'sendTxToL1(address,bytes)': sendTxToL1Schema,
  'wasMyCallersAddressAliased()': wasMyCallersAddressAliasedSchema,
  'withdrawEth(address)': withdrawEthSchema,
} as const;
