// Generated by abi-to-zod v0.0.0 from ArbStatistics.json
// Do not edit manually -- regenerate from source.

import { z } from 'zod';

// === Function schemas ===

// getStats()
export const getStatsSchema = z.tuple([]);

// === Lookup barrel (mirrors abiToZod) ===

export const schemas = {
  getStats: getStatsSchema,
  'getStats()': getStatsSchema,
} as const;
