// Generated by abi-to-zod v0.0.0 from ArbWasm.json
// Do not edit manually -- regenerate from source.

import { z } from 'zod';

// === Primitive schemas (edit once to customise all uses) ===

const ADDRESS = z.string().regex(/^0x[0-9a-fA-F]{40}$/).transform((v) => v as `0x${string}`);
const BYTES32 = z.string().regex(/^0x[0-9a-fA-F]{64}$/).transform((v) => v as `0x${string}`);

// === Function schemas ===

// activateProgram(address)
export const activateProgramSchema = z.tuple([
  /* program: address */ ADDRESS,
]);

// blockCacheSize()
export const blockCacheSizeSchema = z.tuple([]);

// codehashAsmSize(bytes32)
export const codehashAsmSizeSchema = z.tuple([
  /* codehash: bytes32 */ BYTES32,
]);

// codehashKeepalive(bytes32)
export const codehashKeepaliveSchema = z.tuple([
  /* codehash: bytes32 */ BYTES32,
]);

// codehashVersion(bytes32)
export const codehashVersionSchema = z.tuple([
  /* codehash: bytes32 */ BYTES32,
]);

// expiryDays()
export const expiryDaysSchema = z.tuple([]);

// freePages()
export const freePagesSchema = z.tuple([]);

// initCostScalar()
export const initCostScalarSchema = z.tuple([]);

// inkPrice()
export const inkPriceSchema = z.tuple([]);

// keepaliveDays()
export const keepaliveDaysSchema = z.tuple([]);

// maxStackDepth()
export const maxStackDepthSchema = z.tuple([]);

// minInitGas()
export const minInitGasSchema = z.tuple([]);

// pageGas()
export const pageGasSchema = z.tuple([]);

// pageLimit()
export const pageLimitSchema = z.tuple([]);

// pageRamp()
export const pageRampSchema = z.tuple([]);

// programInitGas(address)
export const programInitGasSchema = z.tuple([
  /* program: address */ ADDRESS,
]);

// programMemoryFootprint(address)
export const programMemoryFootprintSchema = z.tuple([
  /* program: address */ ADDRESS,
]);

// programTimeLeft(address)
export const programTimeLeftSchema = z.tuple([
  /* program: address */ ADDRESS,
]);

// programVersion(address)
export const programVersionSchema = z.tuple([
  /* program: address */ ADDRESS,
]);

// stylusVersion()
export const stylusVersionSchema = z.tuple([]);

// === Lookup barrel (mirrors abiToZod) ===

export const schemas = {
  activateProgram: activateProgramSchema,
  blockCacheSize: blockCacheSizeSchema,
  codehashAsmSize: codehashAsmSizeSchema,
  codehashKeepalive: codehashKeepaliveSchema,
  codehashVersion: codehashVersionSchema,
  expiryDays: expiryDaysSchema,
  freePages: freePagesSchema,
  initCostScalar: initCostScalarSchema,
  inkPrice: inkPriceSchema,
  keepaliveDays: keepaliveDaysSchema,
  maxStackDepth: maxStackDepthSchema,
  minInitGas: minInitGasSchema,
  pageGas: pageGasSchema,
  pageLimit: pageLimitSchema,
  pageRamp: pageRampSchema,
  programInitGas: programInitGasSchema,
  programMemoryFootprint: programMemoryFootprintSchema,
  programTimeLeft: programTimeLeftSchema,
  programVersion: programVersionSchema,
  stylusVersion: stylusVersionSchema,
  'activateProgram(address)': activateProgramSchema,
  'blockCacheSize()': blockCacheSizeSchema,
  'codehashAsmSize(bytes32)': codehashAsmSizeSchema,
  'codehashKeepalive(bytes32)': codehashKeepaliveSchema,
  'codehashVersion(bytes32)': codehashVersionSchema,
  'expiryDays()': expiryDaysSchema,
  'freePages()': freePagesSchema,
  'initCostScalar()': initCostScalarSchema,
  'inkPrice()': inkPriceSchema,
  'keepaliveDays()': keepaliveDaysSchema,
  'maxStackDepth()': maxStackDepthSchema,
  'minInitGas()': minInitGasSchema,
  'pageGas()': pageGasSchema,
  'pageLimit()': pageLimitSchema,
  'pageRamp()': pageRampSchema,
  'programInitGas(address)': programInitGasSchema,
  'programMemoryFootprint(address)': programMemoryFootprintSchema,
  'programTimeLeft(address)': programTimeLeftSchema,
  'programVersion(address)': programVersionSchema,
  'stylusVersion()': stylusVersionSchema,
} as const;
