import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import { join, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';

import { generate } from './codegen.js';
import { abiToZod, filterFunctions, canonicalSignature, type Abi } from './abi.js';

const fixturesRoot = join(dirname(fileURLToPath(import.meta.url)), '..', 'test', 'fixtures');

function* walkJson(dir: string): Generator<string> {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) yield* walkJson(full);
    else if (entry.isFile() && entry.name.endsWith('.json')) yield full;
  }
}

function loadAbi(path: string): Abi {
  return JSON.parse(readFileSync(path, 'utf8')) as Abi;
}

function evalGenerated(source: string): {
  schemas: Record<string, z.ZodType>;
} {
  // Strip TS-only assertions and the `import { z } from 'zod'` line; we
  // supply z and the consts are declared inline by the source body.
  const js = source
    .replace(/^import \{ z \} from 'zod';\n/m, '')
    .replace(/ as `0x\$\{string\}`/g, '');
  // Replace `export const` with `const` so we can collect via locals.
  const noExports = js.replace(/^export const /gm, 'const ');
  // The `as const` cast on the barrel is TS-only.
  const noAsConst = noExports.replace(/\}\s*as\s+const;/g, '};');
  const fn = new Function('z', `${noAsConst}\nreturn schemas;`);
  const schemas = fn(z) as Record<string, z.ZodType>;
  return { schemas };
}

function placeholderForType(type: string, components?: readonly unknown[]): unknown {
  if (type === 'address') return '0x0000000000000000000000000000000000000000';
  if (type === 'bool') return false;
  if (type === 'string') return 'x';
  if (type === 'bytes') return '0x';
  const bm = /^bytes(\d+)$/.exec(type);
  if (bm) return '0x' + 'a'.repeat(2 * Number(bm[1]));
  if (type === 'uint' || /^uint\d+$/.test(type)) return '1';
  if (type === 'int' || /^int\d+$/.test(type)) return '-1';
  const arr = /^(.+)\[(\d*)\]$/.exec(type);
  if (arr) {
    const inner = arr[1]!;
    const n = arr[2] ? Number(arr[2]) : 0;
    return Array.from({ length: n }, () => placeholderForType(inner, components));
  }
  if (type === 'tuple') {
    return (components ?? []).map((c) => {
      const cc = c as { type: string; components?: readonly unknown[] };
      return placeholderForType(cc.type, cc.components);
    });
  }
  throw new Error(`no placeholder for ${type}`);
}

function placeholderForInputs(
  inputs: readonly { type: string; components?: readonly unknown[] }[],
): unknown[] {
  return inputs.map((p) => placeholderForType(p.type, p.components));
}

describe('generate: equivalence with abiToZod', () => {
  const paths = [...walkJson(fixturesRoot)];
  for (const p of paths) {
    const rel = p.slice(fixturesRoot.length + 1);
    it(`fixture ${rel}: generated schemas match runtime parse output`, () => {
      const abi = loadAbi(p);
      const source = generate(abi, basename(p));
      const { schemas } = evalGenerated(source);
      const fns = filterFunctions(abi);
      for (const f of fns) {
        const sig = canonicalSignature(f);
        const generated = schemas[sig];
        expect(generated, `barrel missing signature key ${sig}`).toBeDefined();
        if (!generated) continue;

        let input: unknown[];
        try {
          input = placeholderForInputs(f.inputs);
        } catch {
          // skip functions whose inputs use unsupported types (none expected)
          continue;
        }

        const runtime = abiToZod(abi)[sig];
        expect(runtime, `runtime barrel missing signature key ${sig}`).toBeDefined();
        if (!runtime) continue;
        const a = runtime.safeParse(input);
        const b = generated.safeParse(input);
        expect(b.success, `parse mismatch for ${rel}:${sig}`).toBe(a.success);
        if (a.success && b.success) {
          expect(b.data).toEqual(a.data);
        }
      }
    });
  }
});

describe('generate: header and structure', () => {
  it('emits header with version and source name', () => {
    const abi = [
      {
        type: 'function',
        name: 'foo',
        inputs: [{ type: 'uint256', name: 'x' }],
      },
    ];
    const src = generate(abi as unknown as Abi, 'Foo.json');
    expect(src).toMatch(/^\/\/ Generated by abi-to-zod v.+ from Foo\.json/);
    expect(src).toContain('// Do not edit manually');
    expect(src).toContain(`import { z } from 'zod';`);
  });

  it('falls back to (unnamed) when no source name given', () => {
    const src = generate([], undefined);
    expect(src).toContain('from (unnamed)');
  });

  it('emits per-function export for unambiguous names', () => {
    const abi = [
      {
        type: 'function',
        name: 'transfer',
        inputs: [
          { type: 'address', name: 'to' },
          { type: 'uint256', name: 'value' },
        ],
      },
    ];
    const src = generate(abi as unknown as Abi, 'x');
    expect(src).toContain('export const transferSchema = z.tuple([');
    expect(src).toContain('transfer: transferSchema');
    expect(src).toContain(`'transfer(address,uint256)': transferSchema`);
  });

  it('omits per-function export for overloaded names; inlines in barrel by signature only', () => {
    const abi = [
      {
        type: 'function',
        name: 'safeTransferFrom',
        inputs: [
          { type: 'address', name: 'from' },
          { type: 'address', name: 'to' },
          { type: 'uint256', name: 'tokenId' },
        ],
      },
      {
        type: 'function',
        name: 'safeTransferFrom',
        inputs: [
          { type: 'address', name: 'from' },
          { type: 'address', name: 'to' },
          { type: 'uint256', name: 'tokenId' },
          { type: 'bytes', name: 'data' },
        ],
      },
    ];
    const src = generate(abi as unknown as Abi, 'x');
    expect(src).not.toContain('export const safeTransferFromSchema');
    expect(src).not.toMatch(/^ {2}safeTransferFrom:/m);
    expect(src).toContain(`'safeTransferFrom(address,address,uint256)':`);
    expect(src).toContain(`'safeTransferFrom(address,address,uint256,bytes)':`);
  });

  it('only emits primitive consts that are actually used', () => {
    const abi = [
      {
        type: 'function',
        name: 'pingAddress',
        inputs: [{ type: 'address', name: 'a' }],
      },
    ];
    const src = generate(abi as unknown as Abi, 'x');
    expect(src).toContain('const ADDRESS =');
    expect(src).not.toContain('const UINT256 =');
    expect(src).not.toContain('const BOOL =');
  });

  it('skips non-function entries', () => {
    const abi = [
      { type: 'event', name: 'Transfer', inputs: [{ type: 'address', name: 'a' }] } as never,
      {
        type: 'function',
        name: 'name',
        inputs: [],
      },
    ];
    const src = generate(abi as unknown as Abi, 'x');
    expect(src).toContain('export const nameSchema');
    expect(src).not.toContain('TransferSchema');
  });

  it('is deterministic: same ABI -> identical bytes', () => {
    const abi = [
      {
        type: 'function',
        name: 'foo',
        inputs: [{ type: 'uint256', name: 'a' }],
      },
      {
        type: 'function',
        name: 'bar',
        inputs: [{ type: 'address', name: 'b' }],
      },
    ];
    expect(generate(abi as unknown as Abi, 'x')).toBe(generate(abi as unknown as Abi, 'x'));
  });
});

describe('generate: snapshot small fixtures', () => {
  for (const rel of ['erc/ERC20.json', 'arbitrum/precompiles/ArbInfo.json']) {
    it(`snapshot: ${rel}`, () => {
      const abi = loadAbi(join(fixturesRoot, rel));
      const src = generate(abi, basename(rel));
      expect(src).toMatchSnapshot();
    });
  }
});
