import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { type Abi, canonicalSignature, filterFunctions } from './abi.js';
import {
  type AbiParameter,
  collectPrimitives,
  renderTupleSource,
} from './build.js';
import { primitiveSource, primitiveConstName } from './primitives.js';

let cachedVersion: string | undefined;
function generatorVersion(): string {
  if (cachedVersion !== undefined) return cachedVersion;
  const here = dirname(fileURLToPath(import.meta.url));
  const candidates = [join(here, '..', 'package.json'), join(here, '..', '..', 'package.json')];
  for (const p of candidates) {
    try {
      cachedVersion = String(JSON.parse(readFileSync(p, 'utf8')).version);
      return cachedVersion;
    } catch {
      // try next
    }
  }
  cachedVersion = '0.0.0';
  return cachedVersion;
}

function constNameToBase(name: string): string {
  if (name === 'ADDRESS') return 'address';
  if (name === 'BOOL') return 'bool';
  if (name === 'STRING') return 'string';
  if (name === 'BYTES') return 'bytes';
  const um = /^UINT(\d+)$/.exec(name);
  if (um) return `uint${um[1]}`;
  const im = /^INT(\d+)$/.exec(name);
  if (im) return `int${im[1]}`;
  const bm = /^BYTES(\d+)$/.exec(name);
  if (bm) return `bytes${bm[1]}`;
  throw new Error(`unknown const name ${name}`);
}

export function generate(abi: Abi, sourceName: string = '(unnamed)'): string {
  const functions = filterFunctions(abi);

  const nameCount = new Map<string, number>();
  for (const f of functions) {
    nameCount.set(f.name, (nameCount.get(f.name) ?? 0) + 1);
  }

  const allInputs: AbiParameter[] = [];
  for (const f of functions) allInputs.push(...f.inputs);
  const usedPrims = collectPrimitives(allInputs);

  const sortedFns = functions
    .map((entry) => ({
      entry,
      sig: canonicalSignature(entry),
      overloaded: (nameCount.get(entry.name) ?? 0) > 1,
    }))
    .sort((a, b) => (a.sig < b.sig ? -1 : a.sig > b.sig ? 1 : 0));

  const out: string[] = [];

  out.push(`// Generated by abi-to-zod v${generatorVersion()} from ${sourceName}`);
  out.push('// Do not edit manually -- regenerate from source.');
  out.push('');
  out.push(`import { z } from 'zod';`);
  out.push('');

  if (usedPrims.size > 0) {
    out.push('// === Primitive schemas (edit once to customise all uses) ===');
    out.push('');
    const sortedPrims = [...usedPrims].sort();
    for (const cname of sortedPrims) {
      out.push(`const ${cname} = ${primitiveSource(constNameToBase(cname))};`);
    }
    out.push('');
  }

  if (sortedFns.length > 0) {
    out.push('// === Function schemas ===');
    out.push('');
    for (const { entry, sig, overloaded } of sortedFns) {
      if (overloaded) continue;
      out.push(`// ${sig}`);
      const body = renderTupleSource(entry.inputs, primitiveConstName);
      out.push(`export const ${entry.name}Schema = ${body};`);
      out.push('');
    }
  }

  out.push('// === Lookup barrel (mirrors abiToZod) ===');
  out.push('');
  out.push('export const schemas = {');

  const nameEntries = sortedFns
    .filter((f) => !f.overloaded)
    .map((f) => ({ key: f.entry.name, ref: `${f.entry.name}Schema` }))
    .sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));
  for (const e of nameEntries) {
    out.push(`  ${e.key}: ${e.ref},`);
  }

  const sigEntries = sortedFns
    .map((f) => ({
      key: f.sig,
      ref: f.overloaded
        ? renderTupleSource(f.entry.inputs, primitiveConstName, '  ')
        : `${f.entry.name}Schema`,
    }))
    .sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));
  for (const e of sigEntries) {
    out.push(`  '${e.key}': ${e.ref},`);
  }

  out.push('} as const;');
  out.push('');

  return out.join('\n');
}
