import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { type Abi, planFunctions } from './abi.js';
import {
  type AbiParameter,
  collectPrimitives,
  renderTupleSource,
} from './build.js';
import { primitiveSource, primitiveConstName } from './primitives.js';

let cachedVersion: string | undefined;
function generatorVersion(): string {
  if (cachedVersion !== undefined) return cachedVersion;
  const here = dirname(fileURLToPath(import.meta.url));
  cachedVersion = String(
    JSON.parse(readFileSync(join(here, '..', 'package.json'), 'utf8')).version,
  );
  return cachedVersion;
}

function constNameToBase(name: string): string {
  if (name === 'ADDRESS') return 'address';
  if (name === 'BOOL') return 'bool';
  if (name === 'STRING') return 'string';
  if (name === 'BYTES') return 'bytes';
  const um = /^UINT(\d+)$/.exec(name);
  if (um) return `uint${um[1]}`;
  const im = /^INT(\d+)$/.exec(name);
  if (im) return `int${im[1]}`;
  const bm = /^BYTES(\d+)$/.exec(name);
  if (bm) return `bytes${bm[1]}`;
  throw new Error(`unknown const name ${name}`);
}

export function generate(abi: Abi, sourceName: string = '(unnamed)'): string {
  const plan = planFunctions(abi);

  const allInputs: AbiParameter[] = [];
  for (const { entry } of plan) allInputs.push(...entry.inputs);
  const usedPrims = collectPrimitives(allInputs);

  const sortedFns = [...plan].sort((a, b) =>
    a.signature < b.signature ? -1 : a.signature > b.signature ? 1 : 0,
  );

  const out: string[] = [];

  out.push(`// Generated by abi-to-zod v${generatorVersion()} from ${sourceName}`);
  out.push('// Do not edit manually -- regenerate from source.');
  out.push('');
  out.push(`import { z } from 'zod';`);
  out.push('');

  if (usedPrims.size > 0) {
    out.push('// === Primitive schemas (edit once to customise all uses) ===');
    out.push('');
    const sortedPrims = [...usedPrims].sort();
    for (const cname of sortedPrims) {
      out.push(`const ${cname} = ${primitiveSource(constNameToBase(cname))};`);
    }
    out.push('');
  }

  if (sortedFns.length > 0) {
    out.push('// === Function schemas ===');
    out.push('');
    for (const { entry, signature, overloaded } of sortedFns) {
      if (overloaded) continue;
      out.push(`// ${signature}`);
      const body = renderTupleSource(entry.inputs, primitiveConstName);
      out.push(`export const ${entry.name}Schema = ${body};`);
      out.push('');
    }
  }

  out.push('// === Lookup barrel (mirrors abiToZod) ===');
  out.push('');
  out.push('export const schemas = {');

  const nameEntries = sortedFns
    .filter((f) => !f.overloaded)
    .map((f) => ({ key: f.entry.name, ref: `${f.entry.name}Schema` }))
    .sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));
  for (const e of nameEntries) {
    out.push(`  ${e.key}: ${e.ref},`);
  }

  const sigEntries = sortedFns
    .map((f) => ({
      key: f.signature,
      ref: f.overloaded
        ? renderTupleSource(f.entry.inputs, primitiveConstName, '  ')
        : `${f.entry.name}Schema`,
    }))
    .sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));
  for (const e of sigEntries) {
    out.push(`  '${e.key}': ${e.ref},`);
  }

  out.push('} as const;');
  out.push('');

  return out.join('\n');
}
