import { describe, it, expect } from 'vitest';
import { z } from 'zod';

import { renderSchemas } from './codegen.js';
import { buildSchemas, filterFunctions, canonicalSignature, type Abi } from './abi.js';
import { placeholderFor } from './test-helpers.js';

import { FIXTURES, erc20Abi, arbInfoAbi } from '../test/fixtures/index.js';

function evalGenerated(source: string): {
  schemas: Record<string, z.ZodType>;
} {
  // Strip the import (we inject z below), drop TS-only assertions, and remove
  // `export`/`as const` so the source runs as plain JS and exposes `schemas`.
  const js = source
    .replace(/^import \{ z \} from 'zod';\n/m, '')
    .replace(/ as `0x\$\{string\}`/g, '');
  const noExports = js.replace(/^export const /gm, 'const ');
  const noAsConst = noExports.replace(/\}\s*as\s+const;/g, '};');
  const fn = new Function('z', `${noAsConst}\nreturn schemas;`);
  const schemas = fn(z) as Record<string, z.ZodType>;
  return { schemas };
}

describe('renderSchemas: equivalence with buildSchemas', () => {
  for (const [rel, abi] of Object.entries(FIXTURES)) {
    it(`fixture ${rel}: generated schemas match runtime parse output`, () => {
      const source = renderSchemas(abi, rel.split('/').pop() ?? rel);
      const { schemas } = evalGenerated(source);
      const fns = filterFunctions(abi);
      for (const f of fns) {
        const sig = canonicalSignature(f);
        const generated = schemas[sig];
        expect(generated, `table missing signature key ${sig}`).toBeDefined();
        if (!generated) continue;

        let input: unknown[];
        try {
          input = f.inputs.map(placeholderFor);
        } catch {
          // placeholderFor throws on unsupported types; no fixture hits this today.
          continue;
        }

        const runtime = (buildSchemas(abi) as Record<string, z.ZodType<unknown> | undefined>)[sig];
        expect(runtime, `runtime table missing signature key ${sig}`).toBeDefined();
        if (!runtime) continue;
        const a = runtime.safeParse(input);
        const b = generated.safeParse(input);
        expect(b.success, `parse mismatch for ${rel}:${sig}`).toBe(a.success);
        if (a.success && b.success) {
          expect(b.data).toEqual(a.data);
        }
      }
    });
  }
});

describe('renderSchemas: header and structure', () => {
  it('emits header with version and source name', () => {
    const abi = [
      {
        type: 'function',
        name: 'foo',
        inputs: [{ type: 'uint256', name: 'x' }],
      },
    ];
    const src = renderSchemas(abi as unknown as Abi, 'Foo.json');
    expect(src).toMatch(/^\/\/ Generated by abi-to-zod v.+ from Foo\.json/);
    expect(src).toContain('// Do not edit manually');
    expect(src).toContain(`import { z } from 'zod';`);
  });

  it('falls back to (unnamed) when no source name given', () => {
    const src = renderSchemas([], undefined);
    expect(src).toContain('from (unnamed)');
  });

  it('emits per-function export for unambiguous names', () => {
    const abi = [
      {
        type: 'function',
        name: 'transfer',
        inputs: [
          { type: 'address', name: 'to' },
          { type: 'uint256', name: 'value' },
        ],
      },
    ];
    const src = renderSchemas(abi as unknown as Abi, 'x');
    expect(src).toContain('export const transferSchema = z.tuple([');
    expect(src).toContain('transfer: transferSchema');
    expect(src).toContain(`'transfer(address,uint256)': transferSchema`);
  });

  it('omits per-function export for overloaded names; inlines in table by signature only', () => {
    const abi = [
      {
        type: 'function',
        name: 'safeTransferFrom',
        inputs: [
          { type: 'address', name: 'from' },
          { type: 'address', name: 'to' },
          { type: 'uint256', name: 'tokenId' },
        ],
      },
      {
        type: 'function',
        name: 'safeTransferFrom',
        inputs: [
          { type: 'address', name: 'from' },
          { type: 'address', name: 'to' },
          { type: 'uint256', name: 'tokenId' },
          { type: 'bytes', name: 'data' },
        ],
      },
    ];
    const src = renderSchemas(abi as unknown as Abi, 'x');
    expect(src).not.toContain('export const safeTransferFromSchema');
    expect(src).not.toMatch(/^ {2}safeTransferFrom:/m);
    expect(src).toContain(`'safeTransferFrom(address,address,uint256)':`);
    expect(src).toContain(`'safeTransferFrom(address,address,uint256,bytes)':`);
  });

  it('only emits primitive consts that are actually used', () => {
    const abi = [
      {
        type: 'function',
        name: 'pingAddress',
        inputs: [{ type: 'address', name: 'a' }],
      },
    ];
    const src = renderSchemas(abi as unknown as Abi, 'x');
    expect(src).toContain('const ADDRESS =');
    expect(src).not.toContain('const UINT256 =');
    expect(src).not.toContain('const BOOL =');
  });

  it('skips non-function entries', () => {
    const abi = [
      { type: 'event', name: 'Transfer', inputs: [{ type: 'address', name: 'a' }] } as never,
      {
        type: 'function',
        name: 'name',
        inputs: [],
      },
    ];
    const src = renderSchemas(abi as unknown as Abi, 'x');
    expect(src).toContain('export const nameSchema');
    expect(src).not.toContain('TransferSchema');
  });

  it('is deterministic: same ABI -> identical bytes', () => {
    const abi = [
      {
        type: 'function',
        name: 'foo',
        inputs: [{ type: 'uint256', name: 'a' }],
      },
      {
        type: 'function',
        name: 'bar',
        inputs: [{ type: 'address', name: 'b' }],
      },
    ];
    expect(renderSchemas(abi as unknown as Abi, 'x')).toBe(renderSchemas(abi as unknown as Abi, 'x'));
  });
});

describe('renderSchemas: snapshot small fixtures', () => {
  const small: ReadonlyArray<readonly [string, Abi]> = [
    ['erc/ERC20.ts', erc20Abi],
    ['arbitrum/precompiles/ArbInfo.ts', arbInfoAbi],
  ];
  for (const [rel, abi] of small) {
    it(`snapshot: ${rel}`, () => {
      const src = renderSchemas(abi, rel.split('/').pop() ?? rel);
      expect(src).toMatchSnapshot();
    });
  }
});
