import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { parseType } from './type-parser.js';
import { primitiveConstName, primitiveSource } from './primitives.js';
import {
  type RawAbiParameter,
  BuildSchemaError,
  canonicalType,
  pickNamedComponents,
} from './build.js';
import { type Abi, planFunctions } from './schemas.js';

export type PrimitiveResolver = (base: string) => string;

let cachedVersion: string | undefined;
function generatorVersion(): string {
  if (cachedVersion !== undefined) return cachedVersion;
  const here = dirname(fileURLToPath(import.meta.url));
  cachedVersion = String(
    JSON.parse(readFileSync(join(here, '..', 'package.json'), 'utf8')).version,
  );
  return cachedVersion;
}

function constNameToBase(name: string): string {
  if (name === 'ADDRESS') return 'address';
  if (name === 'BOOL') return 'bool';
  if (name === 'STRING') return 'string';
  if (name === 'BYTES') return 'bytes';
  const um = /^UINT(\d+)$/.exec(name);
  if (um) return `uint${um[1]}`;
  const im = /^INT(\d+)$/.exec(name);
  if (im) return `int${im[1]}`;
  const bm = /^BYTES(\d+)$/.exec(name);
  if (bm) return `bytes${bm[1]}`;
  throw new Error(`unknown const name ${name}`);
}

export function renderSchemas(abi: Abi): string {
  const plan = planFunctions(abi);

  const allInputs: RawAbiParameter[] = [];
  for (const { entry } of plan) allInputs.push(...entry.inputs);
  const usedPrims = collectPrimitives(allInputs);

  const sortedFns = [...plan].sort((a, b) =>
    a.signature < b.signature ? -1 : a.signature > b.signature ? 1 : 0,
  );

  const out: string[] = [];

  out.push(`// Generated by abi-to-zod@${generatorVersion()}`);
  out.push('');
  out.push(`import { z } from 'zod';`);
  out.push('');

  if (usedPrims.size > 0) {
    out.push('// === Primitive schemas ===');
    out.push('');
    const sortedPrims = [...usedPrims].sort();
    for (const cname of sortedPrims) {
      out.push(`const ${cname} = ${primitiveSource(constNameToBase(cname))};`);
    }
    out.push('');
  }

  if (sortedFns.length > 0) {
    out.push('// === Function schemas ===');
    out.push('');
    for (const { entry, signature, overloaded } of sortedFns) {
      if (overloaded) continue;
      out.push(`// ${signature}`);
      const body = renderTupleSchema(entry.inputs, primitiveConstName);
      out.push(`export const ${entry.name}Schema = ${body};`);
      out.push('');
    }
  }

  out.push('// === Schema table ===');
  out.push('');
  out.push('export const schemas = {');

  const nameEntries = sortedFns
    .filter((f) => !f.overloaded)
    .map((f) => ({ key: f.entry.name, ref: `${f.entry.name}Schema` }))
    .sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));
  for (const e of nameEntries) {
    out.push(`  ${e.key}: ${e.ref},`);
  }

  const sigEntries = sortedFns
    .map((f) => ({
      key: f.signature,
      ref: f.overloaded
        ? renderTupleSchema(f.entry.inputs, primitiveConstName, '  ')
        : `${f.entry.name}Schema`,
    }))
    .sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));
  for (const e of sigEntries) {
    out.push(`  '${e.key}': ${e.ref},`);
  }

  out.push('} as const;');
  out.push('');

  return out.join('\n');
}

function commentFor(param: RawAbiParameter): string {
  const sig = canonicalType(param);
  const name = param.name ?? '';
  return name ? `/* ${name}: ${sig} */ ` : `/* ${sig} */ `;
}

export function renderParamSchema(
  param: RawAbiParameter,
  resolver: PrimitiveResolver,
  indent: string = '',
  path: readonly string[] = [],
): string {
  try {
    const { base, suffixes } = parseType(param.type);
    let expr: string;
    if (base === 'tuple') {
      if (!param.components) {
        throw new Error(`tuple type missing 'components'`);
      }
      const named = pickNamedComponents(param.components);
      expr = named
        ? renderObjectSchema(named, resolver, indent, path)
        : renderTupleSchema(param.components, resolver, indent, path);
    } else {
      expr = resolver(base);
    }
    for (const suffix of suffixes) {
      expr = suffix === null ? `z.array(${expr})` : `z.array(${expr}).length(${suffix})`;
    }
    return expr;
  } catch (err) {
    if (err instanceof BuildSchemaError) throw err;
    const where = path.length > 0 ? path.join('.') : '<root>';
    const inner = err instanceof Error ? err.message : String(err);
    throw new BuildSchemaError(
      `Failed to render schema at ${where} (type=${JSON.stringify(param.type)}, name=${JSON.stringify(param.name ?? '')}): ${inner}`,
      { cause: err },
    );
  }
}

export function renderTupleSchema(
  params: readonly RawAbiParameter[],
  resolver: PrimitiveResolver,
  indent: string = '',
  path: readonly string[] = [],
): string {
  if (params.length === 0) return 'z.tuple([])';
  const childIndent = indent + '  ';
  const items = params.map((p, i) => {
    const expr = renderParamSchema(p, resolver, childIndent, [...path, `components[${i}]`]);
    return `${childIndent}${commentFor(p)}${expr},`;
  });
  return `z.tuple([\n${items.join('\n')}\n${indent}])`;
}

export function renderObjectSchema(
  named: readonly (readonly [string, RawAbiParameter])[],
  resolver: PrimitiveResolver,
  indent: string = '',
  path: readonly string[] = [],
): string {
  const childIndent = indent + '  ';
  const items = named.map(([name, param], i) => {
    const expr = renderParamSchema(param, resolver, childIndent, [...path, `components[${i}]`]);
    return `${childIndent}${name}: ${expr},`;
  });
  return `z.strictObject({\n${items.join('\n')}\n${indent}})`;
}

export function collectPrimitives(params: readonly RawAbiParameter[]): Set<string> {
  const used = new Set<string>();
  for (const p of params) walkParam(p, used);
  return used;
}

function walkParam(param: RawAbiParameter, used: Set<string>): void {
  const { base } = parseType(param.type);
  if (base === 'tuple') {
    for (const c of param.components ?? []) walkParam(c, used);
  } else {
    used.add(primitiveConstName(base));
  }
}
