// Generated by abi-to-zod v0.0.0 from Seaport.json
// Do not edit manually -- regenerate from source.

import { z } from 'zod';

// === Primitive schemas (edit once to customise all uses) ===

const ADDRESS = z.string().regex(/^0x[0-9a-fA-F]{40}$/).transform((v) => v as `0x${string}`);
const BYTES = z.string().regex(/^0x([0-9a-fA-F]{2})*$/).transform((v) => v as `0x${string}`);
const BYTES32 = z.string().regex(/^0x[0-9a-fA-F]{64}$/).transform((v) => v as `0x${string}`);
const UINT120 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 120n) - 1n);
const UINT256 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 256n) - 1n);
const UINT8 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 8n) - 1n);

// === Function schemas ===

// __activateTstore()
export const __activateTstoreSchema = z.tuple([]);

// cancel((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256)[])
export const cancelSchema = z.tuple([
  /* orders: (address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256)[] */ z.array(z.tuple([
    /* offerer: address */ ADDRESS,
    /* zone: address */ ADDRESS,
    /* offer: (uint8,address,uint256,uint256,uint256)[] */ z.array(z.tuple([
      /* itemType: uint8 */ UINT8,
      /* token: address */ ADDRESS,
      /* identifierOrCriteria: uint256 */ UINT256,
      /* startAmount: uint256 */ UINT256,
      /* endAmount: uint256 */ UINT256,
    ])),
    /* consideration: (uint8,address,uint256,uint256,uint256,address)[] */ z.array(z.tuple([
      /* itemType: uint8 */ UINT8,
      /* token: address */ ADDRESS,
      /* identifierOrCriteria: uint256 */ UINT256,
      /* startAmount: uint256 */ UINT256,
      /* endAmount: uint256 */ UINT256,
      /* recipient: address */ ADDRESS,
    ])),
    /* orderType: uint8 */ UINT8,
    /* startTime: uint256 */ UINT256,
    /* endTime: uint256 */ UINT256,
    /* zoneHash: bytes32 */ BYTES32,
    /* salt: uint256 */ UINT256,
    /* conduitKey: bytes32 */ BYTES32,
    /* counter: uint256 */ UINT256,
  ])),
]);

// fulfillAdvancedOrder(((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),uint120,uint120,bytes,bytes),(uint256,uint8,uint256,uint256,bytes32[])[],bytes32,address)
export const fulfillAdvancedOrderSchema = z.tuple([
  /* ((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),uint120,uint120,bytes,bytes) */ z.tuple([
    /* parameters: (address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256) */ z.tuple([
      /* offerer: address */ ADDRESS,
      /* zone: address */ ADDRESS,
      /* offer: (uint8,address,uint256,uint256,uint256)[] */ z.array(z.tuple([
        /* itemType: uint8 */ UINT8,
        /* token: address */ ADDRESS,
        /* identifierOrCriteria: uint256 */ UINT256,
        /* startAmount: uint256 */ UINT256,
        /* endAmount: uint256 */ UINT256,
      ])),
      /* consideration: (uint8,address,uint256,uint256,uint256,address)[] */ z.array(z.tuple([
        /* itemType: uint8 */ UINT8,
        /* token: address */ ADDRESS,
        /* identifierOrCriteria: uint256 */ UINT256,
        /* startAmount: uint256 */ UINT256,
        /* endAmount: uint256 */ UINT256,
        /* recipient: address */ ADDRESS,
      ])),
      /* orderType: uint8 */ UINT8,
      /* startTime: uint256 */ UINT256,
      /* endTime: uint256 */ UINT256,
      /* zoneHash: bytes32 */ BYTES32,
      /* salt: uint256 */ UINT256,
      /* conduitKey: bytes32 */ BYTES32,
      /* totalOriginalConsiderationItems: uint256 */ UINT256,
    ]),
    /* numerator: uint120 */ UINT120,
    /* denominator: uint120 */ UINT120,
    /* signature: bytes */ BYTES,
    /* extraData: bytes */ BYTES,
  ]),
  /* (uint256,uint8,uint256,uint256,bytes32[])[] */ z.array(z.tuple([
    /* orderIndex: uint256 */ UINT256,
    /* side: uint8 */ UINT8,
    /* index: uint256 */ UINT256,
    /* identifier: uint256 */ UINT256,
    /* criteriaProof: bytes32[] */ z.array(BYTES32),
  ])),
  /* fulfillerConduitKey: bytes32 */ BYTES32,
  /* recipient: address */ ADDRESS,
]);

// fulfillAvailableAdvancedOrders(((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),uint120,uint120,bytes,bytes)[],(uint256,uint8,uint256,uint256,bytes32[])[],(uint256,uint256)[][],(uint256,uint256)[][],bytes32,address,uint256)
export const fulfillAvailableAdvancedOrdersSchema = z.tuple([
  /* ((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),uint120,uint120,bytes,bytes)[] */ z.array(z.tuple([
    /* parameters: (address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256) */ z.tuple([
      /* offerer: address */ ADDRESS,
      /* zone: address */ ADDRESS,
      /* offer: (uint8,address,uint256,uint256,uint256)[] */ z.array(z.tuple([
        /* itemType: uint8 */ UINT8,
        /* token: address */ ADDRESS,
        /* identifierOrCriteria: uint256 */ UINT256,
        /* startAmount: uint256 */ UINT256,
        /* endAmount: uint256 */ UINT256,
      ])),
      /* consideration: (uint8,address,uint256,uint256,uint256,address)[] */ z.array(z.tuple([
        /* itemType: uint8 */ UINT8,
        /* token: address */ ADDRESS,
        /* identifierOrCriteria: uint256 */ UINT256,
        /* startAmount: uint256 */ UINT256,
        /* endAmount: uint256 */ UINT256,
        /* recipient: address */ ADDRESS,
      ])),
      /* orderType: uint8 */ UINT8,
      /* startTime: uint256 */ UINT256,
      /* endTime: uint256 */ UINT256,
      /* zoneHash: bytes32 */ BYTES32,
      /* salt: uint256 */ UINT256,
      /* conduitKey: bytes32 */ BYTES32,
      /* totalOriginalConsiderationItems: uint256 */ UINT256,
    ]),
    /* numerator: uint120 */ UINT120,
    /* denominator: uint120 */ UINT120,
    /* signature: bytes */ BYTES,
    /* extraData: bytes */ BYTES,
  ])),
  /* (uint256,uint8,uint256,uint256,bytes32[])[] */ z.array(z.tuple([
    /* orderIndex: uint256 */ UINT256,
    /* side: uint8 */ UINT8,
    /* index: uint256 */ UINT256,
    /* identifier: uint256 */ UINT256,
    /* criteriaProof: bytes32[] */ z.array(BYTES32),
  ])),
  /* (uint256,uint256)[][] */ z.array(z.array(z.tuple([
    /* orderIndex: uint256 */ UINT256,
    /* itemIndex: uint256 */ UINT256,
  ]))),
  /* (uint256,uint256)[][] */ z.array(z.array(z.tuple([
    /* orderIndex: uint256 */ UINT256,
    /* itemIndex: uint256 */ UINT256,
  ]))),
  /* fulfillerConduitKey: bytes32 */ BYTES32,
  /* recipient: address */ ADDRESS,
  /* maximumFulfilled: uint256 */ UINT256,
]);

// fulfillAvailableOrders(((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),bytes)[],(uint256,uint256)[][],(uint256,uint256)[][],bytes32,uint256)
export const fulfillAvailableOrdersSchema = z.tuple([
  /* ((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),bytes)[] */ z.array(z.tuple([
    /* parameters: (address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256) */ z.tuple([
      /* offerer: address */ ADDRESS,
      /* zone: address */ ADDRESS,
      /* offer: (uint8,address,uint256,uint256,uint256)[] */ z.array(z.tuple([
        /* itemType: uint8 */ UINT8,
        /* token: address */ ADDRESS,
        /* identifierOrCriteria: uint256 */ UINT256,
        /* startAmount: uint256 */ UINT256,
        /* endAmount: uint256 */ UINT256,
      ])),
      /* consideration: (uint8,address,uint256,uint256,uint256,address)[] */ z.array(z.tuple([
        /* itemType: uint8 */ UINT8,
        /* token: address */ ADDRESS,
        /* identifierOrCriteria: uint256 */ UINT256,
        /* startAmount: uint256 */ UINT256,
        /* endAmount: uint256 */ UINT256,
        /* recipient: address */ ADDRESS,
      ])),
      /* orderType: uint8 */ UINT8,
      /* startTime: uint256 */ UINT256,
      /* endTime: uint256 */ UINT256,
      /* zoneHash: bytes32 */ BYTES32,
      /* salt: uint256 */ UINT256,
      /* conduitKey: bytes32 */ BYTES32,
      /* totalOriginalConsiderationItems: uint256 */ UINT256,
    ]),
    /* signature: bytes */ BYTES,
  ])),
  /* (uint256,uint256)[][] */ z.array(z.array(z.tuple([
    /* orderIndex: uint256 */ UINT256,
    /* itemIndex: uint256 */ UINT256,
  ]))),
  /* (uint256,uint256)[][] */ z.array(z.array(z.tuple([
    /* orderIndex: uint256 */ UINT256,
    /* itemIndex: uint256 */ UINT256,
  ]))),
  /* fulfillerConduitKey: bytes32 */ BYTES32,
  /* maximumFulfilled: uint256 */ UINT256,
]);

// fulfillBasicOrder((address,uint256,uint256,address,address,address,uint256,uint256,uint8,uint256,uint256,bytes32,uint256,bytes32,bytes32,uint256,(uint256,address)[],bytes))
export const fulfillBasicOrderSchema = z.tuple([
  /* (address,uint256,uint256,address,address,address,uint256,uint256,uint8,uint256,uint256,bytes32,uint256,bytes32,bytes32,uint256,(uint256,address)[],bytes) */ z.tuple([
    /* considerationToken: address */ ADDRESS,
    /* considerationIdentifier: uint256 */ UINT256,
    /* considerationAmount: uint256 */ UINT256,
    /* offerer: address */ ADDRESS,
    /* zone: address */ ADDRESS,
    /* offerToken: address */ ADDRESS,
    /* offerIdentifier: uint256 */ UINT256,
    /* offerAmount: uint256 */ UINT256,
    /* basicOrderType: uint8 */ UINT8,
    /* startTime: uint256 */ UINT256,
    /* endTime: uint256 */ UINT256,
    /* zoneHash: bytes32 */ BYTES32,
    /* salt: uint256 */ UINT256,
    /* offererConduitKey: bytes32 */ BYTES32,
    /* fulfillerConduitKey: bytes32 */ BYTES32,
    /* totalOriginalAdditionalRecipients: uint256 */ UINT256,
    /* additionalRecipients: (uint256,address)[] */ z.array(z.tuple([
      /* amount: uint256 */ UINT256,
      /* recipient: address */ ADDRESS,
    ])),
    /* signature: bytes */ BYTES,
  ]),
]);

// fulfillBasicOrder_efficient_6GL6yc((address,uint256,uint256,address,address,address,uint256,uint256,uint8,uint256,uint256,bytes32,uint256,bytes32,bytes32,uint256,(uint256,address)[],bytes))
export const fulfillBasicOrder_efficient_6GL6ycSchema = z.tuple([
  /* (address,uint256,uint256,address,address,address,uint256,uint256,uint8,uint256,uint256,bytes32,uint256,bytes32,bytes32,uint256,(uint256,address)[],bytes) */ z.tuple([
    /* considerationToken: address */ ADDRESS,
    /* considerationIdentifier: uint256 */ UINT256,
    /* considerationAmount: uint256 */ UINT256,
    /* offerer: address */ ADDRESS,
    /* zone: address */ ADDRESS,
    /* offerToken: address */ ADDRESS,
    /* offerIdentifier: uint256 */ UINT256,
    /* offerAmount: uint256 */ UINT256,
    /* basicOrderType: uint8 */ UINT8,
    /* startTime: uint256 */ UINT256,
    /* endTime: uint256 */ UINT256,
    /* zoneHash: bytes32 */ BYTES32,
    /* salt: uint256 */ UINT256,
    /* offererConduitKey: bytes32 */ BYTES32,
    /* fulfillerConduitKey: bytes32 */ BYTES32,
    /* totalOriginalAdditionalRecipients: uint256 */ UINT256,
    /* additionalRecipients: (uint256,address)[] */ z.array(z.tuple([
      /* amount: uint256 */ UINT256,
      /* recipient: address */ ADDRESS,
    ])),
    /* signature: bytes */ BYTES,
  ]),
]);

// fulfillOrder(((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),bytes),bytes32)
export const fulfillOrderSchema = z.tuple([
  /* ((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),bytes) */ z.tuple([
    /* parameters: (address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256) */ z.tuple([
      /* offerer: address */ ADDRESS,
      /* zone: address */ ADDRESS,
      /* offer: (uint8,address,uint256,uint256,uint256)[] */ z.array(z.tuple([
        /* itemType: uint8 */ UINT8,
        /* token: address */ ADDRESS,
        /* identifierOrCriteria: uint256 */ UINT256,
        /* startAmount: uint256 */ UINT256,
        /* endAmount: uint256 */ UINT256,
      ])),
      /* consideration: (uint8,address,uint256,uint256,uint256,address)[] */ z.array(z.tuple([
        /* itemType: uint8 */ UINT8,
        /* token: address */ ADDRESS,
        /* identifierOrCriteria: uint256 */ UINT256,
        /* startAmount: uint256 */ UINT256,
        /* endAmount: uint256 */ UINT256,
        /* recipient: address */ ADDRESS,
      ])),
      /* orderType: uint8 */ UINT8,
      /* startTime: uint256 */ UINT256,
      /* endTime: uint256 */ UINT256,
      /* zoneHash: bytes32 */ BYTES32,
      /* salt: uint256 */ UINT256,
      /* conduitKey: bytes32 */ BYTES32,
      /* totalOriginalConsiderationItems: uint256 */ UINT256,
    ]),
    /* signature: bytes */ BYTES,
  ]),
  /* fulfillerConduitKey: bytes32 */ BYTES32,
]);

// getContractOffererNonce(address)
export const getContractOffererNonceSchema = z.tuple([
  /* contractOfferer: address */ ADDRESS,
]);

// getCounter(address)
export const getCounterSchema = z.tuple([
  /* offerer: address */ ADDRESS,
]);

// getOrderHash((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256))
export const getOrderHashSchema = z.tuple([
  /* (address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256) */ z.tuple([
    /* offerer: address */ ADDRESS,
    /* zone: address */ ADDRESS,
    /* offer: (uint8,address,uint256,uint256,uint256)[] */ z.array(z.tuple([
      /* itemType: uint8 */ UINT8,
      /* token: address */ ADDRESS,
      /* identifierOrCriteria: uint256 */ UINT256,
      /* startAmount: uint256 */ UINT256,
      /* endAmount: uint256 */ UINT256,
    ])),
    /* consideration: (uint8,address,uint256,uint256,uint256,address)[] */ z.array(z.tuple([
      /* itemType: uint8 */ UINT8,
      /* token: address */ ADDRESS,
      /* identifierOrCriteria: uint256 */ UINT256,
      /* startAmount: uint256 */ UINT256,
      /* endAmount: uint256 */ UINT256,
      /* recipient: address */ ADDRESS,
    ])),
    /* orderType: uint8 */ UINT8,
    /* startTime: uint256 */ UINT256,
    /* endTime: uint256 */ UINT256,
    /* zoneHash: bytes32 */ BYTES32,
    /* salt: uint256 */ UINT256,
    /* conduitKey: bytes32 */ BYTES32,
    /* counter: uint256 */ UINT256,
  ]),
]);

// getOrderStatus(bytes32)
export const getOrderStatusSchema = z.tuple([
  /* orderHash: bytes32 */ BYTES32,
]);

// incrementCounter()
export const incrementCounterSchema = z.tuple([]);

// information()
export const informationSchema = z.tuple([]);

// matchAdvancedOrders(((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),uint120,uint120,bytes,bytes)[],(uint256,uint8,uint256,uint256,bytes32[])[],((uint256,uint256)[],(uint256,uint256)[])[],address)
export const matchAdvancedOrdersSchema = z.tuple([
  /* ((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),uint120,uint120,bytes,bytes)[] */ z.array(z.tuple([
    /* parameters: (address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256) */ z.tuple([
      /* offerer: address */ ADDRESS,
      /* zone: address */ ADDRESS,
      /* offer: (uint8,address,uint256,uint256,uint256)[] */ z.array(z.tuple([
        /* itemType: uint8 */ UINT8,
        /* token: address */ ADDRESS,
        /* identifierOrCriteria: uint256 */ UINT256,
        /* startAmount: uint256 */ UINT256,
        /* endAmount: uint256 */ UINT256,
      ])),
      /* consideration: (uint8,address,uint256,uint256,uint256,address)[] */ z.array(z.tuple([
        /* itemType: uint8 */ UINT8,
        /* token: address */ ADDRESS,
        /* identifierOrCriteria: uint256 */ UINT256,
        /* startAmount: uint256 */ UINT256,
        /* endAmount: uint256 */ UINT256,
        /* recipient: address */ ADDRESS,
      ])),
      /* orderType: uint8 */ UINT8,
      /* startTime: uint256 */ UINT256,
      /* endTime: uint256 */ UINT256,
      /* zoneHash: bytes32 */ BYTES32,
      /* salt: uint256 */ UINT256,
      /* conduitKey: bytes32 */ BYTES32,
      /* totalOriginalConsiderationItems: uint256 */ UINT256,
    ]),
    /* numerator: uint120 */ UINT120,
    /* denominator: uint120 */ UINT120,
    /* signature: bytes */ BYTES,
    /* extraData: bytes */ BYTES,
  ])),
  /* (uint256,uint8,uint256,uint256,bytes32[])[] */ z.array(z.tuple([
    /* orderIndex: uint256 */ UINT256,
    /* side: uint8 */ UINT8,
    /* index: uint256 */ UINT256,
    /* identifier: uint256 */ UINT256,
    /* criteriaProof: bytes32[] */ z.array(BYTES32),
  ])),
  /* ((uint256,uint256)[],(uint256,uint256)[])[] */ z.array(z.tuple([
    /* offerComponents: (uint256,uint256)[] */ z.array(z.tuple([
      /* orderIndex: uint256 */ UINT256,
      /* itemIndex: uint256 */ UINT256,
    ])),
    /* considerationComponents: (uint256,uint256)[] */ z.array(z.tuple([
      /* orderIndex: uint256 */ UINT256,
      /* itemIndex: uint256 */ UINT256,
    ])),
  ])),
  /* recipient: address */ ADDRESS,
]);

// matchOrders(((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),bytes)[],((uint256,uint256)[],(uint256,uint256)[])[])
export const matchOrdersSchema = z.tuple([
  /* ((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),bytes)[] */ z.array(z.tuple([
    /* parameters: (address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256) */ z.tuple([
      /* offerer: address */ ADDRESS,
      /* zone: address */ ADDRESS,
      /* offer: (uint8,address,uint256,uint256,uint256)[] */ z.array(z.tuple([
        /* itemType: uint8 */ UINT8,
        /* token: address */ ADDRESS,
        /* identifierOrCriteria: uint256 */ UINT256,
        /* startAmount: uint256 */ UINT256,
        /* endAmount: uint256 */ UINT256,
      ])),
      /* consideration: (uint8,address,uint256,uint256,uint256,address)[] */ z.array(z.tuple([
        /* itemType: uint8 */ UINT8,
        /* token: address */ ADDRESS,
        /* identifierOrCriteria: uint256 */ UINT256,
        /* startAmount: uint256 */ UINT256,
        /* endAmount: uint256 */ UINT256,
        /* recipient: address */ ADDRESS,
      ])),
      /* orderType: uint8 */ UINT8,
      /* startTime: uint256 */ UINT256,
      /* endTime: uint256 */ UINT256,
      /* zoneHash: bytes32 */ BYTES32,
      /* salt: uint256 */ UINT256,
      /* conduitKey: bytes32 */ BYTES32,
      /* totalOriginalConsiderationItems: uint256 */ UINT256,
    ]),
    /* signature: bytes */ BYTES,
  ])),
  /* ((uint256,uint256)[],(uint256,uint256)[])[] */ z.array(z.tuple([
    /* offerComponents: (uint256,uint256)[] */ z.array(z.tuple([
      /* orderIndex: uint256 */ UINT256,
      /* itemIndex: uint256 */ UINT256,
    ])),
    /* considerationComponents: (uint256,uint256)[] */ z.array(z.tuple([
      /* orderIndex: uint256 */ UINT256,
      /* itemIndex: uint256 */ UINT256,
    ])),
  ])),
]);

// name()
export const nameSchema = z.tuple([]);

// validate(((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),bytes)[])
export const validateSchema = z.tuple([
  /* ((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),bytes)[] */ z.array(z.tuple([
    /* parameters: (address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256) */ z.tuple([
      /* offerer: address */ ADDRESS,
      /* zone: address */ ADDRESS,
      /* offer: (uint8,address,uint256,uint256,uint256)[] */ z.array(z.tuple([
        /* itemType: uint8 */ UINT8,
        /* token: address */ ADDRESS,
        /* identifierOrCriteria: uint256 */ UINT256,
        /* startAmount: uint256 */ UINT256,
        /* endAmount: uint256 */ UINT256,
      ])),
      /* consideration: (uint8,address,uint256,uint256,uint256,address)[] */ z.array(z.tuple([
        /* itemType: uint8 */ UINT8,
        /* token: address */ ADDRESS,
        /* identifierOrCriteria: uint256 */ UINT256,
        /* startAmount: uint256 */ UINT256,
        /* endAmount: uint256 */ UINT256,
        /* recipient: address */ ADDRESS,
      ])),
      /* orderType: uint8 */ UINT8,
      /* startTime: uint256 */ UINT256,
      /* endTime: uint256 */ UINT256,
      /* zoneHash: bytes32 */ BYTES32,
      /* salt: uint256 */ UINT256,
      /* conduitKey: bytes32 */ BYTES32,
      /* totalOriginalConsiderationItems: uint256 */ UINT256,
    ]),
    /* signature: bytes */ BYTES,
  ])),
]);

// === Lookup barrel (mirrors abiToZod) ===

export const schemas = {
  __activateTstore: __activateTstoreSchema,
  cancel: cancelSchema,
  fulfillAdvancedOrder: fulfillAdvancedOrderSchema,
  fulfillAvailableAdvancedOrders: fulfillAvailableAdvancedOrdersSchema,
  fulfillAvailableOrders: fulfillAvailableOrdersSchema,
  fulfillBasicOrder: fulfillBasicOrderSchema,
  fulfillBasicOrder_efficient_6GL6yc: fulfillBasicOrder_efficient_6GL6ycSchema,
  fulfillOrder: fulfillOrderSchema,
  getContractOffererNonce: getContractOffererNonceSchema,
  getCounter: getCounterSchema,
  getOrderHash: getOrderHashSchema,
  getOrderStatus: getOrderStatusSchema,
  incrementCounter: incrementCounterSchema,
  information: informationSchema,
  matchAdvancedOrders: matchAdvancedOrdersSchema,
  matchOrders: matchOrdersSchema,
  name: nameSchema,
  validate: validateSchema,
  '__activateTstore()': __activateTstoreSchema,
  'cancel((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256)[])': cancelSchema,
  'fulfillAdvancedOrder(((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),uint120,uint120,bytes,bytes),(uint256,uint8,uint256,uint256,bytes32[])[],bytes32,address)': fulfillAdvancedOrderSchema,
  'fulfillAvailableAdvancedOrders(((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),uint120,uint120,bytes,bytes)[],(uint256,uint8,uint256,uint256,bytes32[])[],(uint256,uint256)[][],(uint256,uint256)[][],bytes32,address,uint256)': fulfillAvailableAdvancedOrdersSchema,
  'fulfillAvailableOrders(((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),bytes)[],(uint256,uint256)[][],(uint256,uint256)[][],bytes32,uint256)': fulfillAvailableOrdersSchema,
  'fulfillBasicOrder((address,uint256,uint256,address,address,address,uint256,uint256,uint8,uint256,uint256,bytes32,uint256,bytes32,bytes32,uint256,(uint256,address)[],bytes))': fulfillBasicOrderSchema,
  'fulfillBasicOrder_efficient_6GL6yc((address,uint256,uint256,address,address,address,uint256,uint256,uint8,uint256,uint256,bytes32,uint256,bytes32,bytes32,uint256,(uint256,address)[],bytes))': fulfillBasicOrder_efficient_6GL6ycSchema,
  'fulfillOrder(((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),bytes),bytes32)': fulfillOrderSchema,
  'getContractOffererNonce(address)': getContractOffererNonceSchema,
  'getCounter(address)': getCounterSchema,
  'getOrderHash((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256))': getOrderHashSchema,
  'getOrderStatus(bytes32)': getOrderStatusSchema,
  'incrementCounter()': incrementCounterSchema,
  'information()': informationSchema,
  'matchAdvancedOrders(((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),uint120,uint120,bytes,bytes)[],(uint256,uint8,uint256,uint256,bytes32[])[],((uint256,uint256)[],(uint256,uint256)[])[],address)': matchAdvancedOrdersSchema,
  'matchOrders(((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),bytes)[],((uint256,uint256)[],(uint256,uint256)[])[])': matchOrdersSchema,
  'name()': nameSchema,
  'validate(((address,address,(uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint8,uint256,uint256,bytes32,uint256,bytes32,uint256),bytes)[])': validateSchema,
} as const;
