// Generated by abi-to-zod v0.0.0 from UniswapV3SwapRouter.json
// Do not edit manually -- regenerate from source.

import { z } from 'zod';

// === Primitive schemas (edit once to customise all uses) ===

const ADDRESS = z.string().regex(/^0x[0-9a-fA-F]{40}$/).transform((v) => v as `0x${string}`);
const BYTES = z.string().regex(/^0x([0-9a-fA-F]{2})*$/).transform((v) => v as `0x${string}`);
const BYTES32 = z.string().regex(/^0x[0-9a-fA-F]{64}$/).transform((v) => v as `0x${string}`);
const INT256 = z.string().regex(/^-?\d+$/).transform((v) => BigInt(v)).refine((n) => n >= -(1n << 255n) && n <= (1n << 255n) - 1n);
const UINT160 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 160n) - 1n);
const UINT24 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 24n) - 1n);
const UINT256 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 256n) - 1n);
const UINT8 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 8n) - 1n);

// === Function schemas ===

// WETH9()
export const WETH9Schema = z.tuple([]);

// exactInput((bytes,address,uint256,uint256,uint256))
export const exactInputSchema = z.tuple([
  /* params: (bytes,address,uint256,uint256,uint256) */ z.tuple([
    /* path: bytes */ BYTES,
    /* recipient: address */ ADDRESS,
    /* deadline: uint256 */ UINT256,
    /* amountIn: uint256 */ UINT256,
    /* amountOutMinimum: uint256 */ UINT256,
  ]),
]);

// exactInputSingle((address,address,uint24,address,uint256,uint256,uint256,uint160))
export const exactInputSingleSchema = z.tuple([
  /* params: (address,address,uint24,address,uint256,uint256,uint256,uint160) */ z.tuple([
    /* tokenIn: address */ ADDRESS,
    /* tokenOut: address */ ADDRESS,
    /* fee: uint24 */ UINT24,
    /* recipient: address */ ADDRESS,
    /* deadline: uint256 */ UINT256,
    /* amountIn: uint256 */ UINT256,
    /* amountOutMinimum: uint256 */ UINT256,
    /* sqrtPriceLimitX96: uint160 */ UINT160,
  ]),
]);

// exactOutput((bytes,address,uint256,uint256,uint256))
export const exactOutputSchema = z.tuple([
  /* params: (bytes,address,uint256,uint256,uint256) */ z.tuple([
    /* path: bytes */ BYTES,
    /* recipient: address */ ADDRESS,
    /* deadline: uint256 */ UINT256,
    /* amountOut: uint256 */ UINT256,
    /* amountInMaximum: uint256 */ UINT256,
  ]),
]);

// exactOutputSingle((address,address,uint24,address,uint256,uint256,uint256,uint160))
export const exactOutputSingleSchema = z.tuple([
  /* params: (address,address,uint24,address,uint256,uint256,uint256,uint160) */ z.tuple([
    /* tokenIn: address */ ADDRESS,
    /* tokenOut: address */ ADDRESS,
    /* fee: uint24 */ UINT24,
    /* recipient: address */ ADDRESS,
    /* deadline: uint256 */ UINT256,
    /* amountOut: uint256 */ UINT256,
    /* amountInMaximum: uint256 */ UINT256,
    /* sqrtPriceLimitX96: uint160 */ UINT160,
  ]),
]);

// factory()
export const factorySchema = z.tuple([]);

// multicall(bytes[])
export const multicallSchema = z.tuple([
  /* data: bytes[] */ z.array(BYTES),
]);

// refundETH()
export const refundETHSchema = z.tuple([]);

// selfPermit(address,uint256,uint256,uint8,bytes32,bytes32)
export const selfPermitSchema = z.tuple([
  /* token: address */ ADDRESS,
  /* value: uint256 */ UINT256,
  /* deadline: uint256 */ UINT256,
  /* v: uint8 */ UINT8,
  /* r: bytes32 */ BYTES32,
  /* s: bytes32 */ BYTES32,
]);

// selfPermitAllowed(address,uint256,uint256,uint8,bytes32,bytes32)
export const selfPermitAllowedSchema = z.tuple([
  /* token: address */ ADDRESS,
  /* nonce: uint256 */ UINT256,
  /* expiry: uint256 */ UINT256,
  /* v: uint8 */ UINT8,
  /* r: bytes32 */ BYTES32,
  /* s: bytes32 */ BYTES32,
]);

// selfPermitAllowedIfNecessary(address,uint256,uint256,uint8,bytes32,bytes32)
export const selfPermitAllowedIfNecessarySchema = z.tuple([
  /* token: address */ ADDRESS,
  /* nonce: uint256 */ UINT256,
  /* expiry: uint256 */ UINT256,
  /* v: uint8 */ UINT8,
  /* r: bytes32 */ BYTES32,
  /* s: bytes32 */ BYTES32,
]);

// selfPermitIfNecessary(address,uint256,uint256,uint8,bytes32,bytes32)
export const selfPermitIfNecessarySchema = z.tuple([
  /* token: address */ ADDRESS,
  /* value: uint256 */ UINT256,
  /* deadline: uint256 */ UINT256,
  /* v: uint8 */ UINT8,
  /* r: bytes32 */ BYTES32,
  /* s: bytes32 */ BYTES32,
]);

// sweepToken(address,uint256,address)
export const sweepTokenSchema = z.tuple([
  /* token: address */ ADDRESS,
  /* amountMinimum: uint256 */ UINT256,
  /* recipient: address */ ADDRESS,
]);

// sweepTokenWithFee(address,uint256,address,uint256,address)
export const sweepTokenWithFeeSchema = z.tuple([
  /* token: address */ ADDRESS,
  /* amountMinimum: uint256 */ UINT256,
  /* recipient: address */ ADDRESS,
  /* feeBips: uint256 */ UINT256,
  /* feeRecipient: address */ ADDRESS,
]);

// uniswapV3SwapCallback(int256,int256,bytes)
export const uniswapV3SwapCallbackSchema = z.tuple([
  /* amount0Delta: int256 */ INT256,
  /* amount1Delta: int256 */ INT256,
  /* _data: bytes */ BYTES,
]);

// unwrapWETH9(uint256,address)
export const unwrapWETH9Schema = z.tuple([
  /* amountMinimum: uint256 */ UINT256,
  /* recipient: address */ ADDRESS,
]);

// unwrapWETH9WithFee(uint256,address,uint256,address)
export const unwrapWETH9WithFeeSchema = z.tuple([
  /* amountMinimum: uint256 */ UINT256,
  /* recipient: address */ ADDRESS,
  /* feeBips: uint256 */ UINT256,
  /* feeRecipient: address */ ADDRESS,
]);

// === Lookup barrel (mirrors abiToZod) ===

export const schemas = {
  WETH9: WETH9Schema,
  exactInput: exactInputSchema,
  exactInputSingle: exactInputSingleSchema,
  exactOutput: exactOutputSchema,
  exactOutputSingle: exactOutputSingleSchema,
  factory: factorySchema,
  multicall: multicallSchema,
  refundETH: refundETHSchema,
  selfPermit: selfPermitSchema,
  selfPermitAllowed: selfPermitAllowedSchema,
  selfPermitAllowedIfNecessary: selfPermitAllowedIfNecessarySchema,
  selfPermitIfNecessary: selfPermitIfNecessarySchema,
  sweepToken: sweepTokenSchema,
  sweepTokenWithFee: sweepTokenWithFeeSchema,
  uniswapV3SwapCallback: uniswapV3SwapCallbackSchema,
  unwrapWETH9: unwrapWETH9Schema,
  unwrapWETH9WithFee: unwrapWETH9WithFeeSchema,
  'WETH9()': WETH9Schema,
  'exactInput((bytes,address,uint256,uint256,uint256))': exactInputSchema,
  'exactInputSingle((address,address,uint24,address,uint256,uint256,uint256,uint160))': exactInputSingleSchema,
  'exactOutput((bytes,address,uint256,uint256,uint256))': exactOutputSchema,
  'exactOutputSingle((address,address,uint24,address,uint256,uint256,uint256,uint160))': exactOutputSingleSchema,
  'factory()': factorySchema,
  'multicall(bytes[])': multicallSchema,
  'refundETH()': refundETHSchema,
  'selfPermit(address,uint256,uint256,uint8,bytes32,bytes32)': selfPermitSchema,
  'selfPermitAllowed(address,uint256,uint256,uint8,bytes32,bytes32)': selfPermitAllowedSchema,
  'selfPermitAllowedIfNecessary(address,uint256,uint256,uint8,bytes32,bytes32)': selfPermitAllowedIfNecessarySchema,
  'selfPermitIfNecessary(address,uint256,uint256,uint8,bytes32,bytes32)': selfPermitIfNecessarySchema,
  'sweepToken(address,uint256,address)': sweepTokenSchema,
  'sweepTokenWithFee(address,uint256,address,uint256,address)': sweepTokenWithFeeSchema,
  'uniswapV3SwapCallback(int256,int256,bytes)': uniswapV3SwapCallbackSchema,
  'unwrapWETH9(uint256,address)': unwrapWETH9Schema,
  'unwrapWETH9WithFee(uint256,address,uint256,address)': unwrapWETH9WithFeeSchema,
} as const;
