// Generated by abi-to-zod v0.0.0 from UniswapV2Router.json
// Do not edit manually -- regenerate from source.

import { z } from 'zod';

// === Primitive schemas (edit once to customise all uses) ===

const ADDRESS = z.string().regex(/^0x[0-9a-fA-F]{40}$/).transform((v) => v as `0x${string}`);
const BOOL = z.boolean();
const BYTES32 = z.string().regex(/^0x[0-9a-fA-F]{64}$/).transform((v) => v as `0x${string}`);
const UINT256 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 256n) - 1n);
const UINT8 = z.string().regex(/^\d+$/).transform((v) => BigInt(v)).refine((n) => n <= (1n << 8n) - 1n);

// === Function schemas ===

// WETH()
export const WETHSchema = z.tuple([]);

// addLiquidity(address,address,uint256,uint256,uint256,uint256,address,uint256)
export const addLiquiditySchema = z.tuple([
  /* tokenA: address */ ADDRESS,
  /* tokenB: address */ ADDRESS,
  /* amountADesired: uint256 */ UINT256,
  /* amountBDesired: uint256 */ UINT256,
  /* amountAMin: uint256 */ UINT256,
  /* amountBMin: uint256 */ UINT256,
  /* to: address */ ADDRESS,
  /* deadline: uint256 */ UINT256,
]);

// addLiquidityETH(address,uint256,uint256,uint256,address,uint256)
export const addLiquidityETHSchema = z.tuple([
  /* token: address */ ADDRESS,
  /* amountTokenDesired: uint256 */ UINT256,
  /* amountTokenMin: uint256 */ UINT256,
  /* amountETHMin: uint256 */ UINT256,
  /* to: address */ ADDRESS,
  /* deadline: uint256 */ UINT256,
]);

// factory()
export const factorySchema = z.tuple([]);

// getAmountIn(uint256,uint256,uint256)
export const getAmountInSchema = z.tuple([
  /* amountOut: uint256 */ UINT256,
  /* reserveIn: uint256 */ UINT256,
  /* reserveOut: uint256 */ UINT256,
]);

// getAmountOut(uint256,uint256,uint256)
export const getAmountOutSchema = z.tuple([
  /* amountIn: uint256 */ UINT256,
  /* reserveIn: uint256 */ UINT256,
  /* reserveOut: uint256 */ UINT256,
]);

// getAmountsIn(uint256,address[])
export const getAmountsInSchema = z.tuple([
  /* amountOut: uint256 */ UINT256,
  /* path: address[] */ z.array(ADDRESS),
]);

// getAmountsOut(uint256,address[])
export const getAmountsOutSchema = z.tuple([
  /* amountIn: uint256 */ UINT256,
  /* path: address[] */ z.array(ADDRESS),
]);

// quote(uint256,uint256,uint256)
export const quoteSchema = z.tuple([
  /* amountA: uint256 */ UINT256,
  /* reserveA: uint256 */ UINT256,
  /* reserveB: uint256 */ UINT256,
]);

// removeLiquidity(address,address,uint256,uint256,uint256,address,uint256)
export const removeLiquiditySchema = z.tuple([
  /* tokenA: address */ ADDRESS,
  /* tokenB: address */ ADDRESS,
  /* liquidity: uint256 */ UINT256,
  /* amountAMin: uint256 */ UINT256,
  /* amountBMin: uint256 */ UINT256,
  /* to: address */ ADDRESS,
  /* deadline: uint256 */ UINT256,
]);

// removeLiquidityETH(address,uint256,uint256,uint256,address,uint256)
export const removeLiquidityETHSchema = z.tuple([
  /* token: address */ ADDRESS,
  /* liquidity: uint256 */ UINT256,
  /* amountTokenMin: uint256 */ UINT256,
  /* amountETHMin: uint256 */ UINT256,
  /* to: address */ ADDRESS,
  /* deadline: uint256 */ UINT256,
]);

// removeLiquidityETHSupportingFeeOnTransferTokens(address,uint256,uint256,uint256,address,uint256)
export const removeLiquidityETHSupportingFeeOnTransferTokensSchema = z.tuple([
  /* token: address */ ADDRESS,
  /* liquidity: uint256 */ UINT256,
  /* amountTokenMin: uint256 */ UINT256,
  /* amountETHMin: uint256 */ UINT256,
  /* to: address */ ADDRESS,
  /* deadline: uint256 */ UINT256,
]);

// removeLiquidityETHWithPermit(address,uint256,uint256,uint256,address,uint256,bool,uint8,bytes32,bytes32)
export const removeLiquidityETHWithPermitSchema = z.tuple([
  /* token: address */ ADDRESS,
  /* liquidity: uint256 */ UINT256,
  /* amountTokenMin: uint256 */ UINT256,
  /* amountETHMin: uint256 */ UINT256,
  /* to: address */ ADDRESS,
  /* deadline: uint256 */ UINT256,
  /* approveMax: bool */ BOOL,
  /* v: uint8 */ UINT8,
  /* r: bytes32 */ BYTES32,
  /* s: bytes32 */ BYTES32,
]);

// removeLiquidityETHWithPermitSupportingFeeOnTransferTokens(address,uint256,uint256,uint256,address,uint256,bool,uint8,bytes32,bytes32)
export const removeLiquidityETHWithPermitSupportingFeeOnTransferTokensSchema = z.tuple([
  /* token: address */ ADDRESS,
  /* liquidity: uint256 */ UINT256,
  /* amountTokenMin: uint256 */ UINT256,
  /* amountETHMin: uint256 */ UINT256,
  /* to: address */ ADDRESS,
  /* deadline: uint256 */ UINT256,
  /* approveMax: bool */ BOOL,
  /* v: uint8 */ UINT8,
  /* r: bytes32 */ BYTES32,
  /* s: bytes32 */ BYTES32,
]);

// removeLiquidityWithPermit(address,address,uint256,uint256,uint256,address,uint256,bool,uint8,bytes32,bytes32)
export const removeLiquidityWithPermitSchema = z.tuple([
  /* tokenA: address */ ADDRESS,
  /* tokenB: address */ ADDRESS,
  /* liquidity: uint256 */ UINT256,
  /* amountAMin: uint256 */ UINT256,
  /* amountBMin: uint256 */ UINT256,
  /* to: address */ ADDRESS,
  /* deadline: uint256 */ UINT256,
  /* approveMax: bool */ BOOL,
  /* v: uint8 */ UINT8,
  /* r: bytes32 */ BYTES32,
  /* s: bytes32 */ BYTES32,
]);

// swapETHForExactTokens(uint256,address[],address,uint256)
export const swapETHForExactTokensSchema = z.tuple([
  /* amountOut: uint256 */ UINT256,
  /* path: address[] */ z.array(ADDRESS),
  /* to: address */ ADDRESS,
  /* deadline: uint256 */ UINT256,
]);

// swapExactETHForTokens(uint256,address[],address,uint256)
export const swapExactETHForTokensSchema = z.tuple([
  /* amountOutMin: uint256 */ UINT256,
  /* path: address[] */ z.array(ADDRESS),
  /* to: address */ ADDRESS,
  /* deadline: uint256 */ UINT256,
]);

// swapExactETHForTokensSupportingFeeOnTransferTokens(uint256,address[],address,uint256)
export const swapExactETHForTokensSupportingFeeOnTransferTokensSchema = z.tuple([
  /* amountOutMin: uint256 */ UINT256,
  /* path: address[] */ z.array(ADDRESS),
  /* to: address */ ADDRESS,
  /* deadline: uint256 */ UINT256,
]);

// swapExactTokensForETH(uint256,uint256,address[],address,uint256)
export const swapExactTokensForETHSchema = z.tuple([
  /* amountIn: uint256 */ UINT256,
  /* amountOutMin: uint256 */ UINT256,
  /* path: address[] */ z.array(ADDRESS),
  /* to: address */ ADDRESS,
  /* deadline: uint256 */ UINT256,
]);

// swapExactTokensForETHSupportingFeeOnTransferTokens(uint256,uint256,address[],address,uint256)
export const swapExactTokensForETHSupportingFeeOnTransferTokensSchema = z.tuple([
  /* amountIn: uint256 */ UINT256,
  /* amountOutMin: uint256 */ UINT256,
  /* path: address[] */ z.array(ADDRESS),
  /* to: address */ ADDRESS,
  /* deadline: uint256 */ UINT256,
]);

// swapExactTokensForTokens(uint256,uint256,address[],address,uint256)
export const swapExactTokensForTokensSchema = z.tuple([
  /* amountIn: uint256 */ UINT256,
  /* amountOutMin: uint256 */ UINT256,
  /* path: address[] */ z.array(ADDRESS),
  /* to: address */ ADDRESS,
  /* deadline: uint256 */ UINT256,
]);

// swapExactTokensForTokensSupportingFeeOnTransferTokens(uint256,uint256,address[],address,uint256)
export const swapExactTokensForTokensSupportingFeeOnTransferTokensSchema = z.tuple([
  /* amountIn: uint256 */ UINT256,
  /* amountOutMin: uint256 */ UINT256,
  /* path: address[] */ z.array(ADDRESS),
  /* to: address */ ADDRESS,
  /* deadline: uint256 */ UINT256,
]);

// swapTokensForExactETH(uint256,uint256,address[],address,uint256)
export const swapTokensForExactETHSchema = z.tuple([
  /* amountOut: uint256 */ UINT256,
  /* amountInMax: uint256 */ UINT256,
  /* path: address[] */ z.array(ADDRESS),
  /* to: address */ ADDRESS,
  /* deadline: uint256 */ UINT256,
]);

// swapTokensForExactTokens(uint256,uint256,address[],address,uint256)
export const swapTokensForExactTokensSchema = z.tuple([
  /* amountOut: uint256 */ UINT256,
  /* amountInMax: uint256 */ UINT256,
  /* path: address[] */ z.array(ADDRESS),
  /* to: address */ ADDRESS,
  /* deadline: uint256 */ UINT256,
]);

// === Lookup barrel (mirrors abiToZod) ===

export const schemas = {
  WETH: WETHSchema,
  addLiquidity: addLiquiditySchema,
  addLiquidityETH: addLiquidityETHSchema,
  factory: factorySchema,
  getAmountIn: getAmountInSchema,
  getAmountOut: getAmountOutSchema,
  getAmountsIn: getAmountsInSchema,
  getAmountsOut: getAmountsOutSchema,
  quote: quoteSchema,
  removeLiquidity: removeLiquiditySchema,
  removeLiquidityETH: removeLiquidityETHSchema,
  removeLiquidityETHSupportingFeeOnTransferTokens: removeLiquidityETHSupportingFeeOnTransferTokensSchema,
  removeLiquidityETHWithPermit: removeLiquidityETHWithPermitSchema,
  removeLiquidityETHWithPermitSupportingFeeOnTransferTokens: removeLiquidityETHWithPermitSupportingFeeOnTransferTokensSchema,
  removeLiquidityWithPermit: removeLiquidityWithPermitSchema,
  swapETHForExactTokens: swapETHForExactTokensSchema,
  swapExactETHForTokens: swapExactETHForTokensSchema,
  swapExactETHForTokensSupportingFeeOnTransferTokens: swapExactETHForTokensSupportingFeeOnTransferTokensSchema,
  swapExactTokensForETH: swapExactTokensForETHSchema,
  swapExactTokensForETHSupportingFeeOnTransferTokens: swapExactTokensForETHSupportingFeeOnTransferTokensSchema,
  swapExactTokensForTokens: swapExactTokensForTokensSchema,
  swapExactTokensForTokensSupportingFeeOnTransferTokens: swapExactTokensForTokensSupportingFeeOnTransferTokensSchema,
  swapTokensForExactETH: swapTokensForExactETHSchema,
  swapTokensForExactTokens: swapTokensForExactTokensSchema,
  'WETH()': WETHSchema,
  'addLiquidity(address,address,uint256,uint256,uint256,uint256,address,uint256)': addLiquiditySchema,
  'addLiquidityETH(address,uint256,uint256,uint256,address,uint256)': addLiquidityETHSchema,
  'factory()': factorySchema,
  'getAmountIn(uint256,uint256,uint256)': getAmountInSchema,
  'getAmountOut(uint256,uint256,uint256)': getAmountOutSchema,
  'getAmountsIn(uint256,address[])': getAmountsInSchema,
  'getAmountsOut(uint256,address[])': getAmountsOutSchema,
  'quote(uint256,uint256,uint256)': quoteSchema,
  'removeLiquidity(address,address,uint256,uint256,uint256,address,uint256)': removeLiquiditySchema,
  'removeLiquidityETH(address,uint256,uint256,uint256,address,uint256)': removeLiquidityETHSchema,
  'removeLiquidityETHSupportingFeeOnTransferTokens(address,uint256,uint256,uint256,address,uint256)': removeLiquidityETHSupportingFeeOnTransferTokensSchema,
  'removeLiquidityETHWithPermit(address,uint256,uint256,uint256,address,uint256,bool,uint8,bytes32,bytes32)': removeLiquidityETHWithPermitSchema,
  'removeLiquidityETHWithPermitSupportingFeeOnTransferTokens(address,uint256,uint256,uint256,address,uint256,bool,uint8,bytes32,bytes32)': removeLiquidityETHWithPermitSupportingFeeOnTransferTokensSchema,
  'removeLiquidityWithPermit(address,address,uint256,uint256,uint256,address,uint256,bool,uint8,bytes32,bytes32)': removeLiquidityWithPermitSchema,
  'swapETHForExactTokens(uint256,address[],address,uint256)': swapETHForExactTokensSchema,
  'swapExactETHForTokens(uint256,address[],address,uint256)': swapExactETHForTokensSchema,
  'swapExactETHForTokensSupportingFeeOnTransferTokens(uint256,address[],address,uint256)': swapExactETHForTokensSupportingFeeOnTransferTokensSchema,
  'swapExactTokensForETH(uint256,uint256,address[],address,uint256)': swapExactTokensForETHSchema,
  'swapExactTokensForETHSupportingFeeOnTransferTokens(uint256,uint256,address[],address,uint256)': swapExactTokensForETHSupportingFeeOnTransferTokensSchema,
  'swapExactTokensForTokens(uint256,uint256,address[],address,uint256)': swapExactTokensForTokensSchema,
  'swapExactTokensForTokensSupportingFeeOnTransferTokens(uint256,uint256,address[],address,uint256)': swapExactTokensForTokensSupportingFeeOnTransferTokensSchema,
  'swapTokensForExactETH(uint256,uint256,address[],address,uint256)': swapTokensForExactETHSchema,
  'swapTokensForExactTokens(uint256,uint256,address[],address,uint256)': swapTokensForExactTokensSchema,
} as const;
